Fixing code comment for the put method of MultiMap.
hazelcast/hazelcast pull request #17678
Opened 2020-10-05 08:35 UTC by Serdaro

2022-02-14 09:57 UTC, AyberkSorgun commented
@asimarslan could you review?

2022-02-15 10:47 UTC, ahmetmircik commented on hazelcast/src/main/java/com/hazelcast/multimap/MultiMap.java
> +     * the collection type is LIST
For `LIST` type, method `put` returns true. To reword concisely we can have something like this:

```
{@code false} if the multimap already contained the key-value pair and doesn't allow duplicates
      
```

2022-02-15 10:47 UTC, ahmetmircik requested changes
please see my comment

2022-02-15 11:16 UTC, Serdaro commented
Couldn't find the PR branch. Opened a new PR: https://github.com/hazelcast/hazelcast/pull/20723

2022-02-15 11:16 UTC, closed without merging