Remove extra check on invocation notifyResponse
hazelcast/hazelcast pull request #17703
Opened 2020-10-08 10:22 UTC by ihsandemir

We seem to not need this extra check. See discussion https://github.com/hazelcast/hazelcast-cpp-client/pull/639#discussion_r501590189

2020-10-08 11:08 UTC, sancar requested changes
We need this check on java. Take another look.

2020-10-08 16:33 UTC, hz-highfive commented
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/2652/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/2652/Hazelcast-pr-builder-2652.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>

</details>
</pre>

2020-10-09 13:04 UTC, ihsandemir commented
> We need this check on java. We have multiple threads accessing notifyResponse and notifybackupComplete. It is not single-threaded as we have in c++ client.

@sancar But it is already being checked a few lines above (https://github.com/hazelcast/hazelcast/pull/17703/files#diff-c9d1c54bed27cc8418a9fa480bd6e0c7R85).

2020-10-09 13:07 UTC, ihsandemir commented
run-lab-run

2020-10-09 13:25 UTC, ihsandemir commented
seems like we still need the check.

2020-10-09 13:25 UTC, closed without merging

2020-10-09 17:09 UTC, hz-highfive commented
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/2660/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/2660/Hazelcast-pr-builder-2660.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>

</details>
</pre>