adding #deleteAsync to IMap
hazelcast/hazelcast pull request #17739
Opened 2020-10-17 00:35 UTC by keteracel

Fixes https://github.com/hazelcast/hazelcast/issues/10702 by adding `deleteAsync` functionality to `IMap`.

2020-10-17 00:35 UTC, devOpsHazelcast commented
Can one of the admins verify this patch?

2020-10-28 16:03 UTC, mmedenjak commented
run-lab-run

2020-10-28 16:04 UTC, mmedenjak commented
Hi @keteracel ! Thank you for the PR and sorry for the long delay. Last week or two have been hectic. I've assigned reviewers and we'll take a look. Feel free to ping us here or on community slack if we're unresponsive.

2020-11-16 14:45 UTC, ahmetmircik commented
Hi @keteracel, could you please do required changes for `NearCachedMapProxyImpl` and `NearCachedClientMapProxy` classes as well?

2020-11-18 11:18 UTC, ahmetmircik requested changes
https://github.com/hazelcast/hazelcast/pull/17739#issuecomment-728107464

2023-08-16 06:02 UTC, pveentjer commented
Closing PR since it seems to be abandoned.

2023-08-16 06:02 UTC, closed without merging