Add test for detecting inconsistencies between declarative and programmatic config
hazelcast/hazelcast pull request #18239
Opened 2021-02-18 16:06 UTC by ramizdundar

Fixes #18221

2021-02-22 12:52 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed.
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.1:checkstyle (default) on project hazelcast: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There is 1 error reported by Checkstyle 8.38 with /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_2/checkstyle/checkstyle.xml ruleset. -> [Help 1]
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_2/hazelcast/src/test/java/com/hazelcast/config/DefaultConfigValidationTest.java:1: Line does not match expected header line of '/*'. [Header]
--------------------------
</pre>
</details>

2021-02-22 14:05 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed.
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.1:checkstyle (default) on project hazelcast: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There is 1 error reported by Checkstyle 8.38 with /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_3/checkstyle/checkstyle.xml ruleset. -> [Help 1]
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_3/hazelcast/src/test/java/com/hazelcast/config/DefaultConfigValidationTest.java:1: Line does not match expected header line of '/*'. [Header]
--------------------------
</pre>
</details>

2021-02-23 11:09 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed.
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.1:checkstyle (default) on project hazelcast: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There are 4 errors reported by Checkstyle 8.38 with /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/checkstyle/checkstyle.xml ruleset. -> [Help 1]
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/test/java/com/hazelcast/config/DefaultConfigValidationTest.java:1: Line does not match expected header line of '/*'. [Header]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/test/java/com/hazelcast/config/DefaultConfigValidationTest.java:98:106: '+' should be on a new line. [OperatorWrap]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/test/java/com/hazelcast/config/DefaultConfigValidationTest.java:104:98: '+' should be on a new line. [OperatorWrap]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/test/java/com/hazelcast/config/DefaultConfigValidationTest.java:108:128: '+' should be on a new line. [OperatorWrap]
--------------------------
</pre>
</details>

2021-02-23 12:37 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed.
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.1:checkstyle (default) on project hazelcast: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There are 2 errors reported by Checkstyle 8.38 with /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_3/checkstyle/checkstyle.xml ruleset. -> [Help 1]
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_3/hazelcast/src/test/java/com/hazelcast/config/DefaultConfigValidationTest.java:138:68: '{' is not preceded with whitespace. [WhitespaceAround]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_3/hazelcast/src/test/java/com/hazelcast/config/DefaultConfigValidationTest.java:143:25: '}' at column 25 should be on the same line as the next part of a multi-block statement (one that directly contains multiple blocks: if/else-if/else, do/while or try/catch/finally). [RightCurly]
--------------------------
</pre>
</details>

2021-02-23 13:00 UTC, ramizdundar commented
There are 4 kind of differences:

**Case 1**: There is no same argument constructor with get method

- com.hazelcast.config.SplitBrainProtectionConfig (Child of com.hazelcast.config.Config) does not have a suitable constructor. Note that getter of this config doesn't return null.
- com.hazelcast.config.security.CredentialsIdentityConfig (Child of com.hazelcast.client.config.ClientSecurityConfig) does not have a suitable constructor.
- com.hazelcast.config.security.TokenIdentityConfig (Child of com.hazelcast.client.config.ClientSecurityConfig) does not have a suitable constructor.
- com.hazelcast.config.security.UsernamePasswordIdentityConfig (Child of com.hazelcast.client.config.ClientSecurityConfig) does not have a suitable constructor.


**Case 2**: There are abstract config classes

- Error occurred while calling the constructor of com.hazelcast.config.SecureStoreConfig (Child of com.hazelcast.config.EncryptionAtRestConfig)

**Case 3**: There are configurations that take multiple parameters inside getter methods. (Special case of case 1)

- com.hazelcast.config.QueryCacheConfig (Child of com.hazelcast.client.config.ClientConfig) called from getOrNullQueryCacheConfig
- com.hazelcast.config.QueryCacheConfig (Child of com.hazelcast.client.config.ClientConfig) called from getOrCreateQueryCacheConfig

**Case 4**: There are situations where default and initial configs are not the same. These are the cases we initially want to test.

- com.hazelcast.config.NetworkConfig (Child of com.hazelcast.config.Config) failed the test.
- com.hazelcast.config.AdvancedNetworkConfig (Child of com.hazelcast.config.Config) failed the test.
- com.hazelcast.config.EvictionConfig (Child of com.hazelcast.config.MapConfig) failed the test.
- com.hazelcast.config.MapStoreConfig (Child of com.hazelcast.config.MapConfig) failed the test.
- com.hazelcast.config.RingbufferStoreConfig (Child of com.hazelcast.config.RingbufferConfig) failed the test.
- com.hazelcast.config.MergePolicyConfig (Child of com.hazelcast.config.CardinalityEstimatorConfig) failed the test.

2021-02-23 13:12 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed.
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal com.github.spotbugs:spotbugs-maven-plugin:4.1.4:check (default) on project hazelcast: failed with 1 bugs and 0 errors -> [Help 1]
--------------------------
</pre>
</details>

2021-02-23 13:20 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed.
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal com.github.spotbugs:spotbugs-maven-plugin:4.1.4:check (default) on project hazelcast: failed with 1 bugs and 0 errors -> [Help 1]
--------------------------
</pre>
</details>

2021-02-25 14:08 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed.
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal com.github.spotbugs:spotbugs-maven-plugin:4.1.4:check (default) on project hazelcast: failed with 2 bugs and 0 errors -> [Help 1]
--------------------------
</pre>
</details>

2021-02-25 14:12 UTC, ramizdundar commented
There are 5 situations where default and initial configs differ:

- com.hazelcast.config.SplitBrainProtectionConfig (Child of com.hazelcast.config.Config) failed the test. Because the constructor we added to `SplitBrainProtectionConfig` has `this.enabled = true`. Similar to `MapStoreConfig`.
- com.hazelcast.config.EvictionConfig (Child of com.hazelcast.config.MapConfig) failed the test. Because size is set to `UNSET` in `EvictionConfig`(default) and `DEFAULT_MAX_SIZE` in `MapConfig`(initial).
- com.hazelcast.config.MapStoreConfig (Child of com.hazelcast.config.MapConfig) failed the test. #18216 
- com.hazelcast.config.RingbufferStoreConfig (Child of com.hazelcast.config.RingbufferConfig) failed the test. Similar to `MapStoreConfig`.
- com.hazelcast.config.MergePolicyConfig (Child of com.hazelcast.config.CardinalityEstimatorConfig) failed the test. Because policies differ. `PutIfAbsentMergePolicy` in `MergePolicyConfig`(default) and `HyperLogLogMergePolicy` in `CardinalityEstimatorConfig`(initial)

2021-02-25 15:11 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed.
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   DefaultConfigValidationTest.validateServerConfiguration:63 expected:<0> but was:<5>
[INFO] 
[ERROR] Tests run: 36146, Failures: 1, Errors: 0, Skipped: 988
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2021-03-01 14:30 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed.
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.1:checkstyle (default) on project hazelcast: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There is 1 error reported by Checkstyle 8.38 with /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_2/checkstyle/checkstyle.xml ruleset. -> [Help 1]
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_2/hazelcast/src/test/java/com/hazelcast/config/SplitBrainProtectionConfigTest.java:1: File does not end with a newline. [NewlineAtEndOfFile]
--------------------------
</pre>
</details>

2021-03-03 10:10 UTC, blazember requested changes
LGTM, added a few minors and one on `SplitBrainProtectionConfig` that I think is a non-valid change.

2021-03-03 10:10 UTC, blazember commented on hazelcast/src/test/java/com/hazelcast/config/DefaultConfigValidationTest.java
> +                throws InvocationTargetException, IllegalAccessException, InstantiationException, NoSuchMethodException {
Can be simplified to `throws Exception`.

2021-03-03 10:10 UTC, blazember commented on hazelcast/src/test/java/com/hazelcast/config/DefaultConfigValidationTest.java
> +    private static int numberOfTestedConfigs = 0;
This one shouldn't be `static`.

2021-03-03 10:10 UTC, blazember commented on hazelcast/src/test/java/com/hazelcast/config/DefaultConfigValidationTest.java
> +    }
I think we're better to add a short comment for each why they are ignored before we forget the reason.

2021-03-03 10:40 UTC, ramizdundar commented on hazelcast/src/main/java/com/hazelcast/config/SplitBrainProtectionConfig.java
> +        this.enabled = true;
I thought just like how `MapStoreConfig` has enabled by default this should also enabled but I will change.

2021-03-03 12:45 UTC, Fly-Style approved these changes
LGTM except notes from @blazember.
Good job, thanks!

2021-03-04 07:38 UTC, mmedenjak commented
@ramizdundar moving to the next milestone to clear up the non-critical issues and PRs. But please keep working on it and get it reviewed. If it gets approved before the release branch is created, just merge it to master and change the milestone back for the PR and issue.

2021-03-04 07:40 UTC, ramizdundar commented
@mmedenjak ok hopefully it'll get approved soon if nothing goes wrong.

2021-03-04 08:54 UTC, blazember approved these changes
LGTM, thanks @ramizdundar for picking this up :+1:

2021-03-04 08:58 UTC, merged