Implement type coercion for UDFs
hazelcast/hazelcast pull request #18274
Opened 2021-02-23 12:03 UTC by gierlachg

2021-02-24 12:40 UTC, taburet approved these changes

2021-02-24 15:53 UTC, viliam-durina requested changes
We miss any test where it would fail without this method. There's one in the issue (#2891). I actually don't know why this method isn't always called for UDFs, there's probably some short-circuit code if the types match exactly.

2021-02-25 07:22 UTC, gierlachg commented
I could not find an easy way to test it in IMDG. I have a test in Jet when this is merged.

2021-02-25 07:50 UTC, viliam-durina approved these changes

2021-02-25 08:04 UTC, merged