Support dynamic parameters in Jet SQL engine
hazelcast/hazelcast pull request #18522
Opened 2021-04-13 14:35 UTC by gierlachg

2021-04-13 15:36 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/4592/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/4592/Hazelcast-pr-builder-4592.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.1:checkstyle (default) on project hazelcast: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There are 2 errors reported by Checkstyle 8.38 with /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_2/checkstyle/checkstyle.xml ruleset. -> [Help 1]
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_2/hazelcast/src/test/java/com/hazelcast/jet/core/TopologyChangeTest.java:74:15: Unused import - java.util.Collections.emptyList. [UnusedImports]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_2/hazelcast/src/test/java/com/hazelcast/jet/impl/execution/init/VertexDef_HigherPrioritySourceTest.java:132:106: ',' is not followed by whitespace. [WhitespaceAfter]
--------------------------
</pre>
</details>

2021-04-14 14:40 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/4608/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/4608/Hazelcast-pr-builder-4608.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   HzSerializableProcessorSuppliersTest.test_metaSupplier ? HazelcastSerialization
[ERROR]   HzSerializableProcessorSuppliersTest.test_pSupplier ? HazelcastSerialization E...
[ERROR]   HzSerializableProcessorSuppliersTest.test_simpleSupplier ? HazelcastSerialization
[ERROR]   JetCommandLineTest.test_submit:447->run:668 ? Execution Error while calling co...
[ERROR]   JetCommandLineTest.test_submit_argsPassing:488->run:668 ? Execution Error whil...
[ERROR]   JetCommandLineTest.test_submit_clientShutdownWhenDone:456->run:668 ? Execution
[ERROR]   JetCommandLineTest.test_submit_nameUsed:465->run:668 ? Execution Error while c...
[ERROR]   JetCommandLineTest.test_submit_withClassName:473->run:668 ? Execution Error wh...
[INFO] 
[ERROR] Tests run: 38329, Failures: 0, Errors: 8, Skipped: 1000
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2021-04-15 09:15 UTC, alex-dukhno approved these changes

2021-04-15 14:00 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/4641/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/4641/Hazelcast-pr-builder-4641.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   HzSerializableProcessorSuppliersTest.test_metaSupplier ? HazelcastSerialization
[ERROR]   HzSerializableProcessorSuppliersTest.test_pSupplier ? HazelcastSerialization E...
[ERROR]   HzSerializableProcessorSuppliersTest.test_simpleSupplier ? HazelcastSerialization
[ERROR]   JetCommandLineTest.test_submit:447->run:668 ? Execution Error while calling co...
[ERROR]   JetCommandLineTest.test_submit_argsPassing:488->run:668 ? Execution Error whil...
[ERROR]   JetCommandLineTest.test_submit_clientShutdownWhenDone:456->run:668 ? Execution
[ERROR]   JetCommandLineTest.test_submit_nameUsed:465->run:668 ? Execution Error while c...
[ERROR]   JetCommandLineTest.test_submit_withClassName:473->run:668 ? Execution Error wh...
[INFO] 
[ERROR] Tests run: 38329, Failures: 0, Errors: 8, Skipped: 999
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2021-04-19 15:41 UTC, viliam-durina requested changes

2021-04-19 15:45 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/4699/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/4699/Hazelcast-pr-builder-4699.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:license-maven-plugin:1.19:add-third-party (default) on project hazelcast-jet-files-gcs: could not init goal AddThirdPartyMojo for reason : null: NoSuchElementException -> [Help 1]
--------------------------
</pre>
</details>

2021-04-20 12:01 UTC, gierlachg commented on hazelcast-jet-sql/src/main/java/com/hazelcast/jet/sql/impl/JetPlan.java
> +            assert arguments.isEmpty();
We should never reach this point for dynamic parameters and i.e. `CREATE MAPPING` - it fails at parsing. Also I don't see much value in creating tests for such cases as we would pretty much test `Calcite` parser.

2021-04-20 14:50 UTC, gierlachg commented on hazelcast-jet-sql/src/main/java/com/hazelcast/jet/sql/impl/JetPlanExecutor.java
> +                    "Unexpected parameter count: expected " + parameterCount + ", got " + arguments.size()
Yes. Added test.

2021-04-20 14:51 UTC, gierlachg commented on hazelcast-jet-sql/src/main/java/com/hazelcast/jet/sql/impl/schema/UnknownStatistic.java
> +        return 0D;
Reverted back to `null` - had to change `HazelcastTable` a bit to accommodate that.

2021-04-20 15:25 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/4716/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/4716/Hazelcast-pr-builder-4716.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   SqlClientTest.test_jetJobReturnRowsToClientFrom:60 value already seen: 0
[INFO] 
[ERROR] Tests run: 1273, Failures: 1, Errors: 0, Skipped: 110
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2021-04-21 07:39 UTC, gierlachg commented on hazelcast-jet-sql/src/test/java/com/hazelcast/jet/sql/impl/connector/file/SqlCsvTest.java
> +                        + " path => '" + RESOURCES_PATH + "'"
The problem is we don't have access to arguments in file table functions. I can try to change that in subsequent PR but I would leave this as it is in this one.

2021-04-22 07:16 UTC, viliam-durina commented on hazelcast-jet-sql/src/main/java/com/hazelcast/jet/sql/impl/JetPlan.java
> +            assert arguments.isEmpty();
I tried this code:
```java
sqlService.execute("create mapping t type TestBatch", "param0");
```
and got:
```
java.lang.AssertionError
	at com.hazelcast.jet.sql.impl.JetPlan$CreateMappingPlan.execute(JetPlan.java:100)
        ...
```

2021-04-22 08:11 UTC, viliam-durina approved these changes

2021-04-22 08:47 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/4753/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/4753/Hazelcast-pr-builder-4753.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   JoinByEquiJoinProcessorTest.test_innerJoin:74->runTest:164 ? NullPointer
[ERROR]   JoinByEquiJoinProcessorTest.test_outerJoin:106->runTest:164 ? NullPointer
[ERROR]   JoinByEquiJoinProcessorTest.when_innerJoinFilteredOutByCondition_then_absent:98->runTest:164 ? NullPointer
[ERROR]   JoinByEquiJoinProcessorTest.when_innerJoinFilteredOutByProjector_then_absent:82->runTest:164 ? NullPointer
[ERROR]   JoinByEquiJoinProcessorTest.when_innerJoinProjectedByProjector_then_modified:90->runTest:164 ? NullPointer
[ERROR]   JoinByEquiJoinProcessorTest.when_outerJoinFilteredOutByCondition_then_absent:130->runTest:164 ? NullPointer
[ERROR]   JoinByEquiJoinProcessorTest.when_outerJoinFilteredOutByProjector_then_absent:114->runTest:164 ? NullPointer
[ERROR]   JoinByEquiJoinProcessorTest.when_outerJoinProjectedByProjector_then_modified:122->runTest:164 ? NullPointer
[ERROR]   JoinByPrimitiveKeyProcessorTest.when_innerJoinFilteredOutByCondition_then_absent:99->runTest:168 ? NullPointer
[ERROR]   JoinByPrimitiveKeyProcessorTest.when_innerJoinFilteredOutByProjector_then_emptyResult:83->runTest:168 ? NullPointer
[ERROR]   JoinByPrimitiveKeyProcessorTest.when_innerJoinLeftKeyIsNull_then_emptyResult:68->runTest:168 ? NullPointer
[ERROR]   JoinByPrimitiveKeyProcessorTest.when_innerJoinProjectedByProjector_then_modified:91->runTest:168 ? NullPointer
[ERROR]   JoinByPrimitiveKeyProcessorTest.when_innerJoinRightValueIsNull_then_emptyResult:75->runTest:168 ? NullPointer
[ERROR]   JoinByPrimitiveKeyProcessorTest.when_outerJoinFilteredOutByCondition_then_nulls:137->runTest:168 ? NullPointer
[ERROR]   JoinByPrimitiveKeyProcessorTest.when_outerJoinFilteredOutByProjector_then_nulls:121->runTest:168 ? NullPointer
[ERROR]   JoinByPrimitiveKeyProcessorTest.when_outerJoinLeftKeyIsNull_then_nulls:106->runTest:168 ? NullPointer
[ERROR]   JoinByPrimitiveKeyProcessorTest.when_outerJoinProjectedByProjector_then_modified:129->runTest:168 ? NullPointer
[ERROR]   JoinByPrimitiveKeyProcessorTest.when_outerJoinRightValueIsNull_then_nulls:113->runTest:168 ? NullPointer
[ERROR]   JoinScanProcessorTest.test_innerJoin:82->runTest:176 ? NullPointer
[ERROR]   JoinScanProcessorTest.test_outerJoin:114->runTest:176 ? NullPointer
[ERROR]   JoinScanProcessorTest.when_innerJoinFilteredOutByCondition_then_absent:106->runTest:176 ? NullPointer
[ERROR]   JoinScanProcessorTest.when_innerJoinFilteredOutByProjector_then_absent:90->runTest:176 ? NullPointer
[ERROR]   JoinScanProcessorTest.when_innerJoinProjectedByProjector_then_modified:98->runTest:176 ? NullPointer
[ERROR]   JoinScanProcessorTest.when_outerJoinFilteredOutByCondition_then_absent:142->runTest:176 ? NullPointer
[ERROR]   JoinScanProcessorTest.when_outerJoinFilteredOutByProjector_then_absent:122->runTest:176 ? NullPointer
[ERROR]   JoinScanProcessorTest.when_outerJoinProjectedByProjector_then_modified:130->runTest:176 ? NullPointer
[INFO] 
[ERROR] Tests run: 1285, Failures: 0, Errors: 26, Skipped: 110
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2021-04-22 10:43 UTC, merged