Forbid renaming __key & this for KV connectors
hazelcast/hazelcast pull request #18703
Opened 2021-05-18 12:22 UTC by gierlachg

Forbade renaming `__key` & `this` for KV connectors.

\+ couple of minor cleanups:
- moved `extractFields()` & `maybeAddDefaultField()` from `KvMetadataResolvers` to `KvMetadataResolver`.
- moved `when_noFieldsResolved_then_wholeValueMapped()` from `SqlMappingTest` to `SqlPojoTest`.

Fixes #18691

2021-05-18 12:57 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/5112/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/5112/Hazelcast-pr-builder-5112.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ExecutionLifecycleTest.when_processorProcessThrows_then_failJob:328->assertPsClosedWithError:748 expected:<2> but was:<3>
[INFO] 
[ERROR] Tests run: 38368, Failures: 1, Errors: 0, Skipped: 1004
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2021-05-18 13:01 UTC, gierlachg commented
run-lab-run

2021-05-18 13:43 UTC, gierlachg commented
run-lab-run

2021-05-21 07:23 UTC, viliam-durina requested changes

2021-05-21 07:23 UTC, viliam-durina commented on hazelcast-sql/src/test/java/com/hazelcast/jet/sql/impl/connector/map/SqlPojoTest.java
> +
The following test if added to this class fails:
```java
    @Test
    public void when_keyHasKeyField_then_wholeKeyResolved() {
        String name = randomName();
        sqlService.execute(javaSerializableMapDdl(name, ClassWithKey.class, Integer.class));
        instance().getMap(name).put(new ClassWithKey(), 0);
        assertRowsAnyOrder("SELECT * FROM " + name,
                singletonList(new Row(new ClassWithKey(), 0)));
    }

    public static class ClassWithKey implements Serializable {
        public int __key;

        @Override
        public boolean equals(Object o) {
            if (this == o) {
                return true;
            }
            if (o == null || getClass() != o.getClass()) {
                return false;
            }
            ClassWithKey that = (ClassWithKey) o;
            return __key == that.__key;
        }

        @Override
        public int hashCode() {
            return Objects.hash(__key);
        }
    }
```

The `ClassWithKey` has a `__key` field. What happened is that we mapped the key's field under the `__key` name, and the whole key isn't mapped.

The point of this PR is to make sure that `__key` *always* maps the whole key. It's required for the DELETE functionality.

2021-05-24 07:34 UTC, alex-dukhno approved these changes

2021-05-24 10:32 UTC, viliam-durina approved these changes

2021-05-24 10:42 UTC, merged