[PLAT-256] Support for UPDATE from IMap
hazelcast/hazelcast pull request #18734
Opened 2021-05-21 09:10 UTC by alex-dukhno

<PR description here>

This PR adds support for `UPDATE` sql query from a IMap

Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [x] Add `Add to Release Notes` label if changes should be mentioned in release notes or `Not Release Notes content` if changes are not relevant for release notes

2021-05-21 09:45 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/5170/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/5170/Hazelcast-pr-builder-5170.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   SqlOrderByTest.testNestedFetchOffsetNotSupported:605->HazelcastTestSupport.assertThrows:1447 Unexpected java.lang.AssertionError exception type thrown with message:
expected:<0> but was:<5>
[ERROR]   SqlOrderByTest.testNestedFetchOffsetNotSupported:605->HazelcastTestSupport.assertThrows:1447 Unexpected java.lang.AssertionError exception type thrown with message:
expected:<0> but was:<5>
[ERROR]   SqlOrderByTest.testNestedFetchOffsetNotSupported:605->HazelcastTestSupport.assertThrows:1447 Unexpected java.lang.AssertionError exception type thrown with message:
expected:<0> but was:<5>
[ERROR]   SqlOrderByTest.testNestedFetchOffsetNotSupported:605->HazelcastTestSupport.assertThrows:1447 Unexpected java.lang.AssertionError exception type thrown with message:
expected:<0> but was:<5>
[INFO] 
[ERROR] Tests run: 2447, Failures: 4, Errors: 0, Skipped: 112
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2021-05-26 07:20 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/5219/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/5219/Hazelcast-pr-builder-5219.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.1:checkstyle (default) on project hazelcast-sql: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There are 4 errors reported by Checkstyle 8.38 with /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/checkstyle/checkstyle.xml ruleset. -> [Help 1]
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/validate/JetSqlValidator.java:24:8: Unused import - com.hazelcast.sql.impl.calcite.validate.HazelcastSqlOperatorTable. [UnusedImports]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/validate/JetSqlValidator.java:29:8: Unused import - org.apache.calcite.sql.SqlDataTypeSpec. [UnusedImports]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/validate/JetSqlValidator.java:39:8: Unused import - org.apache.calcite.sql.parser.SqlParserPos. [UnusedImports]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/validate/JetSqlValidator.java:40:8: Unused import - org.apache.calcite.sql.type.SqlTypeUtil. [UnusedImports]
--------------------------
</pre>
</details>

2021-05-26 08:27 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/5220/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/5220/Hazelcast-pr-builder-5220.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   SqlOrderByTest.testNestedFetchOffsetNotSupported:605->HazelcastTestSupport.assertThrows:1447 Unexpected java.lang.AssertionError exception type thrown with message:
expected:<0> but was:<5>
[ERROR]   SqlOrderByTest.testNestedFetchOffsetNotSupported:605->HazelcastTestSupport.assertThrows:1447 Unexpected java.lang.AssertionError exception type thrown with message:
expected:<0> but was:<5>
[ERROR]   SqlOrderByTest.testNestedFetchOffsetNotSupported:605->HazelcastTestSupport.assertThrows:1447 Unexpected java.lang.AssertionError exception type thrown with message:
expected:<0> but was:<5>
[ERROR]   SqlOrderByTest.testNestedFetchOffsetNotSupported:605->HazelcastTestSupport.assertThrows:1447 Unexpected java.lang.AssertionError exception type thrown with message:
expected:<0> but was:<5>
[INFO] 
[ERROR] Tests run: 2454, Failures: 4, Errors: 0, Skipped: 112
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2021-05-26 09:10 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/5221/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/5221/Hazelcast-pr-builder-5221.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   SqlOrderByTest.testNestedFetchOffsetNotSupported:605->HazelcastTestSupport.assertThrows:1447 Unexpected java.lang.AssertionError exception type thrown with message:
expected:<0> but was:<5>
[ERROR]   SqlOrderByTest.testNestedFetchOffsetNotSupported:605->HazelcastTestSupport.assertThrows:1447 Unexpected java.lang.AssertionError exception type thrown with message:
expected:<0> but was:<5>
[ERROR]   SqlOrderByTest.testNestedFetchOffsetNotSupported:605->HazelcastTestSupport.assertThrows:1447 Unexpected java.lang.AssertionError exception type thrown with message:
expected:<0> but was:<5>
[ERROR]   SqlOrderByTest.testNestedFetchOffsetNotSupported:605->HazelcastTestSupport.assertThrows:1447 Unexpected java.lang.AssertionError exception type thrown with message:
expected:<0> but was:<5>
[INFO] 
[ERROR] Tests run: 2454, Failures: 4, Errors: 0, Skipped: 112
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2021-05-26 14:59 UTC, viliam-durina requested changes
The update processor needs to be reworked to a single entry-processor call. Currently it uses a blocking `imap.get` in one vertex, constructs the new value and then sends to the sink - this is racy and slow.

2021-05-26 15:32 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/5236/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/5236/Hazelcast-pr-builder-5236.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   CacheSplitBrainProtectionWriteTest.setUp:73->AbstractSplitBrainProtectionTest.initTestEnvironment:105->AbstractSplitBrainProtectionTest.initCluster:247 ? SplitBrainProtection
[INFO] 
[ERROR] Tests run: 38463, Failures: 0, Errors: 1, Skipped: 1003
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2021-05-31 13:17 UTC, viliam-durina requested changes

2021-05-31 13:17 UTC, viliam-durina commented on hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/map/UpdateProcessor.java
> +            map.submitToKey(
We must track the future: not submit too many of them and check for errors.

2021-07-05 13:05 UTC, mmedenjak commented
Closing as superseded by https://github.com/hazelcast/hazelcast/pull/18910

2021-07-05 13:05 UTC, closed without merging