Add document describing changes done during the merge
hazelcast/hazelcast pull request #18773
Opened 2021-05-25 11:06 UTC by frant-hartm

2021-05-25 11:23 UTC, gurbuzali approved these changes
looks good, maybe we can add bootstrap/cli related changes too

2021-05-25 11:42 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/5213/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/5213/Hazelcast-pr-builder-5213.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   IndexStatsChangingNumberOfMembersTest.testIndexStatsQueryingChangingNumberOfMembers:139->awaitStable:431->HazelcastTestSupport.assertTrueEventually:1350->HazelcastTestSupport.assertTrueEventually:1248->lambda$awaitStable$0:443 MemberPartitions={size=90, partitions=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 85, 87, 88, 89, 90, 92, 93]}, IndexImpl{partitionTracker=GlobalIndexPartitionTracker{partitionCount=271, state=State{stamp=526, indexedPartitions={size=87, partitions=[0, 1, 2, 3, 4, 6, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 85, 87, 88, 89, 90, 92, 93]}, pending=0}}} AbstractIndex{config=IndexConfig{name=this, type=HASH, attributes=[this]}}. Actual: -1
[ERROR] Errors: 
[ERROR]   HazelcastBootstrapTest.bootstrappedInstance:47 ? HazelcastInstanceNotActive Ha...
[INFO] 
[ERROR] Tests run: 38477, Failures: 1, Errors: 1, Skipped: 998
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2021-05-27 10:10 UTC, viliam-durina requested changes
Missing pieces to describe:
- breaking changes, deprecations
- what happened to CLI (if nothing, mention it)
- what happened to config files

2021-05-27 10:10 UTC, viliam-durina commented on docs/design/merge/01-merge-changes.md
> +referencing the streaming engine part of the product - the Jet engine.
```suggestion
referring to the streaming engine part of the product - the Jet engine.
```

2021-05-27 10:10 UTC, viliam-durina commented on docs/design/merge/01-merge-changes.md
> +- Jet datastructures created by com.hazelcast.jet.impl.JobRepository are
```suggestion
- Jet data structures created by com.hazelcast.jet.impl.JobRepository are
```

2021-05-27 10:10 UTC, viliam-durina commented on docs/design/merge/01-merge-changes.md
> +
```suggestion
  place, ideally we should apply it to the whole product
```

2021-05-27 10:10 UTC, viliam-durina commented on docs/design/merge/01-merge-changes.md
> +  `com.hazelcast.jet.config.InstanceConfig#setCooperativeThreadCount` to 2
Add:
```
- Jet cooperative threads are suspended if no jobs are running.
- One can disable Jet code upload for security reasons.
```

2021-06-02 13:22 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/5348/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/5348/Hazelcast-pr-builder-5348.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   StreamKafkaPTest.when_partitionAddedWhileJobDown_then_consumedFromBeginning:397->HazelcastTestSupport.assertTrueEventually:1350->HazelcastTestSupport.assertTrueEventually:1248->lambda$when_partitionAddedWhileJobDown_then_consumedFromBeginning$8:397 expected:<0=82f43262-3a10-4a42-aad4-390d64f7d3f5> but was:<0=0>
[INFO] 
[ERROR] Tests run: 30, Failures: 1, Errors: 0, Skipped: 1
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2021-06-04 04:47 UTC, jbartok approved these changes

2021-09-22 12:05 UTC, viliam-durina approved these changes

2021-09-22 12:22 UTC, merged