Support IMap SQL INSERTs
hazelcast/hazelcast pull request #18940
Opened 2021-06-21 07:04 UTC by gierlachg

2021-06-21 07:09 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/5662/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/5662/Hazelcast-pr-builder-5662.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.1:checkstyle (default) on project hazelcast-sql: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There are 2 errors reported by Checkstyle 8.38 with /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/checkstyle/checkstyle.xml ruleset. -> [Help 1]
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/LogicalTableInsert.java:1: Line does not match expected header line of '/*'. [Header]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/LogicalTableSink.java:1: Line does not match expected header line of '/*'. [Header]
--------------------------
</pre>
</details>

2021-06-24 10:16 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/5760/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/5760/Hazelcast-pr-builder-5760.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.1:checkstyle (default) on project hazelcast-sql: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There are 8 errors reported by Checkstyle 8.38 with /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/checkstyle/checkstyle.xml ruleset. -> [Help 1]
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/LogicalTableInsert.java:2: Line does not match expected header line of ' * Copyright 2021 Hazelcast Inc.'. [Header]
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/LogicalTableSink.java:2: Line does not match expected header line of ' * Copyright 2021 Hazelcast Inc.'. [Header]
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/opt/logical/SinkLogicalRule.java:2: Line does not match expected header line of ' * Copyright 2021 Hazelcast Inc.'. [Header]
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/opt/logical/SinkLogicalRel.java:2: Line does not match expected header line of ' * Copyright 2021 Hazelcast Inc.'. [Header]
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/opt/physical/SinkPhysicalRel.java:2: Line does not match expected header line of ' * Copyright 2021 Hazelcast Inc.'. [Header]
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/opt/physical/SinkPhysicalRule.java:2: Line does not match expected header line of ' * Copyright 2021 Hazelcast Inc.'. [Header]
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/map/InsertProcessorSupplier.java:2: Line does not match expected header line of ' * Copyright 2021 Hazelcast Inc.'. [Header]
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast-sql/src/test/java/com/hazelcast/jet/sql/impl/connector/map/InsertProcessorTest.java:2: Line does not match expected header line of ' * Copyright 2021 Hazelcast Inc.'. [Header]
--------------------------
</pre>
</details>

2021-06-28 08:18 UTC, viliam-durina requested changes

2021-06-28 09:38 UTC, gierlachg commented on hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/map/InsertProcessorSupplier.java
> +    }
If I understand correctly that would require using `ProcessorSupplier.of()`. However, we don't support `IdentifiedDataSerializable` inside lambdas.

2021-06-28 09:41 UTC, gierlachg commented on hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/SqlConnector.java
> +        throw new UnsupportedOperationException("SINK INTO not supported for " + typeName());
What do you propose exactly? We need to configure the edge inside `IMap`s `insertProcessor()`.

2021-06-28 14:42 UTC, viliam-durina commented on hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/SqlConnector.java
> +        throw new UnsupportedOperationException("SINK INTO not supported for " + typeName());
ok, my mistake.

2021-06-28 14:42 UTC, viliam-durina commented on hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/map/InsertProcessorSupplier.java
> +    }
https://github.com/hazelcast/hazelcast/pull/18940/commits/975b01bd2fe9bec3cb12897605c3e83f9c53c482

2021-06-28 14:42 UTC, viliam-durina commented on hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/SqlConnector.java
> +        throw new UnsupportedOperationException("SINK INTO not supported for " + typeName());
ok, my mistake

2021-06-28 14:44 UTC, viliam-durina approved these changes

2021-06-28 14:44 UTC, viliam-durina commented on hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/map/InsertP.java
> +        }
What about this?
```suggestion
        tryFlushQueue();
        if (isQueueFull()) {
            return false;
        }
```
We'll make room for more requests even if the queue isn't fully flushed.

2021-06-28 14:45 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/5800/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/5800/Hazelcast-pr-builder-5800.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.1:checkstyle (default) on project hazelcast-sql: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There is 1 error reported by Checkstyle 8.38 with /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_2/checkstyle/checkstyle.xml ruleset. -> [Help 1]
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_2/hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/map/InsertP.java:2: Line does not match expected header line of ' * Copyright 2021 Hazelcast Inc.'. [Header]
--------------------------
</pre>
</details>

2021-06-28 15:00 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/5801/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/5801/Hazelcast-pr-builder-5801.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.1:checkstyle (default) on project hazelcast-sql: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There is 1 error reported by Checkstyle 8.38 with /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_2/checkstyle/checkstyle.xml ruleset. -> [Help 1]
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_2/hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/map/InsertP.java:2: Line does not match expected header line of ' * Copyright 2021 Hazelcast Inc.'. [Header]
--------------------------
</pre>
</details>

2021-06-29 08:04 UTC, merged