Don't blacklist if forcibly closed by remote host
hazelcast/hazelcast pull request #18988
Opened 2021-06-28 12:11 UTC by ramizdundar

<PR description here>

Fixes #18753

Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [x] Request reviewers if possible

2021-06-28 12:34 UTC, ramizdundar commented
This PR may have some problems with https://github.com/hazelcast/hazelcast/issues/18320. Ideally we want to have correct cause in member(8000) side. This below is remote side exception.

```
java.lang.IllegalStateException: Unsupported protocol exchange detected, expected protocol: CLIENT
	at com.hazelcast.internal.server.tcp.SingleProtocolDecoder.verifyProtocol(SingleProtocolDecoder.java:101) ~[classes/:?]
	at com.hazelcast.internal.server.tcp.SingleProtocolDecoder.onRead(SingleProtocolDecoder.java:78) ~[classes/:?]
	at com.hazelcast.internal.networking.nio.NioInboundPipeline.process(NioInboundPipeline.java:136) ~[classes/:?]
	at com.hazelcast.internal.networking.nio.NioPipeline.lambda$start$0(NioPipeline.java:127) ~[classes/:?]
	at com.hazelcast.internal.networking.nio.NioThread.processTaskQueue(NioThread.java:355) [classes/:?]
	at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:290) [classes/:?]
	at com.hazelcast.internal.networking.nio.NioThread.executeRun(NioThread.java:249) [classes/:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) [classes/:?]
```

And here below is the member side exception

```
java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:1.8.0_292]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[?:1.8.0_292]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.8.0_292]
	at sun.nio.ch.IOUtil.read(IOUtil.java:197) ~[?:1.8.0_292]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379) ~[?:1.8.0_292]
	at com.hazelcast.internal.networking.nio.NioInboundPipeline.process(NioInboundPipeline.java:114) ~[classes/:?]
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKey(NioThread.java:383) [classes/:?]
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKeys(NioThread.java:368) [classes/:?]
	at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:294) [classes/:?]
	at com.hazelcast.internal.networking.nio.NioThread.executeRun(NioThread.java:249) [classes/:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) [classes/:?]
```

Since these exceptions are thrown so early in the communication phase, I couldn't found a way to transmit the error from remote(7000) to the member(8000).

This means that we will only have IOException as a cause. Thus either this PR could be merged or this test could be removed in my opinion.

2021-06-28 12:35 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/5795/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/5795/Hazelcast-pr-builder-5795.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.1:checkstyle (default) on project hazelcast: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There is 1 error reported by Checkstyle 8.38 with /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_2/checkstyle/checkstyle.xml ruleset. -> [Help 1]
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_2/hazelcast/src/main/java/com/hazelcast/internal/server/tcp/TcpServerConnectionManagerBase.java:248:9: NPath Complexity is 308 (max allowed is 250). [NPathComplexity]
--------------------------
</pre>
</details>

2021-06-28 20:24 UTC, ramizdundar commented on hazelcast/src/main/java/com/hazelcast/internal/server/tcp/TcpServerConnectionManagerBase.java
> +    private static final String FORCIBLY_CLOSED = "An existing connection was forcibly closed by the remote host";
You are right. I originally used `!(cause instanceof IOException)` but then changed to this thought exception messages can't change. I reverted this now.

As for `SingleProtocolEncoder` I will look into this tomorrow.

2021-06-29 06:35 UTC, mmedenjak commented
@kwart sorry for the early request, I later realised not all comments were probably addressed

2021-06-29 06:39 UTC, jbartok commented
@ramizdundar I also think that what @kwart suggested, sending a few bytes saying "wrong protocol" before closing the connection, would be the right fix. This thing with checking the exception is a bit of a hack and also too generic. If the "wrong protocol" feedback would be there, then the `hadNoDataTraffic` flag would take care of the problem. That flag has been introduced to fix very similar problems happening during SSL authentication.

2021-06-29 06:40 UTC, jbartok commented
One more thing, whatever fix you decide on, pls. make sure that https://github.com/hazelcast/hazelcast/pull/18591 also passes with the same fix (ie. put it there too and try).

2021-07-19 15:50 UTC, kwart requested changes
Setting to "request change" to avoid listing it in my daily review notifications :)
Please request re-review once it's improved.

2021-08-09 08:34 UTC, ramizdundar commented
> As I understand the behavior after applying the #18673, the current one is "expected". The problem is that the server-side of a connection doesn't reply when protocol selection goes wrong and just closes the connection.
> @jbartok could you confirm?
> 
> I think we could try to introduce some "alert mechanism". I.e. before closing the connection we would send few bytes saying "wrong protocol".
> 
> When the advanced networking is used we have the `SingleProtocolDecoder` which verifies if the incoming connection sends the correct protocol header (e.g. `HZC` for the member protocol or `CB2` for the client).
> If it detects a failure, the exception is thrown and the connection is closed.
> 
> We could provide a `SingleProtocolDecoder`'s counterpart - the `SingleProtocolEncoder` with a sole purpose. When the incoming connection sends an incorrect header (detected in the decoder) then the encoder would send the "wrong protocol" reply (e.g. bytes `HZX`).
> 
> If the protocol bytes verification passes in the decoder, then both decoder and encoder would be removed from the pipelines (see `SingleProtocolDecoder.setupNextDecoder()` method).

As far as I understand, this solution would be problematic when we thought the connection between older and newer members. At this early in the communication members wont each others versions. So a new member will have to send a few bytes no matter what, even if the reciever doesn't expect it. To be more exact:

- we start 5.0 member
- we start 4.2 member and misconfigure to connect it to the 5.0's client port
- 5.0 will recieve the message and will correctly identfy the problem
- then 5.0 will send wrong protocol reply
- 4.2 however doesn't have such protocol or doesn't expect answer

So I still don't know what will happen when a member gets a message it doesn't expect or decipher. However at the best case it should throw few exceptions. So do I miss something or is there a workaround for this case?

cc @kwart

2021-08-09 10:23 UTC, kwart commented
I think the described scenario is OK. If the 4.2 member has a wrong configuration, then it can't expect anything from the response. It's the same as pointing Hazelcast config to an SSH port or a REST application or a Redis port ;)

2021-08-18 14:19 UTC, ramizdundar commented
Follow #19304. Closed.

2021-08-18 14:19 UTC, closed without merging