Optimize IMap VALUES INSERTs
hazelcast/hazelcast pull request #19028
Opened 2021-07-08 12:15 UTC by gierlachg

2021-07-08 12:55 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/5982/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/5982/Hazelcast-pr-builder-5982.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   SqlRollingUpgradeTest.when_clientSql_then_usesEitherVersion:69->HazelcastTestSupport.assertTrueEventually:1362->HazelcastTestSupport.assertTrueEventually:1260->lambda$when_clientSql_then_usesEitherVersion$2:70 expected:<1> but was:<0>
[INFO] 
[ERROR] Tests run: 1021, Failures: 1, Errors: 0, Skipped: 9
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2021-07-08 12:56 UTC, gierlachg commented
run-lab-run

2021-07-09 13:24 UTC, ivanthescientist approved these changes

2021-07-12 14:00 UTC, viliam-durina requested changes

2021-07-12 14:00 UTC, viliam-durina commented on hazelcast-sql/src/test/java/com/hazelcast/jet/sql/impl/connector/map/SqlPrimitiveTest.java
> +    @Test
This test added to this class fails:
```java
    @Test
    public void test() {
        String name = randomName();
        sqlService.execute(javaSerializableMapDdl(name, String.class, String.class));

        assertEquals(1, sqlService.execute("INSERT INTO " + name + " SELECT * FROM (VALUES ('1', '1')) AS t(a, b) WHERE a='0'").updateCount());
    }
```

2021-07-13 10:45 UTC, viliam-durina approved these changes

2021-07-13 11:23 UTC, gierlachg commented
run-lab-run

2021-07-13 12:02 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/6118/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/6118/Hazelcast-pr-builder-6118.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   RetryUtilsTest.retryRetriesWaitExponentialBackoff:108
[INFO] 
[ERROR] Tests run: 4378, Failures: 1, Errors: 0, Skipped: 21
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2021-07-13 12:03 UTC, gierlachg commented
run-lab-run

2021-07-13 12:47 UTC, merged