fix npe
hazelcast/hazelcast pull request #19055
Opened 2021-07-12 15:56 UTC by ahmetmircik

closes https://github.com/hazelcast/hazelcast/issues/19044

2021-07-12 16:00 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/6083/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/6083/Hazelcast-pr-builder-6083.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:license-maven-plugin:2.0.0:add-third-party (add-third-party) on project hazelcast-jet-elasticsearch-6: could not init goal AddThirdPartyMojo for reason : null: ConcurrentModificationException -> [Help 1]
--------------------------
</pre>
</details>

2021-07-12 16:07 UTC, ahmetmircik commented
run-lab-run

2021-07-12 16:48 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/6085/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/6085/Hazelcast-pr-builder-6085.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   JobLifecycleMetricsTest.executionRelatedMetrics:162 startTime=1626106689618, completionTime=1626106689615
[INFO] 
[ERROR] Tests run: 42432, Failures: 1, Errors: 0, Skipped: 1017
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2021-07-12 19:01 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/6095/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/6095/Hazelcast-pr-builder-6095.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:license-maven-plugin:2.0.0:add-third-party (add-third-party) on project hazelcast-jet-hadoop-core: could not init goal AddThirdPartyMojo for reason : null: ConcurrentModificationException -> [Help 1]
--------------------------
</pre>
</details>

2021-07-13 07:01 UTC, mdumandag approved these changes

2021-07-22 12:07 UTC, frant-hartm requested changes
Could we give the PR (and then commit) a more descriptive name?

2021-07-27 07:37 UTC, ahmetmircik commented
@frant-hartm done.

2021-07-28 07:26 UTC, frant-hartm approved these changes

2021-07-28 07:28 UTC, merged