Merge JetProperties into ClusterProperty
hazelcast/hazelcast pull request #19146
Opened 2021-07-20 16:41 UTC by ivanthescientist

Possible implementation, not sure about the location for the merged properties though. 

Closes #19062

2021-07-22 13:12 UTC, viliam-durina approved these changes

2021-07-22 13:12 UTC, viliam-durina commented on hazelcast/src/main/java/com/hazelcast/spi/properties/ClusterProperty.java
> +    /*
This needs to be updated too: https://github.com/hazelcast/hazelcast/blob/26e776194b3f6db57aed59510ecd397158585e5c/site/docs/operations/configuration.md?plain=1#L186

2021-07-22 13:12 UTC, viliam-durina commented on extensions/hazelcast-3-connector/hazelcast-3-connector-common/src/main/java/com/hazelcast/connector/Hz3Enrichment.java
> + * {@link com.hazelcast.spi.properties.ClusterProperty#PROCESSOR_CUSTOM_LIB_DIR}
Do this and add the import, IDE doesn't do it by default, but it's valid:
```suggestion
 * {@link ClusterProperty#PROCESSOR_CUSTOM_LIB_DIR}
```

2021-07-22 13:14 UTC, viliam-durina commented on hazelcast/src/main/java/com/hazelcast/spi/properties/ClusterProperty.java
> +    /*
Probably no need to: https://github.com/hazelcast/hazelcast/pull/19036

2021-08-03 06:38 UTC, Fly-Style approved these changes
LGTM!

2021-08-03 06:50 UTC, frant-hartm requested changes

2021-08-03 06:50 UTC, frant-hartm commented on hazelcast/src/main/java/com/hazelcast/spi/properties/ClusterProperty.java
> +            = new HazelcastProperty("jet.job.scan.period", SECONDS.toMillis(5), MILLISECONDS);
The issue mentions the rest of the properties is prefixed with `hazelcast.`.

We should prefix all these, e.g. `hazelcast.jet.job.scan.period`- to keep it consistent and provide the original non-prefixed key as deprecated name, see `com.hazelcast.spi.properties.HazelcastProperty#setDeprecatedName`.

2021-08-03 06:56 UTC, frant-hartm requested changes

2021-08-03 06:56 UTC, frant-hartm commented on hazelcast/src/main/java/com/hazelcast/jet/impl/JobExecutionService.java
> +        String customLibDir = nodeEngine.getConfig().getProperty(ClusterProperty.PROCESSOR_CUSTOM_LIB_DIR.getName());
This should actually be 
```suggestion
        String customLibDir = nodeEngine.getProperties().getString(ClusterProperty.PROCESSOR_CUSTOM_LIB_DIR);
```

2021-08-03 13:41 UTC, frant-hartm approved these changes

2021-08-03 13:41 UTC, frant-hartm commented on hazelcast/src/main/java/com/hazelcast/spi/properties/ClusterProperty.java
> +            .setDeprecatedName("jet.custom.lib.dir");
We actually don't need this one because the property is new in 5.0.

2021-08-03 18:08 UTC, ahmetmircik approved these changes

2021-08-04 07:39 UTC, merged