Fix race with Jet activation
hazelcast/hazelcast pull request #19184
Opened 2021-07-26 16:50 UTC by viliam-durina

Fixes #19183

2021-07-27 08:03 UTC, ufukyilmaz commented on hazelcast/src/main/java/com/hazelcast/instance/impl/JetExtension.java
>              logger.info("Jet is enabled");
I think we should move this "Jet is enabled" log into `tryActivate`'s activation block.

2021-07-27 09:37 UTC, ufukyilmaz approved these changes
It looks good to me.

2021-07-27 09:41 UTC, ufukyilmaz commented on hazelcast/src/main/java/com/hazelcast/instance/impl/JetExtension.java
>              logger.info("Jet is enabled after the cluster version upgrade.");
But, this log can be missed when jet is activated after the cluster version upgrade and this activation is performed on another place such as on getJet.

2021-07-27 09:47 UTC, ufukyilmaz requested changes
Because the `Jet is enabled after the cluster version upgrade.` log printed in `onClusterVersionChange` may be lost, I wanted to revert my approval

2021-07-28 09:42 UTC, ufukyilmaz approved these changes
LGTM

2021-07-28 12:35 UTC, gurbuzali approved these changes

2021-07-28 12:47 UTC, merged