Secure missing file reader fn
hazelcast/hazelcast pull request #19249
Opened 2021-08-02 14:19 UTC by gurbuzali

Checklist:
- [ ] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [ ] Add `Add to Release Notes` label if changes should be mentioned in release notes or `Not Release Notes content` if changes are not relevant for release notes
- [ ] Request reviewers if possible
- [ ] New public APIs have `@Nonnull/@Nullable` annotations
- [ ] New public APIs have `@since` tags in Javadoc
- [ ] Send backports/forwardports if fix needs to be applied to past/future releases

2021-08-02 15:02 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/6459/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/6459/Hazelcast-pr-builder-6459.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   JobRepositoryTest.test_maxNumberOfJobResults:201 expected:<2> but was:<3>
[INFO] 
[ERROR] Tests run: 42927, Failures: 1, Errors: 0, Skipped: 1017
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2021-08-03 07:49 UTC, frant-hartm requested changes

2021-08-03 07:49 UTC, frant-hartm commented on hazelcast/src/main/java/com/hazelcast/jet/pipeline/FileSourceBuilder.java
> +                        SecuredFunctions.readFileFn(directory, charsetName, mapOutputFn)));
Should we use a secured function also at these places?

https://github.com/hazelcast/hazelcast/pull/19249/files#diff-e87a79dc7bb0a897688b56a68c03c8f3fa48a3f0d757bff72dadbfc647f36605L171

https://github.com/hazelcast/hazelcast/pull/19249/files#diff-e87a79dc7bb0a897688b56a68c03c8f3fa48a3f0d757bff72dadbfc647f36605L237

2021-08-03 07:49 UTC, frant-hartm commented on hazelcast/src/main/java/com/hazelcast/jet/pipeline/FileSourceBuilder.java
> +                        SecuredFunctions.readFileFn(directory, charsetName, mapOutputFn)));
And here

https://github.com/hazelcast/hazelcast/blob/master/extensions/avro/src/main/java/com/hazelcast/jet/avro/AvroSourceBuilder.java#L105

2021-08-04 07:47 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/6491/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/6491/Hazelcast-pr-builder-6491.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] COMPILATION ERROR : 
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_2/extensions/avro/src/main/java/com/hazelcast/jet/avro/AvroProcessors.java:[68,38] error: incompatible types: cannot infer type-variable(s) T#1,CAP#1,CAP#2,D#1,T#2
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5.1:compile (default-compile) on project hazelcast-jet-avro: Compilation failure
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_2/extensions/avro/src/main/java/com/hazelcast/jet/avro/AvroProcessors.java:[68,38] error: incompatible types: cannot infer type-variable(s) T#1,CAP#1,CAP#2,D#1,T#2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_2/extensions/avro/src/main/java/com/hazelcast/jet/avro/AvroProcessors.java:[68,38] error: incompatible types: cannot infer type-variable(s) T#1,CAP#1,CAP#2,D#1,T#2
--------------------------
</pre>
</details>

2021-08-04 07:58 UTC, frant-hartm approved these changes

2021-08-04 12:16 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/6502/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/6502/Hazelcast-pr-builder-6502.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   JobLifecycleMetricsTest.multipleJobsSubmittedAndCompleted:95->HazelcastTestSupport.assertTrueEventually:1364->HazelcastTestSupport.assertTrueEventually:1262->lambda$multipleJobsSubmittedAndCompleted$1:95->assertJobStats:180->assertJobStatsOnMember:190 expected:<2> but was:<3>
[INFO] 
[ERROR] Tests run: 42993, Failures: 1, Errors: 0, Skipped: 1017
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2021-08-04 13:11 UTC, gurbuzali commented
run-lab-run

2021-08-04 21:14 UTC, merged