Fix SQL SUM types
hazelcast/hazelcast pull request #19310
Opened 2021-08-12 06:26 UTC by gierlachg

Unified `HazelcastSumAggFunction` & `HazelcastTypeSystem` SUM return type derivation.

2021-08-12 07:02 UTC, hakanmemisoglu commented on hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/aggregate/function/HazelcastSumAggFunction.java
> +            case BIGINT:
Isn't the previous version safer than new one?

2021-08-12 07:03 UTC, hakanmemisoglu approved these changes
LGTM, just minor question.

2021-08-12 08:08 UTC, viliam-durina commented on hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/aggregate/function/HazelcastSumAggFunction.java
> -            case BIGINT:
It's done the wrong way. SUM(BIGINT) should result to DECIMAL, as in PG.

2021-08-12 08:09 UTC, viliam-durina requested changes

2021-08-12 08:09 UTC, viliam-durina commented on hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/aggregate/function/HazelcastSumAggFunction.java
> -            case BIGINT:
It's done the wrong way. SUM(BIGINT) should result to DECIMAL, as in PG.

2021-08-12 10:16 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/6644/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/6644/Hazelcast-pr-builder-6644.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   HazelcastTypeSystemTest.deriveSumTypeTest:109 expected:<BIGINT> but was:<DECIMAL(38, 38)>
[INFO] 
[ERROR] Tests run: 2903, Failures: 1, Errors: 0, Skipped: 50
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2021-08-23 21:17 UTC, viliam-durina approved these changes

2021-08-24 07:07 UTC, merged