Improve javadoc for Hazelcast 3 connector
hazelcast/hazelcast pull request #19443
Opened 2021-09-02 07:42 UTC by frant-hartm

Add top level javadoc for source and sink
Mark as beta

HZ-373

2021-09-09 08:04 UTC, Serdaro approved these changes
A minor comment. Other than that, LGTM.

2021-09-09 08:04 UTC, Serdaro commented on extensions/hazelcast-3-connector/hazelcast-3-connector-common/src/main/java/com/hazelcast/connector/Hz3Enrichment.java
> + * This class provides a utility methods to create and use this service factory.
... provides utility methods ...

2021-09-09 10:41 UTC, ufukyilmaz approved these changes
LGTM

2021-09-09 10:41 UTC, ufukyilmaz commented on extensions/hazelcast-3-connector/hazelcast-3-connector-common/src/main/java/com/hazelcast/connector/Hz3Sinks.java
> +@Beta
Beta annotation can also be added to the methods of this class.

2021-09-09 10:41 UTC, ufukyilmaz commented on extensions/hazelcast-3-connector/hazelcast-3-connector-common/src/main/java/com/hazelcast/connector/Hz3Sinks.java
> + * to 3.x schema.
Here, maybe we can direct the user to: https://www.hazelcast.com/schema/config/. It's entirely up to you, mine is just as a optional suggestion (if added here it should be added to Hz3Sources as well).

2021-09-09 10:48 UTC, ufukyilmaz requested changes
it might be good to have a reference to the Hazelcast schema repository from the related javadocs

2021-09-09 14:56 UTC, ufukyilmaz commented on extensions/hazelcast-3-connector/hazelcast-3-connector-common/src/main/java/com/hazelcast/connector/Hz3Sources.java
> + * config.addCustomClasspaths(mapStage.name(), jars)
minor `mapStage.name()` -> `source.name()`

2021-09-09 14:57 UTC, ufukyilmaz commented on extensions/hazelcast-3-connector/hazelcast-3-connector-common/src/main/java/com/hazelcast/connector/Hz3Enrichment.java
> + * config.addCustomClasspaths(source.name(), jars);
minor: `source.name()` -> `mapStage.name()`

2021-09-10 11:09 UTC, ufukyilmaz approved these changes

2021-09-10 12:29 UTC, merged