[HZ-736] added module checker step before node start
hazelcast/hazelcast pull request #19971
Opened 2021-11-22 14:08 UTC by ivanthescientist

Introduces centralized Module integrity checker component, based on reflection. If the produced binary does not comply with any of the included module's (e.g. HZ-SQL) requirements (e.g. requirement for `META-INF/service/` files to be merged correctly during build with `assembly-plugin` or any other plugins that provide similar functionality). 

Prototype solution at the moment. 

Possible fix for #19926.

2021-11-22 14:45 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/8333/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/8333/Hazelcast-pr-builder-8333.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ClientMapPartitionLostListenerTest.test_mapPartitionLostListener_invoked_fromOtherNode:133->assertProxyExistsEventually:163->HazelcastTestSupport.assertTrueEventually:1362->HazelcastTestSupport.assertTrueEventually:1260 There is no proxy with name df8c9ff3-0645-4a8e-99fd-efb4020c8d57 created (yet)
[INFO] 
[ERROR] Tests run: 46531, Failures: 1, Errors: 0, Skipped: 1012
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2021-11-23 09:18 UTC, ivanthescientist commented
run-lab-run

2021-12-21 08:17 UTC, mmedenjak commented
@ivanthescientist @frant-hartm can you check if this needs to go into 5.1? Currently it has no milestone so it's going nowhere.

2022-01-03 14:02 UTC, frant-hartm commented
Thanks for looking into this and sorry for taking so long to review.

The solution seems to be unnecessarily complicated to me. What it does is the following:

- during build time scan all modules for `com.hazelcast.DataSerializerHook` service definitions (this duplicates the scanning in ServiceLoader) and put this into a yaml file
- during startup it tries to load each of these hooks
- then the `com.hazelcast.internal.serialization.impl.DataSerializableSerializer` loads the hook again and creates the factories from it

This only solves the problem for the hooks in OS repo, not for EE repo (we could fix this) and neither for customer's hooks (I don't think we can fix this with this approach).

This also currently works only for `DataSerializerHook`, I suppose this is fixable for other interfaces as well, but we would need to remember to add the build step and runtime check for each.

I wonder if we could come up with a simpler solution in `com.hazelcast.internal.util.ServiceLoader` where we would check all implementations of the interface and warn about any mismatch of what is in the service definition and what we find on CP (using ClassGraph scanner, which we already have as a dependency).

2022-01-03 14:10 UTC, frant-hartm commented
@mmedenjak The issue #19926 is a user error, caused when creating a fat jar with `hazelcast` and `hazelcast-sql`. There is an easy workaround, but it's nontrivial to find out, so a fix for this issue is a big usability improvement.

2022-01-12 08:47 UTC, ldziedziul reviewed
I agree with @frant-hartm that it could be simplified, e.g. by dropping generation of the yaml file and using classpath scanning in runtime?

2022-01-13 15:45 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/9160/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/9160/Hazelcast-pr-builder-9160.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 23.651 s <<< FAILURE! - in com.hazelcast.spring.cache.TestCacheManager
--------------------------
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   SessionlessSemaphoreClientBasicTest>AbstractSessionlessSemaphoreBasicTest.setup:49->createInstances:47->SessionlessSemaphoreBasicTest.createInstances:37->HazelcastRaftTestSupport.newInstances:99->HazelcastRaftTestSupport.newInstances:118->HazelcastRaftTestSupport.waitUntilCPDiscoveryCompleted:91->HazelcastTestSupport.assertTrueEventually:1323->HazelcastTestSupport.assertTrueEventually:1221->HazelcastRaftTestSupport.lambda$waitUntilCPDiscoveryCompleted$1:93
[ERROR]   ClientDynamicConfigurationAwareConfigTest>DynamicConfigurationAwareConfigTest.testDecorateAllPublicMethodsFromTest:61 Method public boolean com.hazelcast.config.Config.isIntegrityCheckerEnabled() is declared by class com.hazelcast.config.Config whilst it should be declared by class com.hazelcast.client.impl.clientside.ClientDynamicClusterConfig
[ERROR] Errors: 
[ERROR]   ClientRegressionWithMockNetworkTest.testClientShutdown_shouldNotWaitForNextConnectionAttempt:837 ? TestTimedOut
[ERROR]   ClientCacheNearCacheBasicTest>AbstractNearCacheBasicTest.whenDeleteAsyncIsUsed_thenNearCacheShouldBeInvalidated_onDataAdapter:1166->AbstractNearCacheBasicTest.whenEntryIsRemoved_thenNearCacheShouldBeInvalidated:1250->AbstractNearCacheBasicTest.createContext:152->createContext:116 ? Hazelcast
[ERROR]   ClientCacheNearCacheBasicTest>AbstractNearCacheBasicTest.whenDeleteIsUsed_thenNearCacheShouldBeInvalidated_onNearCacheAdapter:1142->AbstractNearCacheBasicTest.whenEntryIsRemoved_thenNearCacheShouldBeInvalidated:1250->AbstractNearCacheBasicTest.createContext:152->createContext:116 ? Hazelcast
[ERROR]   ClientCacheNearCacheBasicTest>AbstractNearCacheBasicTest.whenGetAsyncIsUsedOnEmptyDataStructure_thenAlwaysReturnNullFromNearCache:1520->AbstractNearCacheBasicTest.whenGetIsUsedOnEmptyDataStructure_thenAlwaysReturnNullFromNearCache:1537->AbstractNearCacheBasicTest.createContext:152->createContext:116 ? Hazelcast
[ERROR]   ClientCacheNearCacheBasicTest>AbstractNearCacheBasicTest.whenLoadAllWithListenerIsUsed_thenNearCacheIsInvalidated_onNearCacheAdapter:988->AbstractNearCacheBasicTest.whenEntryIsLoaded_thenNearCacheShouldBeInvalidated:1038->createContext:116 ? Hazelcast
[ERROR]   ClientCacheNearCacheBasicTest>AbstractNearCacheBasicTest.whenNearCacheIsFull_thenPutOnSameKeyShouldUpdateValue_onDataAdapter:1569->AbstractNearCacheBasicTest.whenNearCacheIsFull_thenPutOnSameKeyShouldUpdateValue:1581->AbstractNearCacheBasicTest.createContext:152->createContext:116 ? Hazelcast
[ERROR]   ClientCacheNearCacheBasicTest>AbstractNearCacheBasicTest.whenRemoveAsyncIsUsed_thenNearCacheShouldBeInvalidated_onDataAdapter:1118->AbstractNearCacheBasicTest.whenEntryIsRemoved_thenNearCacheShouldBeInvalidated:1250->AbstractNearCacheBasicTest.createContext:152->createContext:116 ? Hazelcast
[ERROR]   ClientCacheNearCacheBasicTest>AbstractNearCacheBasicTest.whenReplaceIsUsed_thenNearCacheShouldBeInvalidated_onNearCacheAdapter:681->AbstractNearCacheBasicTest.whenEntryIsChanged_thenNearCacheShouldBeInvalidated:834->AbstractNearCacheBasicTest.createContext:152->createContext:116 ? Hazelcast
[ERROR]   ClientCacheNearCacheBasicTest>AbstractNearCacheBasicTest.whenSetAsyncWithExpiryPolicyIsUsed_thenNearCacheShouldBeInvalidated_onNearCacheAdapter:570->AbstractNearCacheBasicTest.whenEntryIsChanged_thenNearCacheShouldBeInvalidated:834->AbstractNearCacheBasicTest.createContext:152->createContext:116 ? Hazelcast
[ERROR]   ClientCacheNearCacheBasicTest>AbstractNearCacheBasicTest.whenSetIsUsed_thenNearCacheShouldBeInvalidated_onDataAdapter:529->AbstractNearCacheBasicTest.whenEntryIsChanged_thenNearCacheShouldBeInvalidated:834->AbstractNearCacheBasicTest.createContext:152->createContext:116 ? Hazelcast
[ERROR]   AtomicLongClientBasicTest>AbstractAtomicLongBasicTest.setup:46->createInstances:47->AtomicLongBasicTest.createInstances:48->HazelcastRaftTestSupport.newInstances:114 ? Hazelcast
[ERROR]   AtomicLongClientBasicTest>AbstractAtomicLongBasicTest.setup:46->createInstances:47->AtomicLongBasicTest.createInstances:48->HazelcastRaftTestSupport.newInstances:114 ? Hazelcast
[ERROR]   AtomicLongClientBasicTest>AbstractAtomicLongBasicTest.setup:46->createInstances:47->AtomicLongBasicTest.createInstances:48->HazelcastRaftTestSupport.newInstances:114 ? Hazelcast
[ERROR]   AtomicLongClientBasicTest>AbstractAtomicLongBasicTest.setup:46->createInstances:47->AtomicLongBasicTest.createInstances:48->HazelcastRaftTestSupport.newInstances:114 ? Hazelcast
[ERROR]   AtomicLongClientBasicTest>AbstractAtomicLongBasicTest.setup:46->createInstances:47->AtomicLongBasicTest.createInstances:48->HazelcastRaftTestSupport.newInstances:114 ? Hazelcast
[ERROR]   AtomicLongClientBasicTest>AbstractAtomicLongBasicTest.setup:46->createInstances:47->AtomicLongBasicTest.createInstances:48->HazelcastRaftTestSupport.newInstances:114 ? NoClassDefFound
[ERROR]   AtomicLongClientBasicTest>AbstractAtomicLongBasicTest.setup:46->createInstances:47->AtomicLongBasicTest.createInstances:48->HazelcastRaftTestSupport.newInstances:114 ? Hazelcast
[ERROR]   AtomicLongClientBasicTest>AbstractAtomicLongBasicTest.setup:46->createInstances:47->AtomicLongBasicTest.createInstances:48->HazelcastRaftTestSupport.newInstances:114 ? Hazelcast
[ERROR]   AtomicLongClientBasicTest>AbstractAtomicLongBasicTest.setup:46->createInstances:47->AtomicLongBasicTest.createInstances:48->HazelcastRaftTestSupport.newInstances:114 ? Hazelcast
[ERROR]   AtomicLongClientBasicTest>AbstractAtomicLongBasicTest.setup:46->createInstances:47->AtomicLongBasicTest.createInstances:48->HazelcastRaftTestSupport.newInstances:114 ? Hazelcast
[ERROR]   AtomicLongClientBasicTest>AbstractAtomicLongBasicTest.setup:46->createInstances:47->AtomicLongBasicTest.createInstances:48->HazelcastRaftTestSupport.newInstances:114 ? NoClassDefFound
[ERROR]   AtomicLongClientBasicTest>AbstractAtomicLongBasicTest.setup:46->createInstances:47->AtomicLongBasicTest.createInstances:48->HazelcastRaftTestSupport.newInstances:114 ? Hazelcast
[ERROR]   AtomicLongClientBasicTest>AbstractAtomicLongBasicTest.setup:46->createInstances:47->AtomicLongBasicTest.createInstances:48->HazelcastRaftTestSupport.newInstances:114 ? Hazelcast
[ERROR]   AtomicLongClientBasicTest>AbstractAtomicLongBasicTest.setup:46->createInstances:47->AtomicLongBasicTest.createInstances:48->HazelcastRaftTestSupport.newInstances:114 ? Hazelcast
[ERROR]   AtomicLongClientBasicTest>AbstractAtomicLongBasicTest.setup:46->createInstances:47->AtomicLongBasicTest.createInstances:48->HazelcastRaftTestSupport.newInstances:114 ? Hazelcast
[ERROR]   AtomicLongClientBasicTest>AbstractAtomicLongBasicTest.setup:46->createInstances:47->AtomicLongBasicTest.createInstances:48->HazelcastRaftTestSupport.newInstances:114 ? Hazelcast
[ERROR]   AtomicLongClientBasicTest>AbstractAtomicLongBasicTest.setup:46->createInstances:47->AtomicLongBasicTest.createInstances:48->HazelcastRaftTestSupport.newInstances:114 ? Hazelcast
[ERROR]   AtomicLongClientBasicTest>AbstractAtomicLongBasicTest.setup:46->createInstances:47->AtomicLongBasicTest.createInstances:48->HazelcastRaftTestSupport.newInstances:114 ? Hazelcast
[ERROR]   AtomicLongClientBasicTest>AbstractAtomicLongBasicTest.setup:46->cr [...]

2022-01-17 09:12 UTC, ivanthescientist commented on hazelcast/src/main/java/com/hazelcast/instance/impl/DefaultNodeExtension.java
> +        ModuleIntegrityChecker.checkIntegrity();
Yes, I don't think it can cause any issues since all the hooks would be loaded anyway. But I might be wrong on that, not sure how to test this.

2022-01-17 10:40 UTC, ivanthescientist commented
To give an update on this issue, current (ClassGraph-based) solution has a major problem in that it adds roughly 1000-1200ms of overhead to each test startup (we have over 1000 places that use default constructor for which its turned on). And it has to be turned on by default specifically for Configs constructed with `new Config()` (or `new Config(instanceName)`) because that's the exact scenario this error might occur - embedded HZ instance started programmatically with config constructed most likely programmatically as well (however its possible that part of the cases would actually use modified default config file in the project).

Integrity Checker however would be completely useless for cases where integrity of HZ artifacts is guaranteed to be preserved e.g. when official distribution is used (in non-embedded way) or when embedding is used with UberJar plugins that preserve the resources (or even whole jars) correctly.  

Given all that, there are few possible ways forward: 
1. Replace calls to `new Config()` across the tests with `load()` and introduce overrides in the config files - very costly and impractical since there are 1000+ (close to 1060 last I checked) calls to this constructor alone, additionally guaranteeing that no new calls to this constructor inside of tests are introduced would be challenging. 
2. Modify default `Config` constructors to load overrides from special `hazelcast-default-config-override.properties` file - either with reflection-based or fixed logic solution - potentially very fragile and likely to cause all kinds of issues over time. 
3. Keep the Integrity Checker disabled by default and modify documentation to suggest turning it on (also modifying the error messages for Jet to suggest turning it on, since that's the most likely scenario under which it would be useful).
4. Modify error message inside of Serializer factory - https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/internal/serialization/impl/DataSerializableSerializer.java#L139 to suggest that the cause might be corrupted/absent `META-INF/services` files - not a good solution on its own since it would not warn end user about possibly critical problem with their executable. 
5. Previous manual-scan based solution is another option since its low-runtime-overhead, however I agree that it would introduce too much complexity.

2022-01-17 13:19 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/9214/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/9214/Hazelcast-pr-builder-9214.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ClientDynamicConfigurationAwareConfigTest>DynamicConfigurationAwareConfigTest.testDecorateAllPublicMethodsFromTest:61 Method public boolean com.hazelcast.config.Config.isIntegrityCheckerEnabled() is declared by class com.hazelcast.config.Config whilst it should be declared by class com.hazelcast.client.impl.clientside.ClientDynamicClusterConfig
[ERROR]   MembershipUpdateTest.parallel_member_join:137->HazelcastTestSupport.assertTrueEventually:1323->HazelcastTestSupport.assertTrueEventually:1221->lambda$parallel_member_join$1:140
[ERROR]   MembershipUpdateTest.parallel_member_join_and_removal:270->HazelcastTestSupport.assertTrueEventually:1323->HazelcastTestSupport.assertTrueEventually:1221->lambda$parallel_member_join_and_removal$7:273
[ERROR] Errors: 
[ERROR]   MembershipUpdateTest.com.hazelcast.internal.cluster.impl.MembershipUpdateTest ? IllegalState
[ERROR]   MembershipUpdateTest.connectionsToTerminatedMember_shouldBeClosed:771 ? ClassGraph
[ERROR]   MembershipUpdateTest.memberJoinsEventually_whenMemberRestartedWithSameUuid_butMasterDoesNotNoticeItsLeave:669 ? ClassGraph
[ERROR]   MembershipUpdateTest.memberListOrder_shouldBeSame_whenMemberRestartedWithSameIdentity:601 ? ClassGraph
[INFO] 
[ERROR] Tests run: 46692, Failures: 3, Errors: 4, Skipped: 1015
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2022-01-19 12:15 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/9281/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/9281/Hazelcast-pr-builder-9281.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ClientMapPartitionLostListenerTest.test_mapPartitionLostListener_invoked_fromOtherNode:133->assertProxyExistsEventually:163->HazelcastTestSupport.assertTrueEventually:1323->HazelcastTestSupport.assertTrueEventually:1221 There is no proxy with name af01144b-16c7-4e74-bec1-c80211a289fa created (yet)
[INFO] 
[ERROR] Tests run: 46698, Failures: 1, Errors: 0, Skipped: 1015
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2022-01-19 12:37 UTC, ivanthescientist commented
run-lab-run

2022-01-19 12:39 UTC, ivanthescientist commented
run-lab-run

2022-01-19 12:44 UTC, frant-hartm requested changes

2022-01-19 12:44 UTC, frant-hartm commented on hazelcast/src/main/java/com/hazelcast/jet/impl/util/Util.java
> +
We could reuse this part in the other message as well.

2022-01-19 12:44 UTC, frant-hartm commented on hazelcast/src/main/resources/hazelcast-full-example.yaml
> +    enabled: false
Missing empty line at the end of the file.

2022-01-21 12:11 UTC, ivanthescientist commented on hazelcast/pom.xml
> +            <scope>compile</scope>
That was only needed for the previous solution (manual build-time scan one), surprisingly I didn't find a way to include a build-time dependency only. Either way its removed now.

2022-01-21 12:38 UTC, frant-hartm approved these changes
I really like how this turned out, thanks for the patience :-)

2022-01-21 12:38 UTC, frant-hartm commented on hazelcast/src/main/java/com/hazelcast/config/IntegrityCheckerConfig.java
> +     *
nit: we can remove this empty line, also in the javadoc of the method below

2022-01-21 14:30 UTC, mdumandag reviewed
LGTM from the client's perspective.

Just a question: Should we add this to https://github.com/hazelcast/hazelcast/wiki/Checklist-for-Hazelcast-config-changes#hazelcast-spring-config as well?

2022-01-24 11:21 UTC, ldziedziul commented on hazelcast-spring/src/main/resources/hazelcast-spring-5.1.xsd
> +        <xs:attribute name="enabled" type="xs:boolean" default="false">
Could you use `parameterized-boolean` to support spring property placeholders?

```suggestion
        <xs:attribute name="enabled" type="parameterized-boolean" default="false">
```

2022-01-24 11:48 UTC, ldziedziul approved these changes

2022-01-24 12:18 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/9398/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/9398/Hazelcast-pr-builder-9398.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   SqlIndexResolutionTest.testIndexResolution:106->checkIndexResolution:128->checkIndex:211 expected:<[QueryDataType {family=BOOLEAN}]> but was:<[]>
[ERROR]   SqlIndexResolutionTest.testIndexResolution:106->checkIndexResolution:128->checkIndex:211 expected:<[QueryDataType {family=BOOLEAN}]> but was:<[]>
[ERROR]   SqlIndexResolutionTest.testIndexResolution:106->checkIndexResolution:128->checkIndex:211 expected:<[QueryDataType {family=BOOLEAN}]> but was:<[]>
[ERROR]   SqlIndexResolutionTest.testIndexResolution:106->checkIndexResolution:128->checkIndex:211 expected:<[QueryDataType {family=BOOLEAN}]> but was:<[]>
[INFO] 
[ERROR] Tests run: 4713, Failures: 4, Errors: 0, Skipped: 8
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2022-01-24 13:35 UTC, ivanthescientist commented
run-lab-run

2022-01-24 13:49 UTC, ivanthescientist commented
run-lab-run

2022-01-24 14:24 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/9413/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/9413/Hazelcast-pr-builder-9413.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   SqlIndexResolutionTest.testIndexResolution:106->checkIndexResolution:128->checkIndex:211 expected:<[QueryDataType {family=BOOLEAN}]> but was:<[]>
[ERROR]   SqlIndexResolutionTest.testIndexResolution:106->checkIndexResolution:128->checkIndex:211 expected:<[QueryDataType {family=BOOLEAN}]> but was:<[]>
[ERROR]   SqlIndexResolutionTest.testIndexResolution:106->checkIndexResolution:128->checkIndex:211 expected:<[QueryDataType {family=BOOLEAN}]> but was:<[]>
[ERROR]   SqlIndexResolutionTest.testIndexResolution:106->checkIndexResolution:128->checkIndex:211 expected:<[QueryDataType {family=BOOLEAN}]> but was:<[]>
[INFO] 
[ERROR] Tests run: 4713, Failures: 4, Errors: 0, Skipped: 8
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2022-01-24 14:45 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/9414/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/9414/Hazelcast-pr-builder-9414.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   SqlIndexResolutionTest.testIndexResolution:106->checkIndexResolution:128->checkIndex:211 expected:<[QueryDataType {family=BOOLEAN}]> but was:<[]>
[ERROR]   SqlIndexResolutionTest.testIndexResolution:106->checkIndexResolution:128->checkIndex:211 expected:<[QueryDataType {family=BOOLEAN}]> but was:<[]>
[ERROR]   SqlIndexResolutionTest.testIndexResolution:106->checkIndexResolution:128->checkIndex:211 expected:<[QueryDataType {family=BOOLEAN}]> but was:<[]>
[ERROR]   SqlIndexResolutionTest.testIndexResolution:106->checkIndexResolution:128->checkIndex:211 expected:<[QueryDataType {family=BOOLEAN}]> but was:<[]>
[INFO] 
[ERROR] Tests run: 4713, Failures: 4, Errors: 0, Skipped: 8
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2022-01-25 08:43 UTC, mdumandag approved these changes

2022-01-25 10:33 UTC, merged