Forbid view replacement with non-equal projection
hazelcast/hazelcast pull request #20255
Opened 2021-12-21 13:16 UTC by Fly-Style

Forbid view replacement with incompatible projection to avoid additional complexity during dependent view processing.
This fix still doesn't cover replacement with DROP & CREATE VIEW, which is way more complex solution, planned for 5.2.

Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [x] Label `Add to Release Notes` or `Not Release Notes content` set
- [x] Request reviewers if possible

2021-12-21 13:57 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/8739/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/8739/Hazelcast-pr-builder-8739.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   CreateViewStatementTest.when_createsViewWithReplace_then_succeeds:85 ? HazelcastSql
[INFO] 
[ERROR] Tests run: 4661, Failures: 0, Errors: 1, Skipped: 76
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2021-12-27 07:12 UTC, viliam-durina requested changes

2021-12-27 07:12 UTC, viliam-durina commented on hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/PlanExecutor.java
> +    private static void checkProjectsCompatibility(View original, View replacement) {
It's not enough to compare types, we also must compare names. Consider:
```
create view v as 
select 42 as a, 'foo' as b;

create or replace view
select 42 as b, 'foo' as a;
```

Normally, databases allow adding more columns to views too, they don't allow removing or changing columns.

I think we can quickly fix this, even though it's just a small mitigation, not a fix.

2021-12-28 08:02 UTC, viliam-durina approved these changes

2022-01-04 14:24 UTC, ivanthescientist approved these changes

2022-01-04 16:53 UTC, merged