Remove modulepath-tests from root project modules [HZ-691]
hazelcast/hazelcast pull request #20488
Opened 2022-01-25 12:34 UTC by ldziedziul

`modulepath-tests` requires hazelcast java module which we create as an automatic one (by setting `Automatic-Module-Name` in `manifest.mf`). On JDK17 it results in the compilation error when running `mvn clean test-compile` on the root module:
```
Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
.../hazelcast/modulepath-tests/src/main/java/module-info.java:[18,27] module not found: com.hazelcast.core
```
So in order to make it work we need to build main jar file and then run the module tests.

Solution would be to remove `modulepath-tests` from child modules of the root module and run the separately (as we already do in the pr-builder job) 

Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [x] Label `Add to Release Notes` or `Not Release Notes content` set
- [x] Request reviewers if possible

2022-01-25 12:37 UTC, ldziedziul commented
run-with-jdk17

2022-01-25 13:35 UTC, ldziedziul commented
run-with-jdk17

2022-01-26 09:15 UTC, kwart commented
What's the issue with calling `mvn clean install`?
I would rather have the module included automatically for Java 9+.

2022-01-26 11:43 UTC, frant-hartm commented
We wanted to allow running `mvn compile`/`test-compile` on the project (which works with JDK 8). This is to save time locally / on the PR builder (it's a few minutes due to our large jars).

I have looked into this a bit more this simply can't be done with automatic modules, an automatic module can't be created from class files in a directory, it must be in jars. My understanding is that it is possible with own `module-info.java`.

So we have 2 choices:
- when building on JDK11+ require at least `package` phase (as everyone using automatic modules & depending on them)
- move the `modulepath-tests` module to a profile

2022-01-26 12:12 UTC, ldziedziul commented
> What's the issue with calling `mvn clean install`? I would rather have the module included automatically for Java 9+.

`clean install` works but I think that `mvn clean compile` should always work, e.g. we use `mvn clean test-compile` in CI as a preflight check before running actual tests.

As far as I can see, these tests do high-level smoke tests. From my point of view during typical development there's a fairly low risk that we break it by accident.

2022-01-31 15:43 UTC, kwart commented
> As far as I can see, these tests do high-level smoke tests. From my point of view during typical development there's a fairly low risk that we break it by accident.

They are smoke tests, but they should discover the most common problems in the setup:
* accidental automatic module name change;
* including `module-info.class` from a dependency;

We touch our POMs quite often, so to me, it's cleaner to run the modulepath tests automatically.

I have another suggestion to improve the build times. Let's keep this new separation of profiles, but activate the new profile by default and make it dependent e.g. on the existing `quick` property:
```xml
            <activation>
                <property>
                    <name>!quick</name>
                </property>
            </activation>
```

WDYT?

2022-02-01 08:35 UTC, frant-hartm commented
I am fine with that.

2022-02-08 09:08 UTC, kwart requested changes
Let's keep this new separation of profiles, but activate the new profile by default and make it dependent e.g. on the existing quick property.

2022-02-15 16:30 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/9998/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/9998/Hazelcast-pr-builder-9998.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.9.0:compile (default-compile) on project modulepath-tests: Fatal error compiling: invalid flag: --release -> [Help 1]
--------------------------
</pre>
</details>

2022-02-15 17:25 UTC, merged

2023-08-21 11:12 UTC, kwart commented
@anianna96 Try the following command:

```bash
./apache-maven-3.9.4/bin/mvn -Dmaven.repo.local=./maven_repo -DskipTests clean install
```

Do you still see the issue? (even when the `clean` is included)