Log and change license only if not equal to the old license
hazelcast/hazelcast pull request #20594
Opened 2022-02-03 09:54 UTC by ramizdundar

EE PR: INSERT_LINK_TO_THE_EE_PR_HERE

Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [x] Label `Add to Release Notes` or `Not Release Notes content` set
- [x] Request reviewers if possible

2022-02-03 10:40 UTC, vbekiaris approved these changes

2022-02-04 08:33 UTC, frant-hartm requested changes
I would move the message to EE, It's only used from there, reduces coupling between OS and EE repo.

2022-02-04 08:33 UTC, frant-hartm commented on hazelcast/src/main/java/com/hazelcast/internal/config/LicenseKey.java
> +                    + "Please create new members with the updated license.";
```suggestion
                    + "Please ensure new members use the updated license.";
```

2022-02-04 08:33 UTC, frant-hartm commented on hazelcast/src/main/java/com/hazelcast/internal/config/LicenseKey.java
> +                    + "Please create new members with the updated license.";
It is a bit ambiguous - it instructs the user to create new members.

2022-02-04 08:54 UTC, ramizdundar commented
> I would move the message to EE, It's only used from there, reduces coupling between OS and EE repo.

In respect to this message I moved the message to EE. I am closing this now.

2022-02-04 08:54 UTC, closed without merging