[HZ-789] Move streaming source detection to RelNode level
hazelcast/hazelcast pull request #20996
Opened 2022-03-16 19:13 UTC by Fly-Style

2022-03-17 08:37 UTC, krzysztofslusarski approved these changes

2022-03-17 08:37 UTC, krzysztofslusarski commented on hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/opt/physical/StreamAggregateCannotExecuteRule.java
> + * it with {@link ShouldnotExecuteRel}, which has infinity cost. If no other rule
[Minor] ```which has infinity cost``` -> ```which has huge cost```

2022-03-17 09:45 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/10455/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/10455/Hazelcast-pr-builder-10455.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] COMPILATION ERROR : 
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_3/hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/PlanExecutor.java:[272,21] no suitable constructor found for View(java.lang.String,java.lang.String,java.util.List<java.lang.String>,java.util.List<com.hazelcast.sql.impl.type.QueryDataType>)
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.0:compile (default-compile) on project hazelcast-sql: Compilation failure
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_3/hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/PlanExecutor.java:[272,21] no suitable constructor found for View(java.lang.String,java.lang.String,java.util.List<java.lang.String>,java.util.List<com.hazelcast.sql.impl.type.QueryDataType>)
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_3/hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/PlanExecutor.java:[272,21] no suitable constructor found for View(java.lang.String,java.lang.String,java.util.List<java.lang.String>,java.util.List<com.hazelcast.sql.impl.type.QueryDataType>)
--------------------------
</pre>
</details>

2022-03-17 09:55 UTC, hz-devops-test commented
The job `Hazelcast-pr-compiler` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-compiler/586/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-compiler/586/Hazelcast-pr-compiler-586.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] COMPILATION ERROR : 
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler_2/hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/PlanExecutor.java:[272,21] no suitable constructor found for View(java.lang.String,java.lang.String,java.util.List<java.lang.String>,java.util.List<com.hazelcast.sql.impl.type.QueryDataType>)
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.0:compile (default-compile) on project hazelcast-sql: Compilation failure
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler_2/hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/PlanExecutor.java:[272,21] no suitable constructor found for View(java.lang.String,java.lang.String,java.util.List<java.lang.String>,java.util.List<com.hazelcast.sql.impl.type.QueryDataType>)
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler_2/hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/PlanExecutor.java:[272,21] no suitable constructor found for View(java.lang.String,java.lang.String,java.util.List<java.lang.String>,java.util.List<com.hazelcast.sql.impl.type.QueryDataType>)
--------------------------
</pre>
</details>

2022-03-18 22:44 UTC, viliam-durina requested changes

2022-03-18 22:44 UTC, viliam-durina commented on hazelcast/src/main/java/com/hazelcast/sql/impl/schema/view/View.java
> -        out.writeBoolean(isStream);
This must be backwards compatible, the class needs to implement `Versioned` and handle old data.

2022-03-18 23:27 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/10484/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/10484/Hazelcast-pr-builder-10484.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   TestCacheManager.testBean_withTTL:87 expected:<ali> but was:<null>
[INFO] 
[ERROR] Tests run: 207, Failures: 1, Errors: 0, Skipped: 0
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2022-03-21 10:53 UTC, viliam-durina requested changes

2022-03-21 10:53 UTC, viliam-durina commented on hazelcast/src/main/java/com/hazelcast/sql/impl/schema/view/View.java
> +public class View implements IdentifiedDataSerializable, Versioned {
The `isStream` field is unused now, we should remove it from the binary format.

2022-03-22 13:02 UTC, viliam-durina approved these changes

2022-03-22 13:03 UTC, merged