Kinesis builder executor service
hazelcast/hazelcast pull request #21075
Opened 2022-03-28 14:22 UTC by anestoruk

Hello,

**Problem**:
I need a way to configure AWS Asynchronous Client's executor service used by Jet's Kinesis sources and sinks (thread pool size, threads names pattern). Currently, AWS Client will be always constructed with default `Executors.newFixedThreadPool(getClientConfiguration().getMaxConnections()); // default is 50 connections`.

**Solution**:
Extend `AwsConfig` with additional `executorServiceSupplier` field that allows to specify what executore service should be used.

**Checklist**:
- [ ] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [ ] Label `Add to Release Notes` or `Not Release Notes content` set
- [x] Request reviewers if possible
- [ ] Send backports/forwardports if fix needs to be applied to past/future releases
- [ ] New public APIs have `@Nonnull/@Nullable` annotations
- [ ] New public APIs have `@since` tags in Javadoc

2022-03-28 14:22 UTC, devOpsHazelcast commented
Can one of the admins verify this patch?

2022-03-28 14:22 UTC, devOpsHazelcast commented
Can one of the admins verify this patch?

2022-03-28 14:22 UTC, devOpsHazelcast commented
Can one of the admins verify this patch?

2022-03-28 14:22 UTC, devOpsHazelcast commented
Can one of the admins verify this patch?

2022-03-28 14:22 UTC, devOpsHazelcast commented
Can one of the admins verify this patch?

2022-03-28 14:22 UTC, devOpsHazelcast commented
Can one of the admins verify this patch?

2022-03-28 14:22 UTC, devOpsHazelcast commented
[![CLA assistant check](https://cla.hazelcast.org/pull/badge/not_signed)](https://cla.hazelcast.org/hazelcast/hazelcast?pullRequest=21075) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.hazelcast.org/hazelcast/hazelcast?pullRequest=21075) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.hazelcast.org/check/hazelcast/hazelcast?pullRequest=21075) it.</sub>

2022-03-30 09:54 UTC, vbekiaris commented
run-lab-run

2022-09-14 14:20 UTC, TomaszGaweda requested changes
LGTM, but I think some comments should be addressed before merge.

2022-09-14 14:20 UTC, TomaszGaweda commented on extensions/kinesis/src/test/java/com/hazelcast/jet/kinesis/KinesisIntegrationTest.java
> +                1, r -> new Thread(r, "kinesis-sink-thread"));
nit: lambda on new line for clarity

2022-09-14 14:20 UTC, TomaszGaweda commented on extensions/kinesis/src/test/java/com/hazelcast/jet/kinesis/KinesisIntegrationTest.java
> +        SupplierEx<ExecutorService> sourceExecutorSupplier = () -> Executors.newFixedThreadPool(
ditto: you should check that given service is used

2022-09-15 09:23 UTC, anestoruk commented
Thanks @TomaszGaweda for the review, I've made the changes as you suggested :+1:

2022-09-15 09:55 UTC, frant-hartm requested changes

2022-09-15 09:55 UTC, frant-hartm commented on extensions/kinesis/src/main/java/com/hazelcast/jet/kinesis/KinesisSinks.java
> +         */
Could you please add `@since 5.2`

2022-09-15 09:55 UTC, frant-hartm commented on extensions/kinesis/src/test/java/com/hazelcast/jet/kinesis/KinesisIntegrationTest.java
> +                                && threadCounter.get() == MEMBER_COUNT);
I think it makes more sense to move the threadCounter assert just after `sendMessages`. No need to assert it inside a job.

2022-09-15 11:50 UTC, TomaszGaweda approved these changes

2022-09-15 11:55 UTC, frant-hartm approved these changes

2022-09-15 15:56 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/13188/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/13188/Hazelcast-pr-builder-13188.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   ClientPNCounterTest.testClusterRestart ?  Unexpected exception, expected<com.h...
[INFO] 
[ERROR] Tests run: 50847, Failures: 0, Errors: 1, Skipped: 238
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2022-09-16 07:09 UTC, TomaszGaweda commented
run-lab-run

2022-09-16 08:04 UTC, merged

2022-09-16 08:04 UTC, TomaszGaweda commented
thanks for contribution @anestoruk!