Fix possible double shutdown
hazelcast/hazelcast pull request #21147
Opened 2022-04-04 15:20 UTC by viliam-durina

If `HazelcastInstance.shutdown()` is executed twice concurrently from two
threads, they can both attempt to notify the master about being shut down, but
one of the attempts will fail.

It's fixed by moving the `beforeShutdown()` call after the double-shutdown
guard.

Fixes #21123

2022-04-08 06:58 UTC, frant-hartm requested changes
The fix looks good to me, could we add a test?

2022-04-08 12:23 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/10817/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/10817/Hazelcast-pr-builder-10817.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.2:checkstyle (default) on project hazelcast: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There is 1 error reported by Checkstyle 8.38 with /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/checkstyle/checkstyle.xml ruleset. -> [Help 1]
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/test/java/com/hazelcast/instance/impl/LifecycleServiceImplTest.java:1: File does not end with a newline. [NewlineAtEndOfFile]
--------------------------
</pre>
</details>

2022-04-08 12:26 UTC, viliam-durina commented
@frant-hartm test added

2022-04-08 12:28 UTC, hz-devops-test commented
The job `Hazelcast-pr-compiler` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-compiler/936/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-compiler/936/Hazelcast-pr-compiler-936.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.2:checkstyle (default) on project hazelcast: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There is 1 error reported by Checkstyle 8.38 with /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/checkstyle/checkstyle.xml ruleset. -> [Help 1]
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/hazelcast/src/test/java/com/hazelcast/instance/impl/LifecycleServiceImplTest.java:1: File does not end with a newline. [NewlineAtEndOfFile]
--------------------------
</pre>
</details>

2022-04-08 14:21 UTC, ufukyilmaz approved these changes
It looks good to me. Thanks for the fix.

2022-04-20 13:22 UTC, frant-hartm approved these changes

2022-04-21 07:24 UTC, merged