Implement spliterator() on List and Set proxies (#21017)
hazelcast/hazelcast pull request #21250
Opened 2022-04-19 10:23 UTC by bergander

Implements spliterator() on List and Set client proxies to avoid possible IllegalStateException.

Fixes #21017

2022-04-19 10:23 UTC, devOpsHazelcast commented
Can one of the admins verify this patch?

2022-04-19 10:23 UTC, devOpsHazelcast commented
Can one of the admins verify this patch?

2022-04-19 10:23 UTC, devOpsHazelcast commented
Can one of the admins verify this patch?

2022-04-19 10:23 UTC, devOpsHazelcast commented
Can one of the admins verify this patch?

2022-04-19 10:23 UTC, devOpsHazelcast commented
Can one of the admins verify this patch?

2022-04-19 10:23 UTC, devOpsHazelcast commented
Can one of the admins verify this patch?

2022-04-19 10:23 UTC, devOpsHazelcast commented
Can one of the admins verify this patch?

2022-04-19 10:23 UTC, devOpsHazelcast commented
Can one of the admins verify this patch?

2022-04-19 10:23 UTC, devOpsHazelcast commented
Can one of the admins verify this patch?

2022-04-19 10:23 UTC, devOpsHazelcast commented
Can one of the admins verify this patch?

2022-04-19 10:23 UTC, devOpsHazelcast commented
Can one of the admins verify this patch?

2022-04-19 14:12 UTC, ihsandemir reviewed
Your implementation iterates only on snapshot of the list/set. It is not a real iterator on the distributes List/Set structure. I believe that is why the implementation throws the exception. On a dynamic changing data at the cluster, it may not be very feasible to have such an iterator, what do you think?

2022-04-26 12:14 UTC, ihsandemir requested changes
Looks good. Can you please add unit tests for coverage?

2022-04-26 12:15 UTC, ihsandemir commented
@bergander  I got the point now. OK, this is reasonable. Can you add some tests and then it looks good to me.

> @ihsandemir I'm not sure I understand what you mean. My example code fails because the client library does not provide an iterator based on a local snapshot. This is what this PR fixes. In my opinion it should work the same way as e.g. ConcurrentHashMap does which provides _weakly consistent_ Spliterators:
> 
> > Most concurrent Collection implementations (including most Queues) also differ from the usual java.util conventions in that their Iterators and Spliterators provide weakly consistent rather than fast-fail traversal:
> > 
> > * they may proceed concurrently with other operations
> > * they will never throw ConcurrentModificationException
> > * they are guaranteed to **traverse elements as they existed upon construction** exactly once, and may (but are not guaranteed to) reflect any modifications subsequent to construction.
> 
> Also, ClientSetProxy already implements `iterator()` by creating a local snapshot and calling iterator on that snapshot. My changes does the exact same thing but for `spliterator()`.

2022-04-26 12:16 UTC, ihsandemir commented
run-lab-run

2022-07-21 13:02 UTC, ihsandemir approved these changes

2022-08-26 14:36 UTC, mdumandag commented
run-lab-run

2022-08-26 15:27 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/12842/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/12842/Hazelcast-pr-builder-12842.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   QueueDestroyTest.checkStatsMapEntryRemovedWhenQueueDestroyed:78 expected:<0> but was:<1>
[INFO] 
[ERROR] Tests run: 50783, Failures: 1, Errors: 0, Skipped: 238
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2022-08-26 16:02 UTC, mdumandag commented
run-lab-run

2022-08-29 07:18 UTC, mdumandag approved these changes

2022-08-31 07:19 UTC, merged