Update schemaLocation to current version
hazelcast/hazelcast pull request #21357
Opened 2022-05-04 12:29 UTC by TomaszGaweda

Update schemaLocation to current version to avoid warning messages about wrong schema name.

Fixes #21267

Checklist:
- [ ] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [ ] Label `Add to Release Notes` or `Not Release Notes content` set
- [ ] Request reviewers if possible
- [ ] Send backports/forwardports if fix needs to be applied to past/future releases
- [ ] New public APIs have `@Nonnull/@Nullable` annotations
- [ ] New public APIs have `@since` tags in Javadoc

2022-05-04 14:09 UTC, frant-hartm requested changes

2022-05-04 14:09 UTC, frant-hartm commented on hazelcast/src/test/java/com/hazelcast/spi/discovery/DiscoverySpiTest.java
> +        URL schemaResource = DiscoverySpiTest.class.getClassLoader().getResource("hazelcast-config-5.2.xsd");
I think the version is not important here, let's remove it so we don't have to update it again with the next minor version.

2022-05-04 14:25 UTC, frant-hartm approved these changes

2022-05-04 14:28 UTC, frant-hartm commented
@ldziedziul so we should remove `Fixes #21267` from this PR then?

2022-05-04 14:29 UTC, ldziedziul commented
> @ldziedziul so we should remove `Fixes #21267` from this PR then?

Yes, please do.

2022-05-04 14:30 UTC, TomaszGaweda commented
Done

2022-05-05 10:18 UTC, mdumandag approved these changes

2022-05-05 10:25 UTC, TomaszGaweda commented
Thanks for the help with first PR as employee! :D

2022-05-05 10:26 UTC, merged