Add description to JobConfig
hazelcast/hazelcast pull request #21489
Opened 2022-05-29 18:24 UTC by Awelless

Added description to a JobConfig according to the following issue: https://github.com/hazelcast/hazelcast/issues/20510

2022-05-29 18:24 UTC, devOpsHazelcast commented
Can one of the admins verify this patch?

2022-05-29 18:24 UTC, devOpsHazelcast commented
Can one of the admins verify this patch?

2022-05-29 18:24 UTC, devOpsHazelcast commented
Can one of the admins verify this patch?

2022-05-29 18:24 UTC, devOpsHazelcast commented
Can one of the admins verify this patch?

2022-05-29 18:24 UTC, devOpsHazelcast commented
Can one of the admins verify this patch?

2022-05-29 18:24 UTC, devOpsHazelcast commented
Can one of the admins verify this patch?

2022-05-29 18:24 UTC, devOpsHazelcast commented
Can one of the admins verify this patch?

2022-05-29 18:24 UTC, devOpsHazelcast commented
Can one of the admins verify this patch?

2022-05-29 18:24 UTC, devOpsHazelcast commented
Can one of the admins verify this patch?

2022-05-29 18:24 UTC, devOpsHazelcast commented
Can one of the admins verify this patch?

2022-05-29 18:24 UTC, devOpsHazelcast commented
Can one of the admins verify this patch?

2022-05-29 18:24 UTC, devOpsHazelcast commented
[![CLA assistant check](https://cla.hazelcast.org/pull/badge/not_signed)](https://cla.hazelcast.org/hazelcast/hazelcast?pullRequest=21489) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.hazelcast.org/hazelcast/hazelcast?pullRequest=21489) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.hazelcast.org/check/hazelcast/hazelcast?pullRequest=21489) it.</sub>

2022-05-30 12:05 UTC, TomaszGaweda commented
run-lab-run

2022-05-30 14:35 UTC, viliam-durina requested changes
Unfortunately we can't do changes to binary format of `JobConfig`. The class must be backwards compatible because it's stored as a part of `JobRecord` and a cluster must be able to deserialize it after a rolling upgrade. It also can't use `Versioned`, because it's also sent in binary form from the client (see #20755). Therefore we can't do incompatible changes until the next major release.

2022-06-03 12:16 UTC, Awelless commented
@viliam-durina 
Thanks. 
This PR will be opened then. Before a merge I'll adapt it to any changes/new requirements, if needed

2022-08-11 09:23 UTC, neilstevenson commented
@awelless Is there any chance you could join our community Slack channel ? -- there's a link to do so here https://hazelcast.com/dev-community/.
We'd like to chat to you to find out if there's a way we can implement this feature somehow

2023-10-02 17:39 UTC, k-jamroz commented
This can be achieved currently by using `JobConfig.setArgument`. It's not perfect but can be used to pass some extra data about the job.

2023-10-02 20:00 UTC, neilstevenson commented
I'll add a comment to https://github.com/hazelcast/hazelcast/issues/20510 discussing the motivation.

This fix seems pretty good, perhaps the wider problem is that Jet config does not support easy extension as new fields are required

2024-04-08 12:12 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/22256/Hazelcast-pr-builder-22256.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/22256/Hazelcast-pr-builder-22256.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
---------ERRORS-----------
--------------------------
[ERROR] Error executing Maven.
--------------------------
</pre>
</details>

2024-04-08 12:42 UTC, nilnullneil commented
Being able to describe jobs using a description field remains a useful need.

2024-10-08 21:30 UTC, devOpsHazelcast commented
PR closed by Hazelcast automation as no activity (>6 months). Please reopen with comments, if necessary. Thank you for using Hazelcast and your valuable contributions

2024-10-08 21:56 UTC, nilnullneil commented
This is still valid

2025-04-09 21:32 UTC, closed without merging

2025-04-09 21:32 UTC, devOpsHazelcast commented
PR closed by Hazelcast automation as no activity (>6 months). Please reopen with comments, if necessary. Thank you for using Hazelcast and your valuable contributions