[HZ-989] Implement JSON_ARRAYAGG function
hazelcast/hazelcast pull request #21731
Opened 2022-07-04 11:19 UTC by hakanmemisoglu

Implement `JSON_ARRAYAGG` aggregation function. The function will aggregate the values into a JSON array.
Aggregation order can be defined as an argument `JSON_ARRAYAGG(... ORDER BY...)`. Null treatment can be
defined too `JSON_ARRAYAGG(... NULL ON NULL | ABSENT ON NULL ...)`.
Example, 

With the following table

```
name, no
--------
Alice, 1
Bob, 2
Alice, 3
Bob, 6
null, 7
```

This query

```
SELECT name, JSON_ARRAYAGG(no ORDER BY no DESC) arr_no GROUP BY name
```

produces the following result:

```
name, arr_no
------------
Alice, [1, 3]
Bob, [2, 6]
null, [7]
```

Checklist:
- [ ] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [ ] Label `Add to Release Notes` or `Not Release Notes content` set
- [ ] Request reviewers if possible
- [ ] Send backports/forwardports if fix needs to be applied to past/future releases
- [ ] New public APIs have `@Nonnull/@Nullable` annotations
- [ ] New public APIs have `@since` tags in Javadoc

2022-07-04 11:59 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/11816/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/11816/Hazelcast-pr-builder-11816.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   NestingAndCasingExpressionTest.testAllExpressionsCovered:113 Tests not implemented: 
test_JSON_ARRAYAGG_ABSENT_ON_NULL
test_JSON_ARRAYAGG_NULL_ON_NULL
test_WITHIN_GROUP
[INFO] 
[ERROR] Tests run: 4880, Failures: 1, Errors: 0, Skipped: 6
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2022-07-04 13:17 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/11817/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/11817/Hazelcast-pr-builder-11817.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   QueueDestroyTest.checkStatsMapEntryRemovedWhenQueueDestroyed:78 expected:<0> but was:<1>
[ERROR] Errors: 
[ERROR]   ClientSelectorRaceTest.com.hazelcast.client.bluegreen.ClientSelectorRaceTest ? IllegalState
[INFO] 
[ERROR] Tests run: 50573, Failures: 1, Errors: 1, Skipped: 238
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2022-07-05 14:37 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/11835/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/11835/Hazelcast-pr-builder-11835.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   QueueDestroyTest.checkStatsMapEntryRemovedWhenQueueDestroyed:78 expected:<0> but was:<1>
[INFO] 
[ERROR] Tests run: 50572, Failures: 1, Errors: 0, Skipped: 238
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2022-07-06 09:41 UTC, hakanmemisoglu commented
run-lab-run

2022-07-07 12:14 UTC, viliam-durina requested changes
I also pushed failing tests.

2022-07-07 16:30 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/11883/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/11883/Hazelcast-pr-builder-11883.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   JsonSqlAggregateTest.test_jsonArrayAgg_emptyResult:46->SqlTestSupport.assertRowsAnyOrder:271->SqlTestSupport.assertRowsAnyOrder:295->SqlTestSupport.assertRowsAnyOrder:319 ? HazelcastSql
[ERROR]   JsonSqlAggregateTest.test_jsonArrayAgg_nulls:56->SqlTestSupport.assertRowsAnyOrder:271->SqlTestSupport.assertRowsAnyOrder:295->SqlTestSupport.assertRowsAnyOrder:319 ? HazelcastSql
[ERROR]   JsonSqlAggregateTest.test_jsonArrayAgg_unordered:63->SqlTestSupport.assertRowsAnyOrder:271->SqlTestSupport.assertRowsAnyOrder:295->SqlTestSupport.assertRowsAnyOrder:319 ? HazelcastSql
[INFO] 
[ERROR] Tests run: 4885, Failures: 0, Errors: 3, Skipped: 6
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2022-07-12 12:52 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/11930/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/11930/Hazelcast-pr-builder-11930.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   JsonSqlAggregateTest.test_jsonArrayAgg_emptyResult:46->SqlTestSupport.assertRowsAnyOrder:271->SqlTestSupport.assertRowsAnyOrder:295->SqlTestSupport.assertRowsAnyOrder:319 ? HazelcastSql
[ERROR]   JsonSqlAggregateTest.test_jsonArrayAgg_nulls:56->SqlTestSupport.assertRowsAnyOrder:271->SqlTestSupport.assertRowsAnyOrder:295->SqlTestSupport.assertRowsAnyOrder:319 ? HazelcastSql
[ERROR]   JsonSqlAggregateTest.test_jsonArrayAgg_unordered:63->SqlTestSupport.assertRowsAnyOrder:271->SqlTestSupport.assertRowsAnyOrder:295->SqlTestSupport.assertRowsAnyOrder:319 ? HazelcastSql
[INFO] 
[ERROR] Tests run: 4885, Failures: 0, Errors: 3, Skipped: 6
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2022-07-18 09:18 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/11989/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/11989/Hazelcast-pr-builder-11989.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   JsonSqlAggregateTest.test_jsonArrayAgg_emptyResult:46->SqlTestSupport.assertRowsAnyOrder:271->SqlTestSupport.assertRowsAnyOrder:295->SqlTestSupport.assertRowsAnyOrder:319 ? HazelcastSql
[ERROR]   JsonSqlAggregateTest.test_jsonArrayAgg_nulls:56->SqlTestSupport.assertRowsAnyOrder:271->SqlTestSupport.assertRowsAnyOrder:295->SqlTestSupport.assertRowsAnyOrder:319 ? HazelcastSql
[ERROR]   JsonSqlAggregateTest.test_jsonArrayAgg_unordered:63->SqlTestSupport.assertRowsAnyOrder:271->SqlTestSupport.assertRowsAnyOrder:295->SqlTestSupport.assertRowsAnyOrder:319 ? HazelcastSql
[INFO] 
[ERROR] Tests run: 4885, Failures: 0, Errors: 3, Skipped: 6
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2022-07-18 10:55 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/11991/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/11991/Hazelcast-pr-builder-11991.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   JsonSqlAggregateTest.test_jsonArrayAgg_emptyResult:46->SqlTestSupport.assertRowsAnyOrder:271->SqlTestSupport.assertRowsAnyOrder:295->SqlTestSupport.assertRowsAnyOrder:319 ? HazelcastSql
[ERROR]   JsonSqlAggregateTest.test_jsonArrayAgg_nulls:56->SqlTestSupport.assertRowsAnyOrder:271->SqlTestSupport.assertRowsAnyOrder:295->SqlTestSupport.assertRowsAnyOrder:319 ? HazelcastSql
[ERROR]   JsonSqlAggregateTest.test_jsonArrayAgg_unordered:63->SqlTestSupport.assertRowsAnyOrder:271->SqlTestSupport.assertRowsAnyOrder:295->SqlTestSupport.assertRowsAnyOrder:319 ? HazelcastSql
[INFO] 
[ERROR] Tests run: 4885, Failures: 0, Errors: 3, Skipped: 6
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2022-07-18 11:56 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/11998/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/11998/Hazelcast-pr-builder-11998.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   JsonSqlAggregateTest.test_jsonArrayAgg_emptyResult:46->SqlTestSupport.assertRowsAnyOrder:271->SqlTestSupport.assertRowsAnyOrder:295->SqlTestSupport.assertRowsAnyOrder:319 ? HazelcastSql
[ERROR]   JsonSqlAggregateTest.test_jsonArrayAgg_nulls:56->SqlTestSupport.assertRowsAnyOrder:271->SqlTestSupport.assertRowsAnyOrder:295->SqlTestSupport.assertRowsAnyOrder:319 ? HazelcastSql
[ERROR]   JsonSqlAggregateTest.test_jsonArrayAgg_unordered:63->SqlTestSupport.assertRowsAnyOrder:271->SqlTestSupport.assertRowsAnyOrder:295->SqlTestSupport.assertRowsAnyOrder:319 ? HazelcastSql
[INFO] 
[ERROR] Tests run: 4885, Failures: 0, Errors: 3, Skipped: 6
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2022-07-25 16:53 UTC, viliam-durina approved these changes

2022-07-28 09:48 UTC, Fly-Style approved these changes
Generally, looks good to me, but if you have a time, please, take a look on [Vilo's comment](https://github.com/hazelcast/hazelcast/pull/21731/files#r929029011), it's a good enhancement

2022-07-28 09:52 UTC, merged