Fix AAIOB when using select star with natural join
hazelcast/hazelcast pull request #21832
Opened 2022-07-25 07:55 UTC by hakanmemisoglu

Permute method applied in Natural Join or Using Join
causes an exception because the method doesn't handle
our hidden fields. It is a private method and cannot
be intercepted safely, therefore a copy of SqlValidator
is put under the sources and the condition for
triggering the permute operation is removed.

Checklist:
- [ ] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [ ] Label `Add to Release Notes` or `Not Release Notes content` set
- [ ] Request reviewers if possible
- [ ] Send backports/forwardports if fix needs to be applied to past/future releases
- [ ] New public APIs have `@Nonnull/@Nullable` annotations
- [ ] New public APIs have `@since` tags in Javadoc

2022-08-04 07:34 UTC, krzysztofslusarski commented
The real thing in that PR is not shown by GitHub. We copy the ```SqlValidatorImpl``` to our codebase and we are changing a method ```expandStar``` by removing:

```java
      // If NATURAL JOIN or USING is present, move key fields to the front of
      // the list, per standard SQL. Disabled if there are dynamic fields.
      if (!hasDynamicStruct || Bug.CALCITE_2400_FIXED) {
        SqlNode from = requireNonNull(scope.getNode().getFrom(),
            () -> "getFrom for " + scope.getNode());
        new Permute(from, 0).permute(selectItems, fields);
      }
```

2022-08-04 07:35 UTC, krzysztofslusarski approved these changes

2022-08-04 07:36 UTC, krzysztofslusarski commented
@hakanmemisoglu new calcite has just been published. I believe we need to upgrade to 1.31 and copy new validator.

2022-08-04 07:37 UTC, krzysztofslusarski requested changes
To recheck after upgrading calcite

2022-08-11 09:23 UTC, krzysztofslusarski approved these changes

2022-08-24 07:26 UTC, viliam-durina requested changes

2022-08-24 07:26 UTC, viliam-durina commented on hazelcast-sql/src/main/java/org/apache/calcite/sql/validate/SqlValidatorImpl.java
> +                // }
With this you essentially broke this type of join. For example, if you have `t1(a, b)` and `t2(c, b)` and you do `FROM t1 JOIN t2 USING (b)` or `FROM t1 NATURAL JOIN t2`, the query is supposed to have these columns on the output: `b, a, c`. With this code commented out, it has `a, b, c, b` - `b` is there twice with the same value, and it should be at the beginning, as the calcite code comment says

2022-08-24 09:00 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/12787/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/12787/Hazelcast-pr-builder-12787.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR] com.hazelcast.jet.sql.impl.connector.map.SqlJoinTest$SqlInnerJoinTest.test_whenNaturalJoin_noErrorShouldHappen(com.hazelcast.jet.sql.impl.connector.map.SqlJoinTest$SqlInnerJoinTest)
[ERROR]   Run 1: SqlJoinTest$SqlInnerJoinTest.test_whenNaturalJoin_noErrorShouldHappen:686->SqlTestSupport.assertRowsAnyOrder:272->SqlTestSupport.assertRowsAnyOrder:296->SqlTestSupport.assertRowsAnyOrder:322 
Expecting:
  <[Row{[42, 420, foo, 43, 430, foo]}]>
to contain exactly in any order:
  <[Row{[foo, 42, 420, 43, 430]}]>
elements not found:
  <[Row{[foo, 42, 420, 43, 430]}]>
and elements not expected:
  <[Row{[42, 420, foo, 43, 430, foo]}]>

[ERROR]   Run 2: SqlJoinTest$SqlInnerJoinTest.test_whenNaturalJoin_noErrorShouldHappen:686->SqlTestSupport.assertRowsAnyOrder:272->SqlTestSupport.assertRowsAnyOrder:296->SqlTestSupport.assertRowsAnyOrder:322 
Expecting:
  <[Row{[42, 420, foo, 43, 430, foo]}]>
to contain exactly in any order:
  <[Row{[foo, 42, 420, 43, 430]}]>
elements not found:
  <[Row{[foo, 42, 420, 43, 430]}]>
and elements not expected:
  <[Row{[42, 420, foo, 43, 430, foo]}]>

[INFO] 
[INFO] 
[ERROR] Tests run: 5106, Failures: 1, Errors: 0, Skipped: 20
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2022-08-24 10:12 UTC, viliam-durina commented
I propose to close this PR for now. It replaces an error with an incorrect result. The workaround is to not use `SELECT *` in combination with `USING` or `NATURAL JOIN`. 

Hidden fields aren't natively supported by calcite. It is our implementation of hidden fields that causes it.

2022-08-30 13:24 UTC, closed without merging