[HZ-989] Implement JSON_OBJECTAGG aggregation for SQL
hazelcast/hazelcast pull request #21871
Opened 2022-07-28 11:19 UTC by hakanmemisoglu

Checklist:
- [ ] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [ ] Label `Add to Release Notes` or `Not Release Notes content` set
- [ ] Request reviewers if possible
- [ ] Send backports/forwardports if fix needs to be applied to past/future releases
- [ ] New public APIs have `@Nonnull/@Nullable` annotations
- [ ] New public APIs have `@since` tags in Javadoc

2022-07-28 12:10 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/12225/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/12225/Hazelcast-pr-builder-12225.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   AntiEntropyCleanupTest.testCleanup:81->HazelcastTestSupport.assertTrueEventually:1328->HazelcastTestSupport.assertTrueEventually:1226 ? ConcurrentModification
[INFO] 
[ERROR] Tests run: 50594, Failures: 0, Errors: 1, Skipped: 238
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2022-07-28 12:55 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/12227/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/12227/Hazelcast-pr-builder-12227.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   NestingAndCasingExpressionTest.testAllExpressionsCovered:116 Tests not implemented: 
test_JSON_OBJECTAGG_ABSENT_ON_NULL
test_JSON_OBJECTAGG_NULL_ON_NULL
[INFO] 
[ERROR] Tests run: 4895, Failures: 1, Errors: 0, Skipped: 5
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2022-08-02 07:03 UTC, krzysztofslusarski approved these changes
Approve with minors

2022-08-02 07:03 UTC, krzysztofslusarski commented on hazelcast-sql/src/test/java/com/hazelcast/jet/sql/impl/aggregate/JsonSqlAggregateTest.java
> +    private boolean jsonObjectEquals(JsonObject obj, JsonObject obj2) {
If I read correctly that method allows mixed order of attributes only on the first level, so sucha a JSONs are not equal:
```json
{
    "foo": {
        "bar1" : "bar1",
        "bar2" : "bar2"
    }
}
```
```json
{
    "foo": {
        "bar2" : "bar2",
        "bar1" : "bar1"
    }
}
```

If I'm correct then maybe you should rename the method so it inform about that. But it is just a minor.

2022-08-02 07:03 UTC, krzysztofslusarski commented on hazelcast-sql/src/test/java/com/hazelcast/jet/sql/impl/expression/misc/NestingAndCasingExpressionTest.java
> +    private static final Set<String> EXCEPTIONAL_EXPRESSIONS = new HashSet<>(
:heart:

2022-08-02 08:52 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/12296/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/12296/Hazelcast-pr-builder-12296.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ClientMapPartitionLostListenerTest.test_mapPartitionLostListener_invoked_fromOtherNode:133->assertProxyExistsEventually:163->HazelcastTestSupport.assertTrueEventually:1328->HazelcastTestSupport.assertTrueEventually:1226 There is no proxy with name 02dee8bc-5f6c-4417-abf1-bcfb543f582a created (yet)
[INFO] 
[ERROR] Tests run: 50597, Failures: 1, Errors: 0, Skipped: 238
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2022-08-02 09:15 UTC, hakanmemisoglu commented
/run-lab-run

2022-08-02 09:16 UTC, hakanmemisoglu commented
run-lab-run

2022-08-05 12:38 UTC, Fly-Style commented on hazelcast-sql/src/test/java/com/hazelcast/jet/sql/impl/aggregate/JsonSqlAggregateTest.java
> +    private void assertRowsWithJsonValues(String sql, Collection<Row> rows) {
Generally, this method looks overcomplicated and it is not universal. E.g., I tried to play with `JSON_OBJECTAGG`, and wrote this test:

```
        @Test
        public void test_sandbox() {
            String name = "map";
            createMapping(name, String.class, int.class);
            IMap<String, Integer> map = instance().getMap(name);
            map.put("A", 1);
            map.put("B", 1);

            assertRowsWithJsonValues(
                    "SELECT JSON_OBJECTAGG(KEY __key VALUE this) FROM " + name,
                    asList(
                            new Row("{\"A\":1,\"B\":1}")
                    )
            );
        }
```
, but I have no success due to assertion errors below. 
Would you like to refactor it and make it more general? Then you can move it to `SqlJsonTestSupport`. WDYT?

2022-08-05 12:40 UTC, Fly-Style commented on hazelcast-sql/src/test/java/com/hazelcast/jet/sql/impl/expression/misc/NestingAndCasingExpressionTest.java
> +    private static final Set<String> EXCEPTIONAL_EXPRESSIONS = new HashSet<>(
![image](https://user-images.githubusercontent.com/10107557/183079071-2529d3a3-e676-4901-be44-0c1fb276a0e6.png)

2022-08-05 12:48 UTC, Fly-Style reviewed
Generally looks correct, some comments above.

2022-08-06 22:19 UTC, viliam-durina requested changes
I added a couple of failing tests dealing with null and duplicate keys.

2022-08-06 22:25 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/12405/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/12405/Hazelcast-pr-builder-12405.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.2:checkstyle (default) on project hazelcast-sql: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There is 1 error reported by Checkstyle 8.38 with /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_2/checkstyle/checkstyle.xml ruleset. -> [Help 1]
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_2/hazelcast-sql/src/test/java/com/hazelcast/jet/sql/impl/aggregate/JsonSqlAggregateTest.java:365:13: Redundant 'public' modifier. [RedundantModifier]
--------------------------
</pre>
</details>

2022-08-06 22:35 UTC, hz-devops-test commented
The job `Hazelcast-pr-compiler` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-compiler/2383/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-compiler/2383/Hazelcast-pr-compiler-2383.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.2:checkstyle (default) on project hazelcast-sql: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There is 1 error reported by Checkstyle 8.38 with /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/checkstyle/checkstyle.xml ruleset. -> [Help 1]
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/hazelcast-sql/src/test/java/com/hazelcast/jet/sql/impl/aggregate/JsonSqlAggregateTest.java:365:13: Redundant 'public' modifier. [RedundantModifier]
--------------------------
</pre>
</details>

2022-08-08 06:22 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/12407/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/12407/Hazelcast-pr-builder-12407.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR] com.hazelcast.jet.sql.impl.aggregate.JsonSqlAggregateTest$JsonObjectAggregationTest.test_nullKey(com.hazelcast.jet.sql.impl.aggregate.JsonSqlAggregateTest$JsonObjectAggregationTest)
[ERROR]   Run 1: JsonSqlAggregateTest$JsonObjectAggregationTest.test_nullKey:255 
Expecting code to raise a throwable.
[ERROR]   Run 2: JsonSqlAggregateTest$JsonObjectAggregationTest.test_nullKey:255 
Expecting code to raise a throwable.
[INFO] 
[INFO] 
[ERROR] Tests run: 4942, Failures: 1, Errors: 0, Skipped: 13
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2022-08-08 10:28 UTC, viliam-durina approved these changes

2022-08-08 11:33 UTC, merged