Fix WM handling in AggregateSlidingWindowRule
hazelcast/hazelcast pull request #21921
Opened 2022-08-06 10:51 UTC by viliam-durina

Fixes #21920

2022-08-08 10:44 UTC, Fly-Style approved these changes

2022-08-08 11:00 UTC, krzysztofslusarski requested changes

2022-08-08 11:00 UTC, krzysztofslusarski commented on hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/opt/physical/AggregateSlidingWindowPhysicalRule.java
> +                .intersect(logicalAggregate.getGroupSet());
From what I see the builder also has ```intersect``` method, that will save us creating some litter. The ```intersect``` in ```ImmutableBitSet```:
```java
  public ImmutableBitSet intersect(ImmutableBitSet that) {
    final Builder builder = rebuild();
    builder.intersect(that);
    return builder.build();
  }
```
It just creates a builder. Unfortunately the ```intersect``` in builder doesn't returns it's instance.

2022-08-09 09:28 UTC, krzysztofslusarski approved these changes

2022-08-09 12:11 UTC, merged