[HZ-1240] Fix weird issue with wrong optimized rel in rel tree during scan opt
hazelcast/hazelcast pull request #22152
Opened 2022-09-06 10:28 UTC by Fly-Style

2022-09-06 11:27 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/12984/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/12984/Hazelcast-pr-builder-12984.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   TenantControlTest.testTenantControl_executionBeforeAfterOps:146 expected:<4> but was:<3>
[INFO] 
[ERROR] Tests run: 4323, Failures: 1, Errors: 0, Skipped: 8
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2022-09-06 12:20 UTC, Fly-Style commented
run-lab-run

2022-09-14 11:36 UTC, ivanthescientist approved these changes

2022-09-14 13:56 UTC, viliam-durina requested changes

2022-09-14 13:56 UTC, viliam-durina commented on hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/opt/physical/SelectByKeyDeoptPhysicalRule.java
> +final class SelectByKeyDeoptPhysicalRule extends RelRule<RelRule.Config> {
This is weird. Ideally we shouldn't have produced a non-working plan in the first place. We probably can't have a rule that will match an element on the root, but instead after logical opt we can look at the whole plan, and convert to select-by-key, if the whole tree is just a single full-scan.

2022-09-14 14:51 UTC, viliam-durina approved these changes

2022-09-14 16:51 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/13141/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/13141/Hazelcast-pr-builder-13141.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   LogicalSelectTest.test_selectByKeyWithDynamicParam:199->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithDynamicParam:199->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithDynamicParam:199->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithDynamicParam:199->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithDynamicParam:199->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithDynamicParam:199->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithDynamicParam:199->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithDynamicParam:199->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithDynamicParam:199->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithDynamicParam:199->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithDynamicParam:199->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithDynamicParam:199->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithDynamicParam:199->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithDynamicParam:199->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithDynamicParamExpression:221->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithLiteral:150->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithLiteral:150->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithLiteral:150->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithLiteral:150->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithLiteral:150->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithLiteral:150->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithLiteral:150->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithLiteral:150->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1
 [...]

2022-09-14 17:16 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/13142/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/13142/Hazelcast-pr-builder-13142.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   LogicalSelectTest.test_selectByKeyWithDynamicParam:199->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithDynamicParam:199->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithDynamicParam:199->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithDynamicParam:199->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithDynamicParam:199->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithDynamicParam:199->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithDynamicParam:199->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithDynamicParam:199->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithDynamicParam:199->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithDynamicParam:199->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithDynamicParam:199->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithDynamicParam:199->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithDynamicParam:199->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithDynamicParam:199->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithDynamicParamExpression:221->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithLiteral:150->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithLiteral:150->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithLiteral:150->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithLiteral:150->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithLiteral:150->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithLiteral:150->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithLiteral:150->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithLiteral:150->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1
 [...]

2022-09-14 17:42 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/13143/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/13143/Hazelcast-pr-builder-13143.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   KinesisIntegrationTest.restart_dynamicStream_graceful:359->restart_dynamicStream:397->assertMessages:580->AbstractKinesisTest.assertMessages:159->HazelcastTestSupport.assertTrueEventually:1338->HazelcastTestSupport.assertTrueEventually:1236->AbstractKinesisTest.lambda$assertMessages$3:176 Messages for key 230 differ!
	expected: 100
	  actual: 24 expected:<[230: msg 000000230, 230: msg 000000480, 230: msg 000000730, 230: msg 000000980, 230: msg 000001230, 230: msg 000001480, 230: msg 000001730, 230: msg 000001980, 230: msg 000002230, 230: msg 000002480, 230: msg 000002730, 230: msg 000002980, 230: msg 000003230, 230: msg 000003480, 230: msg 000003730, 230: msg 000003980, 230: msg 000004230, 230: msg 000004480, 230: msg 000004730, 230: msg 000004980, 230: msg 000005230, 230: msg 000005480, 230: msg 000005730, 230: msg 000005980, 230: msg 000006230, 230: msg 000006480, 230: msg 000006730, 230: msg 000006980, 230: msg 000007230, 230: msg 000007480, 230: msg 000007730, 230: msg 000007980, 230: msg 000008230, 230: msg 000008480, 230: msg 000008730, 230: msg 000008980, 230: msg 000009230, 230: msg 000009480, 230: msg 000009730, 230: msg 000009980, 230: msg 000010230, 230: msg 000010480, 230: msg 000010730, 230: msg 000010980, 230: msg 000011230, 230: msg 000011480, 230: msg 000011730, 230: msg 000011980, 230: msg 000012230, 230: msg 000012480, 230: msg 000012730, 230: msg 000012980, 230: msg 000013230, 230: msg 000013480, 230: msg 000013730, 230: msg 000013980, 230: msg 000014230, 230: msg 000014480, 230: msg 000014730, 230: msg 000014980, 230: msg 000015230, 230: msg 000015480, 230: msg 000015730, 230: msg 000015980, 230: msg 000016230, 230: msg 000016480, 230: msg 000016730, 230: msg 000016980, 230: msg 000017230, 230: msg 000017480, 230: msg 000017730, 230: msg 000017980, 230: msg 000018230, 230: msg 000018480, 230: msg 000018730, 230: msg 000018980, 230: msg 000019230, 230: msg 000019480, 230: msg 000019730, 230: msg 000019980, 230: msg 000020230, 230: msg 000020480, 230: msg 000020730, 230: msg 000020980, 230: msg 000021230, 230: msg 000021480, 230: msg 000021730, 230: msg 000021980, 230: msg 000022230, 230: msg 000022480, 230: msg 000022730, 230: msg 000022980, 230: msg 000023230, 230: msg 000023480, 230: msg 000023730, 230: msg 000023980, 230: msg 000024230, 230: msg 000024480, 230: msg 000024730, 230: msg 000024980]> but was:<[230: msg 000000230, 230: msg 000000480, 230: msg 000000730, 230: msg 000000980, 230: msg 000001230, 230: msg 000001480, 230: msg 000001730, 230: msg 000001980, 230: msg 000002230, 230: msg 000002480, 230: msg 000002730, 230: msg 000002980, 230: msg 000003230, 230: msg 000003480, 230: msg 000003730, 230: msg 000003980, 230: msg 000004230, 230: msg 000004480, 230: msg 000004730, 230: msg 000004980, 230: msg 000005230, 230: msg 000005480, 230: msg 000005730, 230: msg 000005980]>
[INFO] 
[ERROR] Tests run: 42, Failures: 1, Errors: 0, Skipped: 3
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2022-09-14 18:06 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/13145/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/13145/Hazelcast-pr-builder-13145.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   LocalMultiMapStatsTest.testPutAllAndHitsGeneratedKey:151->testPutAllAndHitsGeneratedTemplate:123->testPutAllAndHitsGeneratedTemplateVerify:134 expected:<100> but was:<99>
[INFO] 
[ERROR] Tests run: 50842, Failures: 1, Errors: 0, Skipped: 238
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2022-09-15 07:38 UTC, krzysztofslusarski approved these changes

2022-09-15 08:50 UTC, Fly-Style commented
run-lab-run

2022-09-15 09:43 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/13170/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/13170/Hazelcast-pr-builder-13170.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   LogicalSelectTest.test_selectByKeyWithDynamicParam:199->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithDynamicParam:199->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithDynamicParam:199->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithDynamicParam:199->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithDynamicParam:199->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithDynamicParam:199->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithDynamicParam:199->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithDynamicParam:199->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithDynamicParam:199->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithDynamicParam:199->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithDynamicParam:199->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithDynamicParam:199->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithDynamicParam:199->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithDynamicParam:199->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithDynamicParamExpression:221->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithLiteral:150->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithLiteral:150->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithLiteral:150->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithLiteral:150->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithLiteral:150->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithLiteral:150->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithLiteral:150->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1

>>> EXPECTED PLAN:
00: SelectByKeyMapLogicalRel

>>> ACTUAL PLAN:
00: FullScanLogicalRel
] expected:<[SelectByKeyMap]LogicalRel> but was:<[FullScan]LogicalRel>
[ERROR]   LogicalSelectTest.test_selectByKeyWithLiteral:150->OptimizerTestSupport.assertPlan:162->OptimizerTestSupport.assertPlan:177 [Plan rows are different at 1
 [...]

2022-09-15 17:34 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/13194/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/13194/Hazelcast-pr-builder-13194.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ExplainStatementTest.test_explainStatementDynamicParams:77 expected:<[FullScanPhysicalRel(table=[[hazelcast, public, map[projects=[$0, $1], filter==($0, ?0)]]], discriminator=[0]])> but was:<[SelectByKeyMapPhysicalRel(table=[[hazelcast, public, map[projects=[$0, $1], filter==($0, ?0)]]], keyCondition=[?0], projections=[__key=[$0], this=[$1]]])>
[INFO] 
[ERROR] Tests run: 5116, Failures: 1, Errors: 0, Skipped: 9
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2022-09-15 18:06 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/13196/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/13196/Hazelcast-pr-builder-13196.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ExplainStatementTest.test_explainStatementDynamicParams:77 expected:<[FullScanPhysicalRel(table=[[hazelcast, public, map[projects=[$0, $1], filter==($0, ?0)]]], discriminator=[0]])> but was:<[SelectByKeyMapPhysicalRel(table=[[hazelcast, public, map[projects=[$0, $1], filter==($0, ?0)]]], keyCondition=[?0], projections=[__key=[$0], this=[$1]]])>
[INFO] 
[ERROR] Tests run: 5116, Failures: 1, Errors: 0, Skipped: 9
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2022-09-16 09:17 UTC, hz-devops-test commented
The job `Hazelcast-pr-EE-compiler` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-EE-compiler/2447/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-EE-compiler/2447/Hazelcast-pr-EE-compiler-2447.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] COMPILATION ERROR : 
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler_2/hazelcast-enterprise/hazelcast-enterprise/src/main/java/com/hazelcast/enterprise/wan/impl/EnterpriseWanReplicationService.java:[328,46] error: method publishAntiEntropyEvent in interface InternalWanPublisher<T> cannot be applied to given types;
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5.1:compile (default-compile) on project hazelcast-enterprise: Compilation failure: Compilation failure: 
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler_2/hazelcast-enterprise/hazelcast-enterprise/src/main/java/com/hazelcast/enterprise/wan/impl/EnterpriseWanReplicationService.java:[328,46] error: method publishAntiEntropyEvent in interface InternalWanPublisher<T> cannot be applied to given types;
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler_2/hazelcast-enterprise/hazelcast-enterprise/src/main/java/com/hazelcast/enterprise/wan/impl/EnterpriseWanReplicationService.java:[328,46] error: method publishAntiEntropyEvent in interface InternalWanPublisher<T> cannot be applied to given types;
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler_2/hazelcast-enterprise/hazelcast-enterprise/src/main/java/com/hazelcast/enterprise/wan/impl/replication/WanBatchPublisher.java:[437,4] error: method does not override or implement a method from a supertype
--------------------------
</pre>
</details>

2022-09-16 09:50 UTC, Fly-Style commented
run-ee-compiler

2022-09-16 09:51 UTC, Fly-Style commented
run-ee-compile

2022-09-16 12:02 UTC, merged