[HZ-1467] Use standard Java binary serialization methods for SQL JSON object
hazelcast/hazelcast pull request #22177
Opened 2022-09-08 14:20 UTC by Fly-Style

2022-09-09 08:32 UTC, viliam-durina requested changes

2022-09-09 08:32 UTC, viliam-durina commented on hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/inject/JsonUpsertTarget.java
> +            ObjectOutputStream oos = new ObjectOutputStream(baos);
This doesn't write the bytes for the JSON document, but some garbage. Tests fail then.

2022-09-12 07:23 UTC, krzysztofslusarski requested changes

2022-09-12 07:23 UTC, krzysztofslusarski commented on hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/inject/JsonUpsertTarget.java
> +        ByteArrayOutputStream baos = new ByteArrayOutputStream();
Shouldn't it just be:
```java
return ((HazelcastJsonValue) super.conclude()).getValue().getBytes(StandardCharsets.UTF_8);
```
?

2022-09-12 07:26 UTC, Fly-Style commented on hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/inject/JsonUpsertTarget.java
> +        ByteArrayOutputStream baos = new ByteArrayOutputStream();
I am late for 3 minutes :)

2022-09-12 07:27 UTC, Fly-Style commented
Need further discussion, closing it.

2022-09-12 07:27 UTC, closed without merging

2022-09-12 07:33 UTC, hz-devops-test commented
The job `Hazelcast-pr-EE-compiler` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-EE-compiler/2299/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-EE-compiler/2299/Hazelcast-pr-EE-compiler-2299.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal on project hazelcast-sql: Could not resolve dependencies for project com.hazelcast:hazelcast-sql:jar:5.2-SNAPSHOT: Could not transfer artifact com.github.everit-org.json-schema:org.everit.json.schema:jar:1.12.2 from/to jitpack.io (https://jitpack.io): Transfer failed for https://jitpack.io/com/github/everit-org/json-schema/org.everit.json.schema/1.12.2/org.everit.json.schema-1.12.2.jar: java.net.SocketException: Connection reset -> [Help 1]
--------------------------
</pre>
</details>

2022-09-12 08:20 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/13059/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/13059/Hazelcast-pr-builder-13059.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   SqlJsonTest.test_allTypes:205->SqlTestSupport.assertRowsEventuallyInAnyOrder:149->SqlTestSupport.assertRowsEventuallyInAnyOrder:204 
Expecting:
  <[Row{[1, string, true, 127, 32767, 2147483647, 9223372036854775807, 1.23456794E9, 1.234512345678901E14, 9223372036854775.123, 12:23:34, 2020-04-15, 2020-04-15T12:23:34.001, 2020-04-15T12:23:34.200Z, {42=43}, null]}]>
to contain exactly in any order:
  <[Row{[1, string, true, 127, 32767, 2147483647, 9223372036854775807, 1.23456794E9, 1.234512345678901E14, 9223372036854775.123, 12:23:34, 2020-04-15, 2020-04-15T12:23:34.001, 2020-04-15T12:23:34.200Z, {42=43}, null]}]>
elements not found:
  <[Row{[1, string, true, 127, 32767, 2147483647, 9223372036854775807, 1.23456794E9, 1.234512345678901E14, 9223372036854775.123, 12:23:34, 2020-04-15, 2020-04-15T12:23:34.001, 2020-04-15T12:23:34.200Z, {42=43}, null]}]>
and elements not expected:
  <[Row{[1, string, true, 127, 32767, 2147483647, 9223372036854775807, 1.23456794E9, 1.234512345678901E14, 9223372036854775.123, 12:23:34, 2020-04-15, 2020-04-15T12:23:34.001, 2020-04-15T12:23:34.200Z, {42=43}, null]}]>

[INFO] 
[ERROR] Tests run: 5113, Failures: 1, Errors: 0, Skipped: 12
[INFO] 

[ERROR] There are test failures.
</pre>
</details>