[22024] error on SQL limit
hazelcast/hazelcast pull request #22186
Opened 2022-09-09 16:35 UTC by TomaszGaweda

TBD

In general, no exception in logs on query `close()` and when iterating over it.

This is one step more than [#22176](https://github.com/hazelcast/hazelcast/pull/22176)

Fixes INSERT_LINK_TO_THE_ISSUE_HERE

Backport of: INSERT_LINK_TO_THE_ORIGINAL_PR_HERE

EE PR: INSERT_LINK_TO_THE_EE_PR_HERE

Breaking changes (list specific methods/types/messages):
* API
* client protocol format
* serialized form
* snapshot format

Checklist:
- [ ] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [ ] Label `Add to Release Notes` or `Not Release Notes content` set
- [ ] Request reviewers if possible
- [ ] Send backports/forwardports if fix needs to be applied to past/future releases
- [ ] New public APIs have `@Nonnull/@Nullable` annotations
- [ ] New public APIs have `@since` tags in Javadoc

2022-09-09 16:42 UTC, TomaszGaweda commented
run-nightly-tests

2022-09-12 10:43 UTC, TomaszGaweda commented
Nightly tests failed due to known issue: https://github.com/hazelcast/hazelcast/issues/19326

2022-09-14 16:55 UTC, TomaszGaweda commented
run-nightly-tests

2022-09-16 14:40 UTC, hz-devops-test commented
The job `Hazelcast-pr-EE-compiler` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-EE-compiler/2466/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-EE-compiler/2466/Hazelcast-pr-EE-compiler-2466.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] COMPILATION ERROR : 
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast-enterprise/hazelcast-enterprise/src/main/java/com/hazelcast/enterprise/wan/impl/replication/WanBatchPublisher.java:[437,4] error: method does not override or implement a method from a supertype
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5.1:compile (default-compile) on project hazelcast-enterprise: Compilation failure: Compilation failure: 
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast-enterprise/hazelcast-enterprise/src/main/java/com/hazelcast/enterprise/wan/impl/replication/WanBatchPublisher.java:[437,4] error: method does not override or implement a method from a supertype
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast-enterprise/hazelcast-enterprise/src/main/java/com/hazelcast/enterprise/wan/impl/EnterpriseWanReplicationService.java:[328,46] error: method publishAntiEntropyEvent in interface InternalWanPublisher<T> cannot be applied to given types;
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast-enterprise/hazelcast-enterprise/src/main/java/com/hazelcast/enterprise/wan/impl/replication/WanBatchPublisher.java:[437,4] error: method does not override or implement a method from a supertype
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast-enterprise/hazelcast-enterprise/src/main/java/com/hazelcast/enterprise/wan/impl/EnterpriseWanReplicationService.java:[328,46] error: method publishAntiEntropyEvent in interface InternalWanPublisher<T> cannot be applied to given types;
--------------------------
</pre>
</details>

2022-09-16 15:19 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/13235/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/13235/Hazelcast-pr-builder-13235.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   KinesisIntegrationTest.restart_dynamicStream_graceful:401->restart_dynamicStream:439->assertMessages:652->AbstractKinesisTest.assertMessages:162->HazelcastTestSupport.assertTrueEventually:1338->HazelcastTestSupport.assertTrueEventually:1236->AbstractKinesisTest.lambda$assertMessages$3:179 Messages for key 230 differ!
	expected: 100
	  actual: 6 expected:<[230: msg 000000230, 230: msg 000000480, 230: msg 000000730, 230: msg 000000980, 230: msg 000001230, 230: msg 000001480, 230: msg 000001730, 230: msg 000001980, 230: msg 000002230, 230: msg 000002480, 230: msg 000002730, 230: msg 000002980, 230: msg 000003230, 230: msg 000003480, 230: msg 000003730, 230: msg 000003980, 230: msg 000004230, 230: msg 000004480, 230: msg 000004730, 230: msg 000004980, 230: msg 000005230, 230: msg 000005480, 230: msg 000005730, 230: msg 000005980, 230: msg 000006230, 230: msg 000006480, 230: msg 000006730, 230: msg 000006980, 230: msg 000007230, 230: msg 000007480, 230: msg 000007730, 230: msg 000007980, 230: msg 000008230, 230: msg 000008480, 230: msg 000008730, 230: msg 000008980, 230: msg 000009230, 230: msg 000009480, 230: msg 000009730, 230: msg 000009980, 230: msg 000010230, 230: msg 000010480, 230: msg 000010730, 230: msg 000010980, 230: msg 000011230, 230: msg 000011480, 230: msg 000011730, 230: msg 000011980, 230: msg 000012230, 230: msg 000012480, 230: msg 000012730, 230: msg 000012980, 230: msg 000013230, 230: msg 000013480, 230: msg 000013730, 230: msg 000013980, 230: msg 000014230, 230: msg 000014480, 230: msg 000014730, 230: msg 000014980, 230: msg 000015230, 230: msg 000015480, 230: msg 000015730, 230: msg 000015980, 230: msg 000016230, 230: msg 000016480, 230: msg 000016730, 230: msg 000016980, 230: msg 000017230, 230: msg 000017480, 230: msg 000017730, 230: msg 000017980, 230: msg 000018230, 230: msg 000018480, 230: msg 000018730, 230: msg 000018980, 230: msg 000019230, 230: msg 000019480, 230: msg 000019730, 230: msg 000019980, 230: msg 000020230, 230: msg 000020480, 230: msg 000020730, 230: msg 000020980, 230: msg 000021230, 230: msg 000021480, 230: msg 000021730, 230: msg 000021980, 230: msg 000022230, 230: msg 000022480, 230: msg 000022730, 230: msg 000022980, 230: msg 000023230, 230: msg 000023480, 230: msg 000023730, 230: msg 000023980, 230: msg 000024230, 230: msg 000024480, 230: msg 000024730, 230: msg 000024980]> but was:<[230: msg 000000230, 230: msg 000000480, 230: msg 000000730, 230: msg 000000980, 230: msg 000001230, 230: msg 000001480]>
[INFO] 
[ERROR] Tests run: 44, Failures: 1, Errors: 0, Skipped: 3
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2022-09-16 15:27 UTC, TomaszGaweda commented
run-lab-run

2022-09-16 16:26 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/13242/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/13242/Hazelcast-pr-builder-13242.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.2.0:checkstyle (default) on project hazelcast: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There is 1 error reported by Checkstyle 8.38 with /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/checkstyle/checkstyle.xml ruleset. -> [Help 1]
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/test/java/com/hazelcast/test/ExceptionsCapturer.java:47:25: 'if' is not followed by whitespace. [WhitespaceAround]
--------------------------
</pre>
</details>

2022-09-16 16:26 UTC, hz-devops-test commented
The job `Hazelcast-pr-compiler` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-compiler/3072/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-compiler/3072/Hazelcast-pr-compiler-3072.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.2.0:checkstyle (default) on project hazelcast: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There is 1 error reported by Checkstyle 8.38 with /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/checkstyle/checkstyle.xml ruleset. -> [Help 1]
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/hazelcast/src/test/java/com/hazelcast/test/ExceptionsCapturer.java:47:25: 'if' is not followed by whitespace. [WhitespaceAround]
--------------------------
</pre>
</details>

2022-09-16 17:41 UTC, TomaszGaweda commented
run-lab-run

2022-09-19 08:32 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/13252/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/13252/Hazelcast-pr-builder-13252.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   SqlFilterProjectTest.test_projectExpressionProjectExpressionFilter:434 ? HazelcastSql
[ERROR]   SqlFilterProjectTest>SimpleTestInClusterSupport.supportAfter:114 ? ArrayIndexOutOfBounds
[INFO] 
[ERROR] Tests run: 5116, Failures: 0, Errors: 2, Skipped: 9
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2022-09-19 09:38 UTC, TomaszGaweda commented
run-lab-run

2022-09-19 10:05 UTC, frant-hartm requested changes

2022-09-19 10:18 UTC, TomaszGaweda commented on hazelcast/pom.xml
> -        </dependency>
It was added in a branch with previous solution, GitHub seems to be not recognizing this correctly.

in short: I wanted to catch everything from console, this lib seemed to be handy. However, there were some problems that not everything was catched correctly - forks, etc. Our current approach with catching logs is a much improved version with catching via this lib

2022-09-19 10:19 UTC, TomaszGaweda commented on hazelcast/src/test/java/com/hazelcast/jet/SimpleTestInClusterSupport.java
> +    protected void assertNoJobsLeft(HazelcastInstance instance) {
Done 4014327126e453ddc717a22c178ac79acfd36219

2022-09-19 11:35 UTC, TomaszGaweda commented on hazelcast/pom.xml
> -        </dependency>
Actually, it was in the same branch: https://github.com/hazelcast/hazelcast/pull/22186/commits/57a2903359d9b4f38cd95a3b778026f2ba546027

2022-09-19 12:40 UTC, frant-hartm commented on hazelcast/pom.xml
> -        </dependency>
This is in `hazelcast` module, it is also present on master.
Looks like we don't need it anymore, but would be better to remove it in a separate PR.

2022-09-19 14:11 UTC, TomaszGaweda commented on hazelcast/pom.xml
> -        </dependency>
Ah, right. Reverted: 2565a403f3a7cdb7816ee5bf1a7188c75b951315

2022-09-19 15:10 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/13271/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/13271/Hazelcast-pr-builder-13271.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   CompactSchemaReplicationTest.testSchemaReplication_whenAMemberThrows_duringPreparationPhase:67 UnfinishedStubbing
[INFO] 
[ERROR] Tests run: 50850, Failures: 0, Errors: 1, Skipped: 238
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2022-09-19 15:38 UTC, TomaszGaweda commented
run-lab-run

2022-09-19 20:38 UTC, frant-hartm approved these changes

2022-09-20 22:03 UTC, viliam-durina requested changes
I don't like the overall design of this PR. Why don't we keep everything as it was, and just reduce the log level to minimum for the `SqlLimitReachedException`? The new impl has multiple flaws.

2022-09-20 22:03 UTC, viliam-durina commented on hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/QueryResultProducerImpl.java
> +    public QueryResultProducerImpl(boolean isBatch) {
What about jobs like this:
```
INSERT INTO a
SELECT * FROM b LIMIT 100;
```
Such job would not use `QueryResultProducer`. I'm not sure we support it now, but we may support it some day.

And the javadoc is stale.

2022-09-22 14:24 UTC, TomaszGaweda commented
Core of the change was merged, the rest needs rework - maybe some day ;) Closing for now

2022-09-22 14:24 UTC, closed without merging