[HZ-1382] Move toward Semantic versioning (X.Y.Z)
hazelcast/hazelcast pull request #22218
Opened 2022-09-14 07:40 UTC by kwart

This PR introduces versioning scheme change for minor versions. Instead of using `5.2` (X.Y), we would use `5.2.0` (X.Y.Z). The change will move us toward [Semantic versioning](https://semver.org/).

The proposal is related to Docker updates planned in [HZ-1382](https://hazelcast.atlassian.net/browse/HZ-1382).
The minor version Docker label will reference the latest patch.

For instance, when `5.2.0` is released, these Docker labels will be added/updated:
`latest = 5.2 = 5.2.0`
When `5.2.1` is released, the labels will be changed:
`latest = 5.2 = 5.2.1`

2022-09-14 07:51 UTC, hz-devops-test commented
The job `Hazelcast-pr-EE-compiler` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-EE-compiler/2352/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-EE-compiler/2352/Hazelcast-pr-EE-compiler-2352.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] COMPILATION ERROR : 
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast-enterprise/hazelcast-enterprise/src/main/java/com/hazelcast/map/impl/operation/EnterpriseMapChunk.java:[96,45] error: method removeReplicatedRecord in interface RecordStore<R> cannot be applied to given types;
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5.1:compile (default-compile) on project hazelcast-enterprise: Compilation failure: Compilation failure: 
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast-enterprise/hazelcast-enterprise/src/main/java/com/hazelcast/map/impl/operation/EnterpriseMapChunk.java:[96,45] error: method removeReplicatedRecord in interface RecordStore<R> cannot be applied to given types;
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast-enterprise/hazelcast-enterprise/src/main/java/com/hazelcast/map/impl/wan/MerkleTreeUpdaterMutationObserver.java:[72,4] error: method does not override or implement a method from a supertype
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast-enterprise/hazelcast-enterprise/src/main/java/com/hazelcast/map/impl/EnterpriseMapReplicationStateHolder.java:[85,27] error: method removeReplicatedRecord in interface RecordStore<R> cannot be applied to given types;
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast-enterprise/hazelcast-enterprise/src/main/java/com/hazelcast/map/impl/recordstore/EnterpriseTieredRecordStore.java:[218,17] error: no suitable method found for removeReplicatedRecord(Data)
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast-enterprise/hazelcast-enterprise/src/main/java/com/hazelcast/map/impl/operation/EnterpriseMapChunk.java:[96,45] error: method removeReplicatedRecord in interface RecordStore<R> cannot be applied to given types;
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast-enterprise/hazelcast-enterprise/src/main/java/com/hazelcast/map/impl/wan/MerkleTreeUpdaterMutationObserver.java:[32,7] error: MerkleTreeUpdaterMutationObserver is not abstract and does not override abstract method onEvictRecord(Data,R,boolean) in MutationObserver
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast-enterprise/hazelcast-enterprise/src/main/java/com/hazelcast/map/impl/wan/MerkleTreeUpdaterMutationObserver.java:[67,4] error: method does not override or implement a method from a supertype
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast-enterprise/hazelcast-enterprise/src/main/java/com/hazelcast/map/impl/wan/MerkleTreeUpdaterMutationObserver.java:[72,4] error: method does not override or implement a method from a supertype
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast-enterprise/hazelcast-enterprise/src/main/java/com/hazelcast/map/impl/EnterpriseMapReplicationStateHolder.java:[85,27] error: method removeReplicatedRecord in interface RecordStore<R> cannot be applied to given types;
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast-enterprise/hazelcast-enterprise/src/main/java/com/hazelcast/map/impl/recordstore/EnterpriseTieredRecordStore.java:[214,4] error: method does not override or implement a method from a supertype
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast-enterprise/hazelcast-enterprise/src/main/java/com/hazelcast/map/impl/recordstore/EnterpriseTieredRecordStore.java:[218,17] error: no suitable method found for removeReplicatedRecord(Data)
--------------------------
</pre>
</details>

2022-09-14 08:12 UTC, hz-devops-test commented
The job `Hazelcast-pr-EE-compiler` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-EE-compiler/2355/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-EE-compiler/2355/Hazelcast-pr-EE-compiler-2355.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] COMPILATION ERROR : 
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler_2/hazelcast-enterprise/hazelcast-enterprise/src/main/java/com/hazelcast/map/impl/recordstore/EnterpriseTieredRecordStore.java:[214,4] error: method does not override or implement a method from a supertype
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5.1:compile (default-compile) on project hazelcast-enterprise: Compilation failure: Compilation failure: 
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler_2/hazelcast-enterprise/hazelcast-enterprise/src/main/java/com/hazelcast/map/impl/recordstore/EnterpriseTieredRecordStore.java:[214,4] error: method does not override or implement a method from a supertype
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler_2/hazelcast-enterprise/hazelcast-enterprise/src/main/java/com/hazelcast/map/impl/recordstore/EnterpriseTieredRecordStore.java:[218,17] error: no suitable method found for removeReplicatedRecord(Data)
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler_2/hazelcast-enterprise/hazelcast-enterprise/src/main/java/com/hazelcast/map/impl/wan/MerkleTreeUpdaterMutationObserver.java:[72,4] error: method does not override or implement a method from a supertype
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler_2/hazelcast-enterprise/hazelcast-enterprise/src/main/java/com/hazelcast/map/impl/recordstore/EnterpriseTieredRecordStore.java:[214,4] error: method does not override or implement a method from a supertype
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler_2/hazelcast-enterprise/hazelcast-enterprise/src/main/java/com/hazelcast/map/impl/recordstore/EnterpriseTieredRecordStore.java:[218,17] error: no suitable method found for removeReplicatedRecord(Data)
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler_2/hazelcast-enterprise/hazelcast-enterprise/src/main/java/com/hazelcast/map/impl/EnterpriseMapReplicationStateHolder.java:[85,27] error: method removeReplicatedRecord in interface RecordStore<R> cannot be applied to given types;
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler_2/hazelcast-enterprise/hazelcast-enterprise/src/main/java/com/hazelcast/map/impl/operation/EnterpriseMapChunk.java:[96,45] error: method removeReplicatedRecord in interface RecordStore<R> cannot be applied to given types;
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler_2/hazelcast-enterprise/hazelcast-enterprise/src/main/java/com/hazelcast/map/impl/wan/MerkleTreeUpdaterMutationObserver.java:[32,7] error: MerkleTreeUpdaterMutationObserver is not abstract and does not override abstract method onEvictRecord(Data,R,boolean) in MutationObserver
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler_2/hazelcast-enterprise/hazelcast-enterprise/src/main/java/com/hazelcast/map/impl/wan/MerkleTreeUpdaterMutationObserver.java:[67,4] error: method does not override or implement a method from a supertype
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler_2/hazelcast-enterprise/hazelcast-enterprise/src/main/java/com/hazelcast/map/impl/wan/MerkleTreeUpdaterMutationObserver.java:[72,4] error: method does not override or implement a method from a supertype
--------------------------
</pre>
</details>

2022-09-14 08:32 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/13116/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/13116/Hazelcast-pr-builder-13116.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   KinesisIntegrationTest.restart_dynamicStream_graceful:359->restart_dynamicStream:397->assertMessages:580->AbstractKinesisTest.assertMessages:159->HazelcastTestSupport.assertTrueEventually:1338->HazelcastTestSupport.assertTrueEventually:1236->AbstractKinesisTest.lambda$assertMessages$3:176 Messages for key 230 differ!
	expected: 100
	  actual: 2 expected:<[230: msg 000000230, 230: msg 000000480, 230: msg 000000730, 230: msg 000000980, 230: msg 000001230, 230: msg 000001480, 230: msg 000001730, 230: msg 000001980, 230: msg 000002230, 230: msg 000002480, 230: msg 000002730, 230: msg 000002980, 230: msg 000003230, 230: msg 000003480, 230: msg 000003730, 230: msg 000003980, 230: msg 000004230, 230: msg 000004480, 230: msg 000004730, 230: msg 000004980, 230: msg 000005230, 230: msg 000005480, 230: msg 000005730, 230: msg 000005980, 230: msg 000006230, 230: msg 000006480, 230: msg 000006730, 230: msg 000006980, 230: msg 000007230, 230: msg 000007480, 230: msg 000007730, 230: msg 000007980, 230: msg 000008230, 230: msg 000008480, 230: msg 000008730, 230: msg 000008980, 230: msg 000009230, 230: msg 000009480, 230: msg 000009730, 230: msg 000009980, 230: msg 000010230, 230: msg 000010480, 230: msg 000010730, 230: msg 000010980, 230: msg 000011230, 230: msg 000011480, 230: msg 000011730, 230: msg 000011980, 230: msg 000012230, 230: msg 000012480, 230: msg 000012730, 230: msg 000012980, 230: msg 000013230, 230: msg 000013480, 230: msg 000013730, 230: msg 000013980, 230: msg 000014230, 230: msg 000014480, 230: msg 000014730, 230: msg 000014980, 230: msg 000015230, 230: msg 000015480, 230: msg 000015730, 230: msg 000015980, 230: msg 000016230, 230: msg 000016480, 230: msg 000016730, 230: msg 000016980, 230: msg 000017230, 230: msg 000017480, 230: msg 000017730, 230: msg 000017980, 230: msg 000018230, 230: msg 000018480, 230: msg 000018730, 230: msg 000018980, 230: msg 000019230, 230: msg 000019480, 230: msg 000019730, 230: msg 000019980, 230: msg 000020230, 230: msg 000020480, 230: msg 000020730, 230: msg 000020980, 230: msg 000021230, 230: msg 000021480, 230: msg 000021730, 230: msg 000021980, 230: msg 000022230, 230: msg 000022480, 230: msg 000022730, 230: msg 000022980, 230: msg 000023230, 230: msg 000023480, 230: msg 000023730, 230: msg 000023980, 230: msg 000024230, 230: msg 000024480, 230: msg 000024730, 230: msg 000024980]> but was:<[230: msg 000000230, 230: msg 000000480]>
[INFO] 
[ERROR] Tests run: 42, Failures: 1, Errors: 0, Skipped: 3
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2022-09-14 09:30 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/13119/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/13119/Hazelcast-pr-builder-13119.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   BasicNestedFieldsTest.test_mixedModeUpsert:321->execute:576->execute:580 ? HazelcastSql
[INFO] 
[ERROR] Tests run: 5113, Failures: 0, Errors: 1, Skipped: 12
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2022-09-14 16:50 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/13140/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/13140/Hazelcast-pr-builder-13140.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   KinesisIntegrationTest.restart_dynamicStream_graceful:359->restart_dynamicStream:397->assertMessages:580->AbstractKinesisTest.assertMessages:159->HazelcastTestSupport.assertTrueEventually:1338->HazelcastTestSupport.assertTrueEventually:1236->AbstractKinesisTest.lambda$assertMessages$3:176 Messages for key 230 differ!
	expected: 100
	  actual: 13
	first difference at index: 0
		expected: 0: 230: msg 000000230, 1: 230: msg 000000480, 2: 230: msg 000000730, 3: 230: msg 000000980, 4: 230: msg 000001230, 
		  actual: 0: 230: msg 000012980, 1: 230: msg 000013230, 2: 230: msg 000013480, 3: 230: msg 000013730, 4: 230: msg 000013980,  expected:<[230: msg 000000230, 230: msg 000000480, 230: msg 000000730, 230: msg 000000980, 230: msg 000001230, 230: msg 000001480, 230: msg 000001730, 230: msg 000001980, 230: msg 000002230, 230: msg 000002480, 230: msg 000002730, 230: msg 000002980, 230: msg 000003230, 230: msg 000003480, 230: msg 000003730, 230: msg 000003980, 230: msg 000004230, 230: msg 000004480, 230: msg 000004730, 230: msg 000004980, 230: msg 000005230, 230: msg 000005480, 230: msg 000005730, 230: msg 000005980, 230: msg 000006230, 230: msg 000006480, 230: msg 000006730, 230: msg 000006980, 230: msg 000007230, 230: msg 000007480, 230: msg 000007730, 230: msg 000007980, 230: msg 000008230, 230: msg 000008480, 230: msg 000008730, 230: msg 000008980, 230: msg 000009230, 230: msg 000009480, 230: msg 000009730, 230: msg 000009980, 230: msg 000010230, 230: msg 000010480, 230: msg 000010730, 230: msg 000010980, 230: msg 000011230, 230: msg 000011480, 230: msg 000011730, 230: msg 000011980, 230: msg 000012230, 230: msg 000012480, 230: msg 000012730, 230: msg 000012980, 230: msg 000013230, 230: msg 000013480, 230: msg 000013730, 230: msg 000013980, 230: msg 000014230, 230: msg 000014480, 230: msg 000014730, 230: msg 000014980, 230: msg 000015230, 230: msg 000015480, 230: msg 000015730, 230: msg 000015980, 230: msg 000016230, 230: msg 000016480, 230: msg 000016730, 230: msg 000016980, 230: msg 000017230, 230: msg 000017480, 230: msg 000017730, 230: msg 000017980, 230: msg 000018230, 230: msg 000018480, 230: msg 000018730, 230: msg 000018980, 230: msg 000019230, 230: msg 000019480, 230: msg 000019730, 230: msg 000019980, 230: msg 000020230, 230: msg 000020480, 230: msg 000020730, 230: msg 000020980, 230: msg 000021230, 230: msg 000021480, 230: msg 000021730, 230: msg 000021980, 230: msg 000022230, 230: msg 000022480, 230: msg 000022730, 230: msg 000022980, 230: msg 000023230, 230: msg 000023480, 230: msg 000023730, 230: msg 000023980, 230: msg 000024230, 230: msg 000024480, 230: msg 000024730, 230: msg 000024980]> but was:<[230: msg 000012980, 230: msg 000013230, 230: msg 000013480, 230: msg 000013730, 230: msg 000013980, 230: msg 000014230, 230: msg 000014480, 230: msg 000014730, 230: msg 000014980, 230: msg 000015230, 230: msg 000015480, 230: msg 000015730, 230: msg 000015980]>
[INFO] 
[ERROR] Tests run: 42, Failures: 1, Errors: 0, Skipped: 3
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2022-09-14 18:38 UTC, olukas approved these changes

2022-09-14 19:34 UTC, srknzl commented
I think as the @hazelcast/apis team we should make sure we don't use 5.2-SNAPSHOT in our client repos anymore. Otherwise, we will not use the latest snapshot of 5.2. Instead we should use 5.2.0-SNAPSHOT. So, is it reasonable to put `all client should check` label to this PR ? @mdumandag @ihsandemir

Other than that, it looks ok I think

2022-09-14 21:36 UTC, frant-hartm requested changes

2022-09-14 21:36 UTC, frant-hartm commented on extensions/hazelcast-3-connector/hazelcast-3-connector-common/pom.xml
> +            <version>5.2.0-SNAPSHOT</version>
This should be `${project.parent.version}`. Let's fix it.

2022-09-14 21:36 UTC, frant-hartm commented on extensions/mapstore/pom.xml
> +            <version>5.2.0-SNAPSHOT</version>
Changed to `${project.parent.version}` in #22213

2022-09-15 06:02 UTC, kwart commented
Thanks for the reviews, guys. I've added a new commit covering the comments.

2022-09-15 07:17 UTC, frant-hartm approved these changes

2022-09-15 10:19 UTC, merged