Fixes/5.2.0/hz 1208 2
hazelcast/hazelcast pull request #22369
Opened 2022-09-30 09:16 UTC by TomaszGaweda

Merge persistence & hot-restart when getting MapConfig; while this is missing, map configs based on default or wildcard configs will not have their `DataPersistenceConfig` & `HotRestartConfig` merged, resulting in unexpected EE-side persistence behaviour (see [HZ-1208](https://hazelcast.atlassian.net/browse/HZ-1208)).

With these fixes, it is revealed that assertions in `ConfigSearchTest` and `DynamicConfigSearchOrderTest` are faulty, since they are based on config name. The tests are now fixed to compare on other properties of the config (eg maxIdleSeconds).

EE PR: https://github.com/hazelcast/hazelcast-enterprise/pull/5336 (only adds test on EE side; by @vbekiaris)

Checklist:
- [ ] Label `Add to Release Notes` or `Not Release Notes content` set
- [ ] Send backports/forwardports if fix needs to be applied to past/future releases

2022-09-30 09:29 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/13501/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/13501/Hazelcast-pr-builder-13501.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.2.0:checkstyle (default) on project hazelcast: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There is 1 error reported by Checkstyle 8.38 with /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/checkstyle/checkstyle.xml ruleset. -> [Help 1]
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/test/java/com/hazelcast/internal/dynamicconfig/ConfigSearchTest.java:827:12: 'abstract' modifier out of order with the JLS suggestions. [ModifierOrder]
--------------------------
</pre>
</details>

2022-09-30 09:34 UTC, hz-devops-test commented
The job `Hazelcast-pr-compiler` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-compiler/3287/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-compiler/3287/Hazelcast-pr-compiler-3287.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.2.0:checkstyle (default) on project hazelcast: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There is 1 error reported by Checkstyle 8.38 with /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/checkstyle/checkstyle.xml ruleset. -> [Help 1]
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/hazelcast/src/test/java/com/hazelcast/internal/dynamicconfig/ConfigSearchTest.java:827:12: 'abstract' modifier out of order with the JLS suggestions. [ModifierOrder]
--------------------------
</pre>
</details>

2022-09-30 10:39 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/13503/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/13503/Hazelcast-pr-builder-13503.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   DynamicConfigSearchOrderTest.testSearchConfigOrderForStaticConfigs:102 Static exact name should match expected:<200> but was:<100>
[ERROR]   PhoneHomeTest.testMapCountUsingEviction:329 expected:<[0]> but was:<[1]>
[ERROR]   PhoneHomeTest.testMapCountWithAtleastOneAttribute:308 expected:<[0]> but was:<[1]>
[ERROR]   PhoneHomeTest.testMapCountWithAtleastOneIndex:246 expected:<[0]> but was:<[1]>
[ERROR]   PhoneHomeTest.testMapCountWithAtleastOneQueryCache:224 expected:<[0]> but was:<[1]>
[ERROR]   PhoneHomeTest.testMapCountWithBackupReadEnabled:185 expected:<[0]> but was:<[1]>
[ERROR]   PhoneHomeTest.testMapCountWithHotRestartEnabled:267 expected:<[0]> but was:<[1]>
[ERROR]   PhoneHomeTest.testMapCountWithMapStoreEnabled:207 expected:<[0]> but was:<[1]>
[ERROR]   PhoneHomeTest.testMapCountWithNativeInMemory:349 expected:<[0]> but was:<[1]>
[ERROR]   PhoneHomeTest.testMapCountWithWANReplication:293 expected:<[0]> but was:<[1]>
[ERROR]   PhoneHomeTest.testMapGetLatencyWithMapStore:539->HazelcastTestSupport.assertGreaterOrEquals:1387 Expected 'mpgtlams' to be greater than or equal to 200, but was -1
[ERROR]   PhoneHomeTest.testMapPutLatencyWithMapStore:519->HazelcastTestSupport.assertGreaterOrEquals:1387 Expected 'mpptlams' to be greater than or equal to 200, but was -1
[ERROR] Errors: 
[ERROR]   ClientMapNearCacheTest.testAfterLoadAllNearCacheIsInvalidated:461 ? IllegalArgument
[ERROR]   ClientMapNearCacheTest.testAfterLoadAllWithDefinedKeysNearCacheIsInvalidated:525 ? NullPointer
[ERROR]   ClientMapNearCacheTest.testMemberLoadAll_invalidates_clientNearCache:490 ? IllegalArgument
[INFO] 
[ERROR] Tests run: 50897, Failures: 12, Errors: 3, Skipped: 238
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2022-09-30 11:40 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/13505/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/13505/Hazelcast-pr-builder-13505.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   BackupTest.testBackupPutWhenOwnerNodeDead:295 ? TestTimedOut test timed out af...
[INFO] 
[ERROR] Tests run: 50897, Failures: 0, Errors: 1, Skipped: 238
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2022-09-30 11:50 UTC, TomaszGaweda commented
run-lab-run

2022-10-03 07:36 UTC, frant-hartm requested changes

2022-10-03 07:36 UTC, frant-hartm commented on hazelcast/src/main/java/com/hazelcast/config/Config.java
> +     * @see #getConfigPatternMatcher()`
Typo?

2022-10-03 07:36 UTC, frant-hartm commented on hazelcast/src/main/java/com/hazelcast/internal/config/ConfigUtils.java
> +        return config;
```suggestion
        return copyConstructor.newInstance(defConfig);
```

2022-10-03 07:38 UTC, TomaszGaweda commented on hazelcast/src/test/java/com/hazelcast/config/ConfigTest.java
> +        assertTrue(binaryMapConfig.getHotRestartConfig().isFsync());
and it win - fsync value is from data persistence

2022-10-03 07:41 UTC, hz-devops-test commented
The job `Hazelcast-pr-EE-compiler` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-EE-compiler/2695/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-EE-compiler/2695/Hazelcast-pr-EE-compiler-2695.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] COMPILATION ERROR : 
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/hazelcast/src/main/java/com/hazelcast/internal/config/ConfigUtils.java:[135,43] incompatible types: capture#1 of ? cannot be converted to T
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.0:compile (default-compile) on project hazelcast: Compilation failure
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/hazelcast/src/main/java/com/hazelcast/internal/config/ConfigUtils.java:[135,43] incompatible types: capture#1 of ? cannot be converted to T
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/hazelcast/src/main/java/com/hazelcast/internal/config/ConfigUtils.java:[135,43] incompatible types: capture#1 of ? cannot be converted to T
--------------------------
</pre>
</details>

2022-10-03 07:41 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/13519/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/13519/Hazelcast-pr-builder-13519.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] COMPILATION ERROR : 
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/internal/config/ConfigUtils.java:[135,43] incompatible types: capture#1 of ? cannot be converted to T
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.0:compile (default-compile) on project hazelcast: Compilation failure
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/internal/config/ConfigUtils.java:[135,43] incompatible types: capture#1 of ? cannot be converted to T
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/internal/config/ConfigUtils.java:[135,43] incompatible types: capture#1 of ? cannot be converted to T
--------------------------
</pre>
</details>

2022-10-03 07:42 UTC, hz-devops-test commented
The job `Hazelcast-pr-compiler` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-compiler/3303/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-compiler/3303/Hazelcast-pr-compiler-3303.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] COMPILATION ERROR : 
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/hazelcast/src/main/java/com/hazelcast/internal/config/ConfigUtils.java:[135,43] incompatible types: capture#1 of ? cannot be converted to T
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.0:compile (default-compile) on project hazelcast: Compilation failure
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/hazelcast/src/main/java/com/hazelcast/internal/config/ConfigUtils.java:[135,43] incompatible types: capture#1 of ? cannot be converted to T
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/hazelcast/src/main/java/com/hazelcast/internal/config/ConfigUtils.java:[135,43] incompatible types: capture#1 of ? cannot be converted to T
--------------------------
</pre>
</details>

2022-10-03 07:47 UTC, TomaszGaweda commented on hazelcast/src/test/java/com/hazelcast/internal/dynamicconfig/DynamicConfigSearchOrderTest.java
> +        hazelcastInstance.getConfig().addMapConfig(new MapConfig(DYNAMIC_NAME).setMaxIdleSeconds(DYNAMIC_MAX_IDLE));
Yes, 8abd3d84f7d89895025fbdac4739b58e31c3bc96

2022-10-03 07:47 UTC, TomaszGaweda commented on hazelcast/src/test/java/com/hazelcast/internal/dynamicconfig/DynamicConfigSearchOrderTest.java
> +        assertEquals("Dynamic wildcard name should match", DYNAMIC_MAX_IDLE,
Indeed, fixed this and few other: 8abd3d84f7d89895025fbdac4739b58e31c3bc96

2022-10-03 07:47 UTC, TomaszGaweda commented on hazelcast/src/test/java/com/hazelcast/internal/dynamicconfig/ConfigSearchTest.java
> +                assertThat(dataConfig.getMaxSize(), equalTo(3));
8abd3d84f7d89895025fbdac4739b58e31c3bc96

2022-10-03 07:47 UTC, TomaszGaweda commented on hazelcast/src/main/java/com/hazelcast/config/Config.java
> +     * @see #getConfigPatternMatcher()`
probably failed shortcut ;P 8abd3d84f7d89895025fbdac4739b58e31c3bc96

2022-10-03 07:50 UTC, hz-devops-test commented
The job `Hazelcast-pr-EE-compiler` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-EE-compiler/2696/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-EE-compiler/2696/Hazelcast-pr-EE-compiler-2696.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] COMPILATION ERROR : 
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/hazelcast/src/main/java/com/hazelcast/internal/config/ConfigUtils.java:[135,43] incompatible types: capture#1 of ? cannot be converted to T
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.0:compile (default-compile) on project hazelcast: Compilation failure
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/hazelcast/src/main/java/com/hazelcast/internal/config/ConfigUtils.java:[135,43] incompatible types: capture#1 of ? cannot be converted to T
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/hazelcast/src/main/java/com/hazelcast/internal/config/ConfigUtils.java:[135,43] incompatible types: capture#1 of ? cannot be converted to T
--------------------------
</pre>
</details>

2022-10-03 07:50 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/13520/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/13520/Hazelcast-pr-builder-13520.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] COMPILATION ERROR : 
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/internal/config/ConfigUtils.java:[135,43] incompatible types: capture#1 of ? cannot be converted to T
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.0:compile (default-compile) on project hazelcast: Compilation failure
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/internal/config/ConfigUtils.java:[135,43] incompatible types: capture#1 of ? cannot be converted to T
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/internal/config/ConfigUtils.java:[135,43] incompatible types: capture#1 of ? cannot be converted to T
--------------------------
</pre>
</details>

2022-10-03 09:02 UTC, frant-hartm approved these changes

2022-10-03 09:15 UTC, vbekiaris approved these changes
thanks for dealing with this PR @TomaszGaweda

2022-10-03 09:18 UTC, merged