Import old MongoDB connector
hazelcast/hazelcast pull request #22565
Opened 2022-10-21 11:07 UTC by TomaszGaweda

INSERT_PR_DESCRIPTION_HERE

Fixes INSERT_LINK_TO_THE_ISSUE_HERE

Backport of: INSERT_LINK_TO_THE_ORIGINAL_PR_HERE

EE PR: INSERT_LINK_TO_THE_EE_PR_HERE

Breaking changes (list specific methods/types/messages):
* API
* client protocol format
* serialized form
* snapshot format

Checklist:
- [ ] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [ ] Label `Add to Release Notes` or `Not Release Notes content` set
- [ ] Request reviewers if possible
- [ ] Send backports/forwardports if fix needs to be applied to past/future releases
- [ ] New public APIs have `@Nonnull/@Nullable` annotations
- [ ] New public APIs have `@since` tags in Javadoc

2022-10-21 11:07 UTC, devOpsHazelcast commented
[![CLA assistant check](https://cla.hazelcast.org/pull/badge/not_signed)](https://cla.hazelcast.org/hazelcast/hazelcast?pullRequest=22565) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.hazelcast.org/hazelcast/hazelcast?pullRequest=22565) before we can accept your contribution.<br/>**3** out of **4** committers have signed the CLA.<br/><br/>:white_check_mark: TomaszGaweda<br/>:white_check_mark: ufukyilmaz<br/>:white_check_mark: gurbuzali<br/>:x: devOpsHazelcast<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.hazelcast.org/check/hazelcast/hazelcast?pullRequest=22565) it.</sub>

2022-10-21 11:15 UTC, hz-devops-test commented
The job `Hazelcast-pr-EE-compiler` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-EE-compiler/2972/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-EE-compiler/2972/Hazelcast-pr-EE-compiler-2972.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] COMPILATION ERROR : 
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mongodb/src/test/java/com/hazelcast/jet/contrib/mongodb/MongoDBContainer.java:[21,37] package org.testcontainers.containers does not exist
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.0:testCompile (default-testCompile) on project hazelcast-mongodb: Compilation failure: Compilation failure: 
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mongodb/src/test/java/com/hazelcast/jet/contrib/mongodb/MongoDBContainer.java:[21,37] package org.testcontainers.containers does not exist
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mongodb/src/test/java/com/hazelcast/jet/contrib/mongodb/MongoDBContainer.java:[22,37] package org.testcontainers.containers does not exist
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mongodb/src/test/java/com/hazelcast/jet/contrib/mongodb/MongoDBContainer.java:[27,39] cannot find symbol
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mongodb/src/test/java/com/hazelcast/jet/contrib/mongodb/MongoDBContainer.java:[21,37] package org.testcontainers.containers does not exist
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mongodb/src/test/java/com/hazelcast/jet/contrib/mongodb/MongoDBContainer.java:[22,37] package org.testcontainers.containers does not exist
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mongodb/src/test/java/com/hazelcast/jet/contrib/mongodb/MongoDBContainer.java:[27,39] cannot find symbol
--------------------------
</pre>
</details>

2022-10-21 11:18 UTC, hz-devops-test commented
The job `Hazelcast-pr-compiler` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-compiler/3581/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-compiler/3581/Hazelcast-pr-compiler-3581.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.2.0:checkstyle (default) on project hazelcast-mongodb: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There are 9 errors reported by Checkstyle 8.38 with /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mongodb/../../checkstyle/checkstyle_jet.xml ruleset. -> [Help 1]
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mongodb/src/main/java/com/hazelcast/jet/contrib/mongodb/MongoDBSinkBuilder.java:2: Line does not match expected header line of ' * Copyright 2021 Hazelcast Inc.'. [Header]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mongodb/src/main/java/com/hazelcast/jet/contrib/mongodb/MongoDBSinks.java:2: Line does not match expected header line of ' * Copyright 2021 Hazelcast Inc.'. [Header]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mongodb/src/main/java/com/hazelcast/jet/contrib/mongodb/MongoDBSourceBuilder.java:2: Line does not match expected header line of ' * Copyright 2021 Hazelcast Inc.'. [Header]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mongodb/src/main/java/com/hazelcast/jet/contrib/mongodb/MongoDBSources.java:2: Line does not match expected header line of ' * Copyright 2021 Hazelcast Inc.'. [Header]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mongodb/src/main/java/com/hazelcast/jet/contrib/mongodb/package-info.java:2: Line does not match expected header line of ' * Copyright 2021 Hazelcast Inc.'. [Header]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mongodb/src/test/java/com/hazelcast/jet/contrib/mongodb/AbstractMongoDBTest.java:2: Line does not match expected header line of ' * Copyright 2021 Hazelcast Inc.'. [Header]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mongodb/src/test/java/com/hazelcast/jet/contrib/mongodb/MongoDBContainer.java:2: Line does not match expected header line of ' * Copyright 2021 Hazelcast Inc.'. [Header]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mongodb/src/test/java/com/hazelcast/jet/contrib/mongodb/MongoDBSinkTest.java:2: Line does not match expected header line of ' * Copyright 2021 Hazelcast Inc.'. [Header]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mongodb/src/test/java/com/hazelcast/jet/contrib/mongodb/MongoDBSourceTest.java:2: Line does not match expected header line of ' * Copyright 2021 Hazelcast Inc.'. [Header]
--------------------------
</pre>
</details>

2022-10-21 11:54 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/13834/Hazelcast-pr-builder-13834.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/13834/Hazelcast-pr-builder-13834.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.2.0:checkstyle (default) on project hazelcast-mongodb: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There are 9 errors reported by Checkstyle 8.38 with /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/extensions/mongodb/../../checkstyle/checkstyle_jet.xml ruleset. -> [Help 1]
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/extensions/mongodb/src/main/java/com/hazelcast/jet/contrib/mongodb/MongoDBSinkBuilder.java:2: Line does not match expected header line of ' * Copyright 2021 Hazelcast Inc.'. [Header]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/extensions/mongodb/src/main/java/com/hazelcast/jet/contrib/mongodb/MongoDBSinks.java:2: Line does not match expected header line of ' * Copyright 2021 Hazelcast Inc.'. [Header]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/extensions/mongodb/src/main/java/com/hazelcast/jet/contrib/mongodb/MongoDBSourceBuilder.java:2: Line does not match expected header line of ' * Copyright 2021 Hazelcast Inc.'. [Header]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/extensions/mongodb/src/main/java/com/hazelcast/jet/contrib/mongodb/MongoDBSources.java:2: Line does not match expected header line of ' * Copyright 2021 Hazelcast Inc.'. [Header]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/extensions/mongodb/src/main/java/com/hazelcast/jet/contrib/mongodb/package-info.java:2: Line does not match expected header line of ' * Copyright 2021 Hazelcast Inc.'. [Header]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/extensions/mongodb/src/test/java/com/hazelcast/jet/contrib/mongodb/AbstractMongoDBTest.java:2: Line does not match expected header line of ' * Copyright 2021 Hazelcast Inc.'. [Header]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/extensions/mongodb/src/test/java/com/hazelcast/jet/contrib/mongodb/MongoDBContainer.java:2: Line does not match expected header line of ' * Copyright 2021 Hazelcast Inc.'. [Header]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/extensions/mongodb/src/test/java/com/hazelcast/jet/contrib/mongodb/MongoDBSinkTest.java:2: Line does not match expected header line of ' * Copyright 2021 Hazelcast Inc.'. [Header]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/extensions/mongodb/src/test/java/com/hazelcast/jet/contrib/mongodb/MongoDBSourceTest.java:2: Line does not match expected header line of ' * Copyright 2021 Hazelcast Inc.'. [Header]
--------------------------
</pre>
</details>

2022-10-21 16:54 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/13842/Hazelcast-pr-builder-13842.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/13842/Hazelcast-pr-builder-13842.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.2.0:checkstyle (default) on project hazelcast-mongodb: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There are 3 errors reported by Checkstyle 8.38 with /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/extensions/mongodb/../../checkstyle/checkstyle_jet.xml ruleset. -> [Help 1]
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/extensions/mongodb/src/test/java/com/hazelcast/jet/mongodb/AbstractMongoDBTest.java:45:5: Variable access definition in wrong order. [DeclarationOrder]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/extensions/mongodb/src/test/java/com/hazelcast/jet/mongodb/AbstractMongoDBTest.java:46:5: Variable access definition in wrong order. [DeclarationOrder]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/extensions/mongodb/src/test/java/com/hazelcast/jet/mongodb/AbstractMongoDBTest.java:47:5: Variable access definition in wrong order. [DeclarationOrder]
--------------------------
</pre>
</details>

2022-10-21 17:04 UTC, hz-devops-test commented
The job `Hazelcast-pr-compiler` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-compiler/3587/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-compiler/3587/Hazelcast-pr-compiler-3587.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.2.0:checkstyle (default) on project hazelcast-mongodb: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There are 3 errors reported by Checkstyle 8.38 with /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mongodb/../../checkstyle/checkstyle_jet.xml ruleset. -> [Help 1]
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mongodb/src/test/java/com/hazelcast/jet/mongodb/AbstractMongoDBTest.java:45:5: Variable access definition in wrong order. [DeclarationOrder]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mongodb/src/test/java/com/hazelcast/jet/mongodb/AbstractMongoDBTest.java:46:5: Variable access definition in wrong order. [DeclarationOrder]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mongodb/src/test/java/com/hazelcast/jet/mongodb/AbstractMongoDBTest.java:47:5: Variable access definition in wrong order. [DeclarationOrder]
--------------------------
</pre>
</details>

2022-11-09 16:29 UTC, ldziedziul reviewed
Should we add it to `distribution/pom.xml`?

2022-11-10 15:16 UTC, TomaszGaweda commented
Indeed it should, thanks @ldziedziul :)

2022-11-21 10:58 UTC, orcunc approved these changes

2022-11-22 08:34 UTC, frant-hartm requested changes

2022-11-22 11:25 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/14411/Hazelcast-pr-builder-14411.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/14411/Hazelcast-pr-builder-14411.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 17.725 s <<< FAILURE! - in com.hazelcast.jet.mongodb.MongoDBSinkTest
--------------------------
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   MongoDBSinkTest.test_whenServerNotAvailable:82
[INFO] 
[ERROR] Tests run: 7, Failures: 1, Errors: 0, Skipped: 0
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2022-11-22 12:20 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/14415/Hazelcast-pr-builder-14415.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/14415/Hazelcast-pr-builder-14415.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.2.0:checkstyle (default) on project hazelcast-jet-mongodb: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There is 1 error reported by Checkstyle 8.38 with /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_2/extensions/mongodb/../../checkstyle/checkstyle_jet.xml ruleset. -> [Help 1]
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_2/extensions/mongodb/src/test/java/com/hazelcast/jet/mongodb/MongoDBSinkTest.java:66:64: '(' is followed by whitespace. [ParenPad]
--------------------------
</pre>
</details>

2022-11-22 12:26 UTC, frant-hartm approved these changes

2022-12-12 12:10 UTC, merged