Various tests for HZ-1294
hazelcast/hazelcast pull request #22677
Opened 2022-11-02 18:44 UTC by sumnerib

Includes various test scenarios for the JDBC OOTB Connector (JDBC Mapping and `GenericMapStore`)

2022-11-04 13:14 UTC, frant-hartm requested changes
Looks mostly good. Special thanks for the test cases for the reported issues.

2022-11-07 13:44 UTC, sumnerib commented on extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java
> +    public void givenColumnPropSubset_whenStore_thenTableContainsRow() throws SQLException {
Thanks! I'll be sure to add the permalinks to the respective issues once this is merged.

2022-11-07 13:52 UTC, sumnerib commented on hazelcast-sql/src/test/java/com/hazelcast/jet/sql/impl/connector/jdbc/mysql/MySQLJoinJdbcSqlConnectorTest.java
> +@Category({NightlyTest.class, ParallelJVMTest.class})
I was just copying what  was already there in `MySql*JdbcSqlConnectorTest`s and `Postgres*JdbcSqlConnectorTest`s. Should these be updated to remove the `ParallelJVMTest` as well?

2022-11-07 14:15 UTC, olukas reviewed
LGTM. I like those tests. What we can also add is more negative tests. For example for GenericMapStore - what happens if we're trying to load data but column is not as expected (for example we expect `int` but it contains `String`)? What happens if we're trying to delete non-existing row? etc.

2022-11-14 13:18 UTC, frant-hartm commented on hazelcast-sql/src/test/java/com/hazelcast/jet/sql/impl/connector/jdbc/mysql/MySQLJoinJdbcSqlConnectorTest.java
> +@Category({NightlyTest.class, ParallelJVMTest.class})
Yes this is a copy-paste mistake.
These should be `NightlyTest` only.

2022-11-14 14:36 UTC, frant-hartm commented on extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreIntegrationTest.java
> +    }
You are right.
Orcun has a PR in review regarding this.

2022-11-14 20:02 UTC, frant-hartm approved these changes

2022-11-14 20:10 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/14215/Hazelcast-pr-builder-14215.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/14215/Hazelcast-pr-builder-14215.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>

</pre>
</details>

2022-11-15 13:12 UTC, sumnerib commented
run-lab-run

2022-11-15 14:09 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/14238/Hazelcast-pr-builder-14238.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/14238/Hazelcast-pr-builder-14238.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>

</pre>
</details>

2022-11-15 18:37 UTC, sumnerib commented
run-lab-run

2022-11-18 09:16 UTC, olukas approved these changes
LGTM, thanks Isaac!

2022-11-18 11:56 UTC, merged