Await MapStore initialization before tests [HZ-1695] (#21993)
hazelcast/hazelcast pull request #22806
Opened 2022-11-14 13:02 UTC by burakgok

Some tests in `GenericMapStoreTest` seemingly end before MapStore is initialized, which prevents the mapping from being destroyed by `SimpleTestInClusterSupport#supportAfter`.

Additionally, some refactoring is done.

Fixes HZ-1695 #21993

2022-11-14 20:54 UTC, frant-hartm requested changes

2022-11-14 20:54 UTC, frant-hartm commented on extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java
> +        mapStore.awaitInitFinished();
Some tests intentionally fail to create the mapping, so the `awaitInitFinished` throws an exception. See the failed tests.

2022-11-15 13:48 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/14236/Hazelcast-pr-builder-14236.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/14236/Hazelcast-pr-builder-14236.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   CacheClientListenerTest>CacheListenerTest.testSyncListener:110 Cache operations have not finished in 130 seconds when sync listener is present!
[ERROR] Errors: 
[ERROR]   CacheClientListenerTest>CacheListenerTest.testReplaceWithSyncListener_whenEntryNotExists:137->getCachingProvider:63 ? TestTimedOut test timed out after 30000 milliseconds
[INFO] 
[ERROR] Tests run: 50995, Failures: 1, Errors: 1, Skipped: 238
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2022-11-15 13:51 UTC, krzysztofslusarski commented
run-lab-run

2022-11-15 13:59 UTC, frant-hartm approved these changes

2022-11-15 14:00 UTC, krzysztofslusarski approved these changes

2022-11-15 14:49 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/14240/Hazelcast-pr-builder-14240.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/14240/Hazelcast-pr-builder-14240.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>

</pre>
</details>

2022-11-16 14:45 UTC, frant-hartm commented
run-lab-run

2022-11-16 22:43 UTC, merged