Guard pip install with flock
hazelcast/hazelcast pull request #22829
Opened 2022-11-15 21:34 UTC by frant-hartm

The tests run multiple instances, each instance using a different virtual environment.

The issue looks similar to this https://github.com/pypa/pip/issues/2361

It seems there are still issues with concurrent pip runs.

Added flock to guard all pip executions.

Fixes #22599

Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [x] Label `Add to Release Notes` or `Not Release Notes content` set
- [x] Request reviewers if possible
- [ ] Send backports/forwardports if fix needs to be applied to past/future releases

2022-11-15 22:34 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/14253/Hazelcast-pr-builder-14253.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/14253/Hazelcast-pr-builder-14253.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   CacheClientListenerTest>CacheListenerTest.testSyncListener:110 Cache operations have not finished in 130 seconds when sync listener is present!
[INFO] 
[ERROR] Tests run: 50995, Failures: 1, Errors: 0, Skipped: 238
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2022-11-15 22:57 UTC, TomaszGaweda approved these changes

2022-11-16 07:27 UTC, kwart requested changes
Could you use another path to the lock file? Otherwise looks good.

2022-11-16 07:27 UTC, kwart commented on extensions/python/src/main/resources/jet_to_python_init.sh
> +flock --exclusive /tmp/jet-pip.lock python3 -m pip install --upgrade pip
We should use another directory. The `/tmp` is shared between the host and containers on our Jenkins.

2022-11-24 06:53 UTC, kwart approved these changes

2022-11-24 09:17 UTC, merged