Wait for database to be up before returning URL
hazelcast/hazelcast pull request #22868
Opened 2022-11-17 15:25 UTC by TomaszGaweda

GenericMapStore init creates mapping, resolves fields etc. and has just 5 second to do that. For some tests we use H2 Mem database, which will be up after the first call is made. This means that H2 startup time was added to GenericMapStore init's startup time. In some cases like overloaded Jenkins, this may cause init to fail.

In this change I'm explicitly initializing connection to test databases, so that slow startup in case of overload won't affect GenericMapStore's init (at least, not that much)

Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [x] Label `Add to Release Notes` or `Not Release Notes content` set
- [ ] Request reviewers if possible

2022-11-17 17:53 UTC, TomaszGaweda commented
run-lab-run

2022-11-17 17:55 UTC, TomaszGaweda commented
run-with-jdk17

2022-11-17 17:55 UTC, TomaszGaweda commented
run-with-ibm-jdk-8

2022-11-17 18:10 UTC, TomaszGaweda commented
run-with-jdk17

2022-11-17 19:07 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder-jdk17` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder-jdk17/35/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder-jdk17/35/Hazelcast-pr-builder-jdk17-35.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option --illegal-access=deny; support was removed in 17.0
--------------------------
[ERROR] Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option --illegal-access=deny; support was removed in 17.0
--------------------------
</pre>
</details>

2022-11-17 21:57 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder-with-ibm-jdk-8` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder-with-ibm-jdk-8/6/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder-with-ibm-jdk-8/6/Hazelcast-pr-builder-with-ibm-jdk-8-6.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>

</pre>
</details>

2022-11-18 09:41 UTC, TomaszGaweda commented
Both failed jobs failed due to errors in non-related tests.

2022-11-18 09:41 UTC, TomaszGaweda commented
run-with-jdk17  run-with-ibm-jdk-8 run-lab-run

2022-11-18 09:42 UTC, TomaszGaweda commented
run-lab-run

2022-11-18 09:42 UTC, TomaszGaweda commented
run-with-jdk17

2022-11-18 09:42 UTC, TomaszGaweda commented
run-with-ibm-jdk-8

2022-11-18 13:44 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder-with-ibm-jdk-8` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder-with-ibm-jdk-8/7/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder-with-ibm-jdk-8/7/Hazelcast-pr-builder-with-ibm-jdk-8-7.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>

</pre>
</details>

2022-11-18 15:27 UTC, TomaszGaweda commented
IBM errors are not related as well

2022-11-18 16:27 UTC, TomaszGaweda commented
with-ibm-jdk-8

2022-11-18 16:27 UTC, TomaszGaweda commented
run-with-ibm-jdk-8

2022-11-18 20:30 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder-with-ibm-jdk-8` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder-with-ibm-jdk-8/8/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder-with-ibm-jdk-8/8/Hazelcast-pr-builder-with-ibm-jdk-8-8.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>

</pre>
</details>

2022-11-21 11:17 UTC, TomaszGaweda commented
run-with-ibm-jdk-8

2022-11-21 11:42 UTC, ldziedziul commented on hazelcast/src/test/java/com/hazelcast/test/jdbc/PostgresDatabaseProvider.java
> +    private void waitForDb() {
Maybe move `waitForDb` to `TestDatabaseProvider` ?

2022-11-21 15:19 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder-with-ibm-jdk-8` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder-with-ibm-jdk-8/10/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder-with-ibm-jdk-8/10/Hazelcast-pr-builder-with-ibm-jdk-8-10.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>

</pre>
</details>

2022-11-21 18:37 UTC, ldziedziul approved these changes

2022-11-22 12:13 UTC, frant-hartm requested changes

2022-11-22 12:13 UTC, frant-hartm commented on hazelcast/src/test/java/com/hazelcast/test/jdbc/MySQLDatabaseProvider.java
> +    private static final int LOGIN_TIMEOUT = 5;
This is short - it might be downloading a docker image, we should allow something much longer - 120 s maybe.

2022-11-22 12:13 UTC, frant-hartm commented on hazelcast/src/test/java/com/hazelcast/test/jdbc/PostgresDatabaseProvider.java
> +    private static final int LOGIN_TIMEOUT = 5;
Same here.

2022-11-22 12:45 UTC, orcunc commented
I think it is better to initialize the Hikari Connection pool if possible. This way the DB will be created and connection pool will be populated

2022-11-22 12:52 UTC, TomaszGaweda commented on hazelcast/src/test/java/com/hazelcast/test/jdbc/PostgresDatabaseProvider.java
> +    private static final int LOGIN_TIMEOUT = 5;
Good idea, I've changed to 120

2022-11-22 12:53 UTC, TomaszGaweda commented
I'd agree in general, but for tests I think we prefer to have as strong isolation as possible, that's why it's not pooled

2022-11-22 13:14 UTC, frant-hartm approved these changes

2022-11-22 14:16 UTC, merged