Peel should also peel JetExceptions
hazelcast/hazelcast pull request #22889
Opened 2022-11-18 16:49 UTC by TomaszGaweda

If processor throw JetException with a non-serializable cause, then the result cannot be send - `peel` method doesn't see HazecastSerializationException due to JetException not being included in the definition.

See https://github.com/hazelcast/hazelcast/pull/22497/files#r996878225

Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [x] Label `Add to Release Notes` or `Not Release Notes content` set
- [ ] Request reviewers if possible
- [ ] Send backports/forwardports if fix needs to be applied to past/future releases

2022-11-18 16:53 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/14362/Hazelcast-pr-builder-14362.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/14362/Hazelcast-pr-builder-14362.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.2.0:checkstyle (default) on project hazelcast: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There are 2 errors reported by Checkstyle 8.38 with /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/checkstyle/checkstyle.xml ruleset. -> [Help 1]
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/jet/impl/util/ExceptionUtil.java:113:9: Boolean expression complexity is 5 (max allowed is 4). [BooleanExpressionComplexity]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/test/java/com/hazelcast/jet/impl/util/ExceptionUtilTest.java:65:48: '{' at column 48 should have line break after. [LeftCurly]
--------------------------
</pre>
</details>

2022-11-21 10:49 UTC, TomaszGaweda commented
run-lab-run

2022-11-21 14:18 UTC, hz-devops-test commented
The job `Hazelcast-pr-EE-compiler` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-EE-compiler/3437/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-EE-compiler/3437/Hazelcast-pr-EE-compiler-3437.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>

</pre>
</details>

2022-11-21 14:20 UTC, TomaszGaweda commented on hazelcast/src/main/java/com/hazelcast/jet/impl/util/ExceptionUtil.java
> +        factory.register(JET_EXCEPTIONS_RANGE_START, JetException.class, JetException::new);
6 lines vs 11 with same readability and no warnings produced by compiler... I think it should be ok to include simple boyscout, WDYT?

2022-11-21 14:23 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/14385/Hazelcast-pr-builder-14385.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/14385/Hazelcast-pr-builder-14385.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.2.0:checkstyle (default) on project hazelcast: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There are 2 errors reported by Checkstyle 8.38 with /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/checkstyle/checkstyle.xml ruleset. -> [Help 1]
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/jet/impl/util/ExceptionUtil.java:89:55: '4' is a magic number. [MagicNumber]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/jet/impl/util/ExceptionUtil.java:90:55: '5' is a magic number. [MagicNumber]
--------------------------
</pre>
</details>

2022-11-21 15:50 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/14386/Hazelcast-pr-builder-14386.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/14386/Hazelcast-pr-builder-14386.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ExceptionUtilTest.when_throwableIsJetExceptionWithNonNullCause_then_returnCause:81 expected:<[oh no]> but was:<[here stacktrace]>
[INFO] 
[ERROR] Tests run: 50912, Failures: 1, Errors: 0, Skipped: 238
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2022-11-21 16:03 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/14390/Hazelcast-pr-builder-14390.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/14390/Hazelcast-pr-builder-14390.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.2.0:checkstyle (default) on project hazelcast: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There is 1 error reported by Checkstyle 8.38 with /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/checkstyle/checkstyle.xml ruleset. -> [Help 1]
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/test/java/com/hazelcast/jet/impl/util/ExceptionUtilTest.java:24:8: Unused import - com.hazelcast.nio.serialization.HazelcastSerializationException. [UnusedImports]
--------------------------
</pre>
</details>

2022-11-22 11:00 UTC, TomaszGaweda commented
run-nightly-tests

2022-11-22 11:27 UTC, ramizdundar approved these changes

2022-11-22 11:27 UTC, ramizdundar commented on hazelcast/src/main/java/com/hazelcast/jet/impl/util/ExceptionUtil.java
> +        factory.register(id, JetDisabledException.class, JetDisabledException::new);
nit:
```suggestion
        factory.register(id++, JetDisabledException.class, JetDisabledException::new);
```

2022-11-22 11:35 UTC, ramizdundar commented on hazelcast/src/main/java/com/hazelcast/jet/impl/util/ExceptionUtil.java
> +        factory.register(id, JetDisabledException.class, JetDisabledException::new);
ah, unlucky, ok

2022-11-22 12:48 UTC, frant-hartm requested changes
I applaud the effort to improve the state, but we need a test :-)

2022-11-22 12:48 UTC, frant-hartm commented on hazelcast/src/main/java/com/hazelcast/jet/impl/operation/AsyncOperation.java
> +                if (value instanceof Throwable && isOrHasCause(ex, HazelcastSerializationException.class)) {
Could you please explain how we get a nested `HazelcastSerializationException`. Note that this exception is from `sendResponse`.

2022-12-06 06:55 UTC, orcunc approved these changes

2023-01-24 17:38 UTC, closed without merging