Use Hazelcast version in the protocol definitions
hazelcast/hazelcast pull request #23039
Opened 2022-12-01 13:40 UTC by mdumandag

We were using the separate protocol version in the since values
of the protocol definitions, but that was causing a quite bit
of confusion.

We have decided to stick to the Hazelcast versions to make it simpler.

This PR updates the auto-generated test files with the changes
done on the protocol side and updates the since versions used in
the `LongRegister`.

protocol PR: https://github.com/hazelcast/hazelcast-client-protocol/pull/444

2022-12-01 17:00 UTC, srknzl approved these changes

2022-12-16 14:18 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/14912/Hazelcast-pr-builder-14912.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/14912/Hazelcast-pr-builder-14912.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>

</pre>
</details>

2022-12-16 17:24 UTC, mdumandag commented
run-lab-run

2023-09-20 13:46 UTC, devOpsHazelcast commented
Can one of the admins verify this patch?

2023-09-20 13:46 UTC, devOpsHazelcast commented
Can one of the admins verify this patch?

2023-09-20 13:50 UTC, hz-devops-test commented
The job `Hazelcast-pr-compiler` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-compiler/9961/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-compiler/9961/Hazelcast-pr-compiler-9961.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] COMPILATION ERROR : 
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/ClientCompatibilityNullTest_2_7.java:[51,8] class ClientCompatibilityNullTest_5_4 is public, should be declared in a file named ClientCompatibilityNullTest_5_4.java
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] COMPILATION ERROR : 
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/ClientCompatibilityNullTest_2_7.java:[51,8] class ClientCompatibilityNullTest_5_4 is public, should be declared in a file named ClientCompatibilityNullTest_5_4.java
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/ClientCompatibilityTest_5_3.java:[5913,63] method encodeRequest in class com.hazelcast.client.impl.protocol.codec.DynamicConfigAddMapConfigCodec cannot be applied to given types;
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/ClientCompatibilityTest_5_3.java:[5978,33] cannot find symbol
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:testCompile (default-testCompile) on project hazelcast: Compilation failure: Compilation failure: 
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/ClientCompatibilityNullTest_2_7.java:[51,8] class ClientCompatibilityNullTest_5_4 is public, should be declared in a file named ClientCompatibilityNullTest_5_4.java
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/ClientCompatibilityTest_5_3.java:[5913,63] method encodeRequest in class com.hazelcast.client.impl.protocol.codec.DynamicConfigAddMapConfigCodec cannot be applied to given types;
--------------------------
[ERROR]   required: java.lang.String,int,int,int,int,com.hazelcast.client.impl.protocol.task.dynamicconfig.EvictionConfigHolder,boolean,java.lang.String,java.lang.String,int,java.lang.String,java.util.Collection<com.hazelcast.client.impl.protocol.task.dynamicconfig.ListenerConfigHolder>,java.util.Collection<com.hazelcast.client.impl.protocol.task.dynamicconfig.ListenerConfigHolder>,boolean,java.lang.String,com.hazelcast.client.impl.protocol.task.dynamicconfig.MapStoreConfigHolder,com.hazelcast.client.impl.protocol.task.dynamicconfig.NearCacheConfigHolder,com.hazelcast.config.WanReplicationRef,java.util.Collection<com.hazelcast.config.IndexConfig>,java.util.Collection<com.hazelcast.config.AttributeConfig>,java.util.Collection<com.hazelcast.client.impl.protocol.task.dynamicconfig.QueryCacheConfigHolder>,java.lang.String,com.hazelcast.internal.serialization.Data,com.hazelcast.config.HotRestartConfig,com.hazelcast.config.EventJournalConfig,com.hazelcast.config.MerkleTreeConfig,int,boolean,com.hazelcast.config.DataPersistenceConfig,com.hazelcast.config.TieredStoreConfig,java.util.Collection<com.hazelcast.config.PartitioningAttributeConfig>
--------------------------
[ERROR]   found: java.lang.String,int,int,int,int,com.hazelcast.client.impl.protocol.task.dynamicconfig.EvictionConfigHolder,boolean,java.lang.String,java.lang.String,int,java.lang.String,java.util.List<com.hazelcast.client.impl.protocol.task.dynamicconfig.ListenerConfigHolder>,java.util.List<com.hazelcast.client.impl.protocol.task.dynamicconfig.ListenerConfigHolder>,boolean,java.lang.String,com.hazelcast.client.impl.protocol.task.dynamicconfig.MapStoreConfigHolder,com.hazelcast.client.impl.protocol.task.dynamicconfig.NearCacheConfigHolder,com.hazelcast.config.WanReplicationRef,java.util.List<com.hazelcast.config.IndexConfig>,java.util.List<com.hazelcast.config.AttributeConfig>,java.util.List<com.hazelcast.client.impl.protocol.task.dynamicconfig.QueryCacheConfigHolder>,java.lang.String,com.hazelcast.internal.serialization.Data,com.hazelcast.config.HotRestartConfig,com.hazelcast.config.EventJournalConfig,com.hazelcast.config.MerkleTreeConfig,int,boolean,com.hazelcast.config.DataPersistenceConfig,com.hazelcast.config.TieredStoreConfig
--------------------------
[ERROR]   reason: actual and formal argument lists differ in length
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/ClientCompatibilityTest_5_3.java:[5978,33] cannot find symbol
--------------------------
[ERROR]   symbol:   variable DynamicConfigAddExternalDataStoreConfigCodec
--------------------------
[ERROR]   location: class com.hazelcast.client.protocol.compatibility.ClientCompatibilityTest_5_3
--------------------------
[ERROR] -> [Help 1]
--------------------------
[ERROR] 
--------------------------
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
--------------------------
[ERROR] 
--------------------------
[ERROR] For more information about the errors and possible solutions, please read the following articles:
--------------------------
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
--------------------------
[ERROR] 
--------------------------
[ERROR] After correcting the problems, you can resume the build with the command
--------------------------
[ERROR]   mvn <args> -rf :hazelcast
--------------------------
</pre>
</details>

2023-09-20 13:50 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/20638/Hazelcast-pr-builder-20638.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/20638/Hazelcast-pr-builder-20638.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] COMPILATION ERROR : 
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/ClientCompatibilityNullTest_2_7.java:[51,8] class ClientCompatibilityNullTest_5_4 is public, should be declared in a file named ClientCompatibilityNullTest_5_4.java
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] COMPILATION ERROR : 
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/ClientCompatibilityNullTest_2_7.java:[51,8] class ClientCompatibilityNullTest_5_4 is public, should be declared in a file named ClientCompatibilityNullTest_5_4.java
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/ClientCompatibilityTest_5_3.java:[5913,63] method encodeRequest in class com.hazelcast.client.impl.protocol.codec.DynamicConfigAddMapConfigCodec cannot be applied to given types;
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/ClientCompatibilityTest_5_3.java:[5978,33] cannot find symbol
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:testCompile (default-testCompile) on project hazelcast: Compilation failure: Compilation failure: 
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/ClientCompatibilityNullTest_2_7.java:[51,8] class ClientCompatibilityNullTest_5_4 is public, should be declared in a file named ClientCompatibilityNullTest_5_4.java
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/ClientCompatibilityTest_5_3.java:[5913,63] method encodeRequest in class com.hazelcast.client.impl.protocol.codec.DynamicConfigAddMapConfigCodec cannot be applied to given types;
--------------------------
[ERROR]   required: java.lang.String,int,int,int,int,com.hazelcast.client.impl.protocol.task.dynamicconfig.EvictionConfigHolder,boolean,java.lang.String,java.lang.String,int,java.lang.String,java.util.Collection<com.hazelcast.client.impl.protocol.task.dynamicconfig.ListenerConfigHolder>,java.util.Collection<com.hazelcast.client.impl.protocol.task.dynamicconfig.ListenerConfigHolder>,boolean,java.lang.String,com.hazelcast.client.impl.protocol.task.dynamicconfig.MapStoreConfigHolder,com.hazelcast.client.impl.protocol.task.dynamicconfig.NearCacheConfigHolder,com.hazelcast.config.WanReplicationRef,java.util.Collection<com.hazelcast.config.IndexConfig>,java.util.Collection<com.hazelcast.config.AttributeConfig>,java.util.Collection<com.hazelcast.client.impl.protocol.task.dynamicconfig.QueryCacheConfigHolder>,java.lang.String,com.hazelcast.internal.serialization.Data,com.hazelcast.config.HotRestartConfig,com.hazelcast.config.EventJournalConfig,com.hazelcast.config.MerkleTreeConfig,int,boolean,com.hazelcast.config.DataPersistenceConfig,com.hazelcast.config.TieredStoreConfig,java.util.Collection<com.hazelcast.config.PartitioningAttributeConfig>
--------------------------
[ERROR]   found: java.lang.String,int,int,int,int,com.hazelcast.client.impl.protocol.task.dynamicconfig.EvictionConfigHolder,boolean,java.lang.String,java.lang.String,int,java.lang.String,java.util.List<com.hazelcast.client.impl.protocol.task.dynamicconfig.ListenerConfigHolder>,java.util.List<com.hazelcast.client.impl.protocol.task.dynamicconfig.ListenerConfigHolder>,boolean,java.lang.String,com.hazelcast.client.impl.protocol.task.dynamicconfig.MapStoreConfigHolder,com.hazelcast.client.impl.protocol.task.dynamicconfig.NearCacheConfigHolder,com.hazelcast.config.WanReplicationRef,java.util.List<com.hazelcast.config.IndexConfig>,java.util.List<com.hazelcast.config.AttributeConfig>,java.util.List<com.hazelcast.client.impl.protocol.task.dynamicconfig.QueryCacheConfigHolder>,java.lang.String,com.hazelcast.internal.serialization.Data,com.hazelcast.config.HotRestartConfig,com.hazelcast.config.EventJournalConfig,com.hazelcast.config.MerkleTreeConfig,int,boolean,com.hazelcast.config.DataPersistenceConfig,com.hazelcast.config.TieredStoreConfig
--------------------------
[ERROR]   reason: actual and formal argument lists differ in length
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/ClientCompatibilityTest_5_3.java:[5978,33] cannot find symbol
--------------------------
[ERROR]   symbol:   variable DynamicConfigAddExternalDataStoreConfigCodec
--------------------------
[ERROR]   location: class com.hazelcast.client.protocol.compatibility.ClientCompatibilityTest_5_3
--------------------------
[ERROR] -> [Help 1]
--------------------------
[ERROR] 
--------------------------
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
--------------------------
[ERROR] 
--------------------------
[ERROR] For more information about the errors and possible solutions, please read the following articles:
--------------------------
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
--------------------------
[ERROR] 
--------------------------
[ERROR] After correcting the problems, you can resume the build with the command
--------------------------
[ERROR]   mvn <args> -rf :hazelcast
--------------------------
</pre>
</details>

2023-09-20 13:51 UTC, hz-devops-test commented
The job `Hazelcast-pr-EE-compiler` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-EE-compiler/9380/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-EE-compiler/9380/Hazelcast-pr-EE-compiler-9380.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] COMPILATION ERROR : 
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/ClientCompatibilityNullTest_2_7.java:[51,8] class ClientCompatibilityNullTest_5_4 is public, should be declared in a file named ClientCompatibilityNullTest_5_4.java
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] COMPILATION ERROR : 
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/ClientCompatibilityNullTest_2_7.java:[51,8] class ClientCompatibilityNullTest_5_4 is public, should be declared in a file named ClientCompatibilityNullTest_5_4.java
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/ClientCompatibilityTest_5_3.java:[5913,63] method encodeRequest in class com.hazelcast.client.impl.protocol.codec.DynamicConfigAddMapConfigCodec cannot be applied to given types;
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/ClientCompatibilityTest_5_3.java:[5978,33] cannot find symbol
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:testCompile (default-testCompile) on project hazelcast: Compilation failure: Compilation failure: 
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/ClientCompatibilityNullTest_2_7.java:[51,8] class ClientCompatibilityNullTest_5_4 is public, should be declared in a file named ClientCompatibilityNullTest_5_4.java
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/ClientCompatibilityTest_5_3.java:[5913,63] method encodeRequest in class com.hazelcast.client.impl.protocol.codec.DynamicConfigAddMapConfigCodec cannot be applied to given types;
--------------------------
[ERROR]   required: java.lang.String,int,int,int,int,com.hazelcast.client.impl.protocol.task.dynamicconfig.EvictionConfigHolder,boolean,java.lang.String,java.lang.String,int,java.lang.String,java.util.Collection<com.hazelcast.client.impl.protocol.task.dynamicconfig.ListenerConfigHolder>,java.util.Collection<com.hazelcast.client.impl.protocol.task.dynamicconfig.ListenerConfigHolder>,boolean,java.lang.String,com.hazelcast.client.impl.protocol.task.dynamicconfig.MapStoreConfigHolder,com.hazelcast.client.impl.protocol.task.dynamicconfig.NearCacheConfigHolder,com.hazelcast.config.WanReplicationRef,java.util.Collection<com.hazelcast.config.IndexConfig>,java.util.Collection<com.hazelcast.config.AttributeConfig>,java.util.Collection<com.hazelcast.client.impl.protocol.task.dynamicconfig.QueryCacheConfigHolder>,java.lang.String,com.hazelcast.internal.serialization.Data,com.hazelcast.config.HotRestartConfig,com.hazelcast.config.EventJournalConfig,com.hazelcast.config.MerkleTreeConfig,int,boolean,com.hazelcast.config.DataPersistenceConfig,com.hazelcast.config.TieredStoreConfig,java.util.Collection<com.hazelcast.config.PartitioningAttributeConfig>
--------------------------
[ERROR]   found: java.lang.String,int,int,int,int,com.hazelcast.client.impl.protocol.task.dynamicconfig.EvictionConfigHolder,boolean,java.lang.String,java.lang.String,int,java.lang.String,java.util.List<com.hazelcast.client.impl.protocol.task.dynamicconfig.ListenerConfigHolder>,java.util.List<com.hazelcast.client.impl.protocol.task.dynamicconfig.ListenerConfigHolder>,boolean,java.lang.String,com.hazelcast.client.impl.protocol.task.dynamicconfig.MapStoreConfigHolder,com.hazelcast.client.impl.protocol.task.dynamicconfig.NearCacheConfigHolder,com.hazelcast.config.WanReplicationRef,java.util.List<com.hazelcast.config.IndexConfig>,java.util.List<com.hazelcast.config.AttributeConfig>,java.util.List<com.hazelcast.client.impl.protocol.task.dynamicconfig.QueryCacheConfigHolder>,java.lang.String,com.hazelcast.internal.serialization.Data,com.hazelcast.config.HotRestartConfig,com.hazelcast.config.EventJournalConfig,com.hazelcast.config.MerkleTreeConfig,int,boolean,com.hazelcast.config.DataPersistenceConfig,com.hazelcast.config.TieredStoreConfig
--------------------------
[ERROR]   reason: actual and formal argument lists differ in length
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/ClientCompatibilityTest_5_3.java:[5978,33] cannot find symbol
--------------------------
[ERROR]   symbol:   variable DynamicConfigAddExternalDataStoreConfigCodec
--------------------------
[ERROR]   location: class com.hazelcast.client.protocol.compatibility.ClientCompatibilityTest_5_3
--------------------------
[ERROR] -> [Help 1]
--------------------------
[ERROR] 
--------------------------
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
--------------------------
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
--------------------------
[ERROR] 
--------------------------
[ERROR] For more information about the errors and possible solutions, please read the following articles:
--------------------------
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
--------------------------
[ERROR] 
--------------------------
[ERROR] After correcting the problems, you can resume the build with the command
--------------------------
[ERROR]   mvn <args> -rf :hazelcast
--------------------------
</pre>
</details>

2023-09-20 13:57 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/20639/Hazelcast-pr-builder-20639.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/20639/Hazelcast-pr-builder-20639.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] COMPILATION ERROR : 
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/ClientCompatibilityTest_5_3.java:[5913,63] method encodeRequest in class com.hazelcast.client.impl.protocol.codec.DynamicConfigAddMapConfigCodec cannot be applied to given types;
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] COMPILATION ERROR : 
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/ClientCompatibilityTest_5_3.java:[5913,63] method encodeRequest in class com.hazelcast.client.impl.protocol.codec.DynamicConfigAddMapConfigCodec cannot be applied to given types;
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/ClientCompatibilityTest_5_3.java:[5978,33] cannot find symbol
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:testCompile (default-testCompile) on project hazelcast: Compilation failure: Compilation failure: 
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/ClientCompatibilityTest_5_3.java:[5913,63] method encodeRequest in class com.hazelcast.client.impl.protocol.codec.DynamicConfigAddMapConfigCodec cannot be applied to given types;
--------------------------
[ERROR]   required: java.lang.String,int,int,int,int,com.hazelcast.client.impl.protocol.task.dynamicconfig.EvictionConfigHolder,boolean,java.lang.String,java.lang.String,int,java.lang.String,java.util.Collection<com.hazelcast.client.impl.protocol.task.dynamicconfig.ListenerConfigHolder>,java.util.Collection<com.hazelcast.client.impl.protocol.task.dynamicconfig.ListenerConfigHolder>,boolean,java.lang.String,com.hazelcast.client.impl.protocol.task.dynamicconfig.MapStoreConfigHolder,com.hazelcast.client.impl.protocol.task.dynamicconfig.NearCacheConfigHolder,com.hazelcast.config.WanReplicationRef,java.util.Collection<com.hazelcast.config.IndexConfig>,java.util.Collection<com.hazelcast.config.AttributeConfig>,java.util.Collection<com.hazelcast.client.impl.protocol.task.dynamicconfig.QueryCacheConfigHolder>,java.lang.String,com.hazelcast.internal.serialization.Data,com.hazelcast.config.HotRestartConfig,com.hazelcast.config.EventJournalConfig,com.hazelcast.config.MerkleTreeConfig,int,boolean,com.hazelcast.config.DataPersistenceConfig,com.hazelcast.config.TieredStoreConfig,java.util.Collection<com.hazelcast.config.PartitioningAttributeConfig>
--------------------------
[ERROR]   found: java.lang.String,int,int,int,int,com.hazelcast.client.impl.protocol.task.dynamicconfig.EvictionConfigHolder,boolean,java.lang.String,java.lang.String,int,java.lang.String,java.util.List<com.hazelcast.client.impl.protocol.task.dynamicconfig.ListenerConfigHolder>,java.util.List<com.hazelcast.client.impl.protocol.task.dynamicconfig.ListenerConfigHolder>,boolean,java.lang.String,com.hazelcast.client.impl.protocol.task.dynamicconfig.MapStoreConfigHolder,com.hazelcast.client.impl.protocol.task.dynamicconfig.NearCacheConfigHolder,com.hazelcast.config.WanReplicationRef,java.util.List<com.hazelcast.config.IndexConfig>,java.util.List<com.hazelcast.config.AttributeConfig>,java.util.List<com.hazelcast.client.impl.protocol.task.dynamicconfig.QueryCacheConfigHolder>,java.lang.String,com.hazelcast.internal.serialization.Data,com.hazelcast.config.HotRestartConfig,com.hazelcast.config.EventJournalConfig,com.hazelcast.config.MerkleTreeConfig,int,boolean,com.hazelcast.config.DataPersistenceConfig,com.hazelcast.config.TieredStoreConfig
--------------------------
[ERROR]   reason: actual and formal argument lists differ in length
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/ClientCompatibilityTest_5_3.java:[5978,33] cannot find symbol
--------------------------
[ERROR]   symbol:   variable DynamicConfigAddExternalDataStoreConfigCodec
--------------------------
[ERROR]   location: class com.hazelcast.client.protocol.compatibility.ClientCompatibilityTest_5_3
--------------------------
[ERROR] -> [Help 1]
--------------------------
[ERROR] 
--------------------------
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
--------------------------
[ERROR] 
--------------------------
[ERROR] For more information about the errors and possible solutions, please read the following articles:
--------------------------
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
--------------------------
[ERROR] 
--------------------------
[ERROR] After correcting the problems, you can resume the build with the command
--------------------------
[ERROR]   mvn <args> -rf :hazelcast
--------------------------
</pre>
</details>

2023-09-20 13:58 UTC, hz-devops-test commented
The job `Hazelcast-pr-compiler` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-compiler/9962/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-compiler/9962/Hazelcast-pr-compiler-9962.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] COMPILATION ERROR : 
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/ClientCompatibilityTest_5_3.java:[5913,63] method encodeRequest in class com.hazelcast.client.impl.protocol.codec.DynamicConfigAddMapConfigCodec cannot be applied to given types;
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] COMPILATION ERROR : 
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/ClientCompatibilityTest_5_3.java:[5913,63] method encodeRequest in class com.hazelcast.client.impl.protocol.codec.DynamicConfigAddMapConfigCodec cannot be applied to given types;
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/ClientCompatibilityTest_5_3.java:[5978,33] cannot find symbol
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:testCompile (default-testCompile) on project hazelcast: Compilation failure: Compilation failure: 
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/ClientCompatibilityTest_5_3.java:[5913,63] method encodeRequest in class com.hazelcast.client.impl.protocol.codec.DynamicConfigAddMapConfigCodec cannot be applied to given types;
--------------------------
[ERROR]   required: java.lang.String,int,int,int,int,com.hazelcast.client.impl.protocol.task.dynamicconfig.EvictionConfigHolder,boolean,java.lang.String,java.lang.String,int,java.lang.String,java.util.Collection<com.hazelcast.client.impl.protocol.task.dynamicconfig.ListenerConfigHolder>,java.util.Collection<com.hazelcast.client.impl.protocol.task.dynamicconfig.ListenerConfigHolder>,boolean,java.lang.String,com.hazelcast.client.impl.protocol.task.dynamicconfig.MapStoreConfigHolder,com.hazelcast.client.impl.protocol.task.dynamicconfig.NearCacheConfigHolder,com.hazelcast.config.WanReplicationRef,java.util.Collection<com.hazelcast.config.IndexConfig>,java.util.Collection<com.hazelcast.config.AttributeConfig>,java.util.Collection<com.hazelcast.client.impl.protocol.task.dynamicconfig.QueryCacheConfigHolder>,java.lang.String,com.hazelcast.internal.serialization.Data,com.hazelcast.config.HotRestartConfig,com.hazelcast.config.EventJournalConfig,com.hazelcast.config.MerkleTreeConfig,int,boolean,com.hazelcast.config.DataPersistenceConfig,com.hazelcast.config.TieredStoreConfig,java.util.Collection<com.hazelcast.config.PartitioningAttributeConfig>
--------------------------
[ERROR]   found: java.lang.String,int,int,int,int,com.hazelcast.client.impl.protocol.task.dynamicconfig.EvictionConfigHolder,boolean,java.lang.String,java.lang.String,int,java.lang.String,java.util.List<com.hazelcast.client.impl.protocol.task.dynamicconfig.ListenerConfigHolder>,java.util.List<com.hazelcast.client.impl.protocol.task.dynamicconfig.ListenerConfigHolder>,boolean,java.lang.String,com.hazelcast.client.impl.protocol.task.dynamicconfig.MapStoreConfigHolder,com.hazelcast.client.impl.protocol.task.dynamicconfig.NearCacheConfigHolder,com.hazelcast.config.WanReplicationRef,java.util.List<com.hazelcast.config.IndexConfig>,java.util.List<com.hazelcast.config.AttributeConfig>,java.util.List<com.hazelcast.client.impl.protocol.task.dynamicconfig.QueryCacheConfigHolder>,java.lang.String,com.hazelcast.internal.serialization.Data,com.hazelcast.config.HotRestartConfig,com.hazelcast.config.EventJournalConfig,com.hazelcast.config.MerkleTreeConfig,int,boolean,com.hazelcast.config.DataPersistenceConfig,com.hazelcast.config.TieredStoreConfig
--------------------------
[ERROR]   reason: actual and formal argument lists differ in length
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/ClientCompatibilityTest_5_3.java:[5978,33] cannot find symbol
--------------------------
[ERROR]   symbol:   variable DynamicConfigAddExternalDataStoreConfigCodec
--------------------------
[ERROR]   location: class com.hazelcast.client.protocol.compatibility.ClientCompatibilityTest_5_3
--------------------------
[ERROR] -> [Help 1]
--------------------------
[ERROR] 
--------------------------
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
--------------------------
[ERROR] 
--------------------------
[ERROR] For more information about the errors and possible solutions, please read the following articles:
--------------------------
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
--------------------------
[ERROR] 
--------------------------
[ERROR] After correcting the problems, you can resume the build with the command
--------------------------
[ERROR]   mvn <args> -rf :hazelcast
--------------------------
</pre>
</details>

2023-09-21 23:16 UTC, srknzl commented on hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/ClientCompatibilityTest_5_3.java
This is interesting, should not we have 5.3 test already?

2023-09-21 23:18 UTC, srknzl commented on hazelcast/src/test/java/com/hazelcast/client/protocol/compatibility/ClientCompatibilityTest_5_3.java
We have ClientCompatibilityTest_2_6 already in master

2023-09-21 23:19 UTC, srknzl requested changes
looks good except a comment

2023-12-22 00:59 UTC, closed without merging

2023-12-22 00:59 UTC, devOpsHazelcast commented
PR closed by Hazelcast automation as no activity (>3 months). Please reopen with comments, if necessary. Thank you for using Hazelcast and your valuable contributions