Pass assertion arguments in the correct order [HZ-1911]
hazelcast/hazelcast pull request #23389
Opened 2023-01-13 11:49 UTC by Patras3

WIP - cleaning up sonar issues

INSERT_PR_DESCRIPTION_HERE

Fixes INSERT_LINK_TO_THE_ISSUE_HERE

Backport of: INSERT_LINK_TO_THE_ORIGINAL_PR_HERE

EE PR: INSERT_LINK_TO_THE_EE_PR_HERE

Breaking changes (list specific methods/types/messages):
* API
* client protocol format
* serialized form
* snapshot format

Checklist:
- [ ] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [ ] Label `Add to Release Notes` or `Not Release Notes content` set
- [ ] Request reviewers if possible
- [ ] Send backports/forwardports if fix needs to be applied to past/future releases
- [ ] New public APIs have `@Nonnull/@Nullable` annotations
- [ ] New public APIs have `@since` tags in Javadoc

2023-01-14 21:59 UTC, viliam-durina approved these changes
I reviewed only the files in `sql` packages, thanks for the fix!

2023-01-16 07:11 UTC, olukas approved these changes

2023-01-16 07:13 UTC, kwart requested changes

2023-01-16 07:13 UTC, kwart commented on hazelcast/src/test/java/com/hazelcast/version/VersionUnknownTest.java
> +        assertNotEquals(UNKNOWN, ANY_VERSION);
This one should  be reverted as the original test is the expected one. See the `unknown_notEquals_to_any` for the other direction.
```suggestion
        assertNotEquals(ANY_VERSION, UNKNOWN);
```

2023-01-16 14:32 UTC, Patras3 commented on hazelcast/src/test/java/com/hazelcast/config/YamlConfigBuilderConfigResolutionTest.java
> +        assertEquals("YAML_ACCEPTED_SUFFIXES sequence", DeclarativeConfigUtil.YAML_ACCEPTED_SUFFIXES, YAML_ACCEPTED_SUFFIXES_SORTED);
Changed. Thx.

2023-01-17 07:28 UTC, kwart approved these changes

2023-01-17 09:24 UTC, merged