Split jar execution strategy for client and member
hazelcast/hazelcast pull request #23773
Opened 2023-02-28 10:07 UTC by orcunc

The jars executed by the client and member need to use different strategies. 
For the client
- The execute operation should be a synchronized method. Because the client needs to wait for the result of the execution and the state of the HazelcastBootstrap singleton must be preserved
For the member
- The execute operation should use a smaller synchronized block. Because the member does not need to wait for the result of 

Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [x] Label `Add to Release Notes` or `Not Release Notes content` set
- [x] Request reviewers if possible

2023-02-28 10:18 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/16575/Hazelcast-pr-builder-16575.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/16575/Hazelcast-pr-builder-16575.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] COMPILATION ERROR : 
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_2/hazelcast/src/main/java/com/hazelcast/instance/impl/executejar/ExecuteJarStrategyHelper.java:[22,35] com.hazelcast.instance.impl.MainMethodFinder is not public in com.hazelcast.instance.impl; cannot be accessed from outside package
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project hazelcast: Compilation failure
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_2/hazelcast/src/main/java/com/hazelcast/instance/impl/executejar/ExecuteJarStrategyHelper.java:[22,35] com.hazelcast.instance.impl.MainMethodFinder is not public in com.hazelcast.instance.impl; cannot be accessed from outside package
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_2/hazelcast/src/main/java/com/hazelcast/instance/impl/executejar/ExecuteJarStrategyHelper.java:[22,35] com.hazelcast.instance.impl.MainMethodFinder is not public in com.hazelcast.instance.impl; cannot be accessed from outside package
--------------------------
</pre>
</details>

2023-02-28 10:19 UTC, hz-devops-test commented
The job `Hazelcast-pr-EE-compiler` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-EE-compiler/5598/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-EE-compiler/5598/Hazelcast-pr-EE-compiler-5598.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] COMPILATION ERROR : 
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler_2/hazelcast/hazelcast/src/main/java/com/hazelcast/instance/impl/executejar/ExecuteJarStrategyHelper.java:[22,35] com.hazelcast.instance.impl.MainMethodFinder is not public in com.hazelcast.instance.impl; cannot be accessed from outside package
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project hazelcast: Compilation failure
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler_2/hazelcast/hazelcast/src/main/java/com/hazelcast/instance/impl/executejar/ExecuteJarStrategyHelper.java:[22,35] com.hazelcast.instance.impl.MainMethodFinder is not public in com.hazelcast.instance.impl; cannot be accessed from outside package
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler_2/hazelcast/hazelcast/src/main/java/com/hazelcast/instance/impl/executejar/ExecuteJarStrategyHelper.java:[22,35] com.hazelcast.instance.impl.MainMethodFinder is not public in com.hazelcast.instance.impl; cannot be accessed from outside package
--------------------------
</pre>
</details>

2023-02-28 10:22 UTC, hz-devops-test commented
The job `Hazelcast-pr-compiler` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-compiler/6211/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-compiler/6211/Hazelcast-pr-compiler-6211.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] COMPILATION ERROR : 
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler_2/hazelcast/src/main/java/com/hazelcast/instance/impl/executejar/ExecuteJarStrategyHelper.java:[22,35] com.hazelcast.instance.impl.MainMethodFinder is not public in com.hazelcast.instance.impl; cannot be accessed from outside package
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project hazelcast: Compilation failure
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler_2/hazelcast/src/main/java/com/hazelcast/instance/impl/executejar/ExecuteJarStrategyHelper.java:[22,35] com.hazelcast.instance.impl.MainMethodFinder is not public in com.hazelcast.instance.impl; cannot be accessed from outside package
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler_2/hazelcast/src/main/java/com/hazelcast/instance/impl/executejar/ExecuteJarStrategyHelper.java:[22,35] com.hazelcast.instance.impl.MainMethodFinder is not public in com.hazelcast.instance.impl; cannot be accessed from outside package
--------------------------
</pre>
</details>

2023-02-28 10:29 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/16579/Hazelcast-pr-builder-16579.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/16579/Hazelcast-pr-builder-16579.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] COMPILATION ERROR : 
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_2/hazelcast/src/main/java/com/hazelcast/instance/impl/executejar/ExecuteJarStrategyHelper.java:[22,35] com.hazelcast.instance.impl.MainMethodFinder is not public in com.hazelcast.instance.impl; cannot be accessed from outside package
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project hazelcast: Compilation failure
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_2/hazelcast/src/main/java/com/hazelcast/instance/impl/executejar/ExecuteJarStrategyHelper.java:[22,35] com.hazelcast.instance.impl.MainMethodFinder is not public in com.hazelcast.instance.impl; cannot be accessed from outside package
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_2/hazelcast/src/main/java/com/hazelcast/instance/impl/executejar/ExecuteJarStrategyHelper.java:[22,35] com.hazelcast.instance.impl.MainMethodFinder is not public in com.hazelcast.instance.impl; cannot be accessed from outside package
--------------------------
</pre>
</details>

2023-02-28 10:29 UTC, hz-devops-test commented
The job `Hazelcast-pr-EE-compiler` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-EE-compiler/5601/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-EE-compiler/5601/Hazelcast-pr-EE-compiler-5601.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] COMPILATION ERROR : 
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/hazelcast/src/main/java/com/hazelcast/instance/impl/executejar/ExecuteJarStrategyHelper.java:[22,35] com.hazelcast.instance.impl.MainMethodFinder is not public in com.hazelcast.instance.impl; cannot be accessed from outside package
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project hazelcast: Compilation failure
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/hazelcast/src/main/java/com/hazelcast/instance/impl/executejar/ExecuteJarStrategyHelper.java:[22,35] com.hazelcast.instance.impl.MainMethodFinder is not public in com.hazelcast.instance.impl; cannot be accessed from outside package
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/hazelcast/src/main/java/com/hazelcast/instance/impl/executejar/ExecuteJarStrategyHelper.java:[22,35] com.hazelcast.instance.impl.MainMethodFinder is not public in com.hazelcast.instance.impl; cannot be accessed from outside package
--------------------------
</pre>
</details>

2023-03-01 10:53 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/16617/Hazelcast-pr-builder-16617.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/16617/Hazelcast-pr-builder-16617.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.2.1:checkstyle (default) on project hazelcast: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There is 1 error reported by Checkstyle 8.38 with /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_3/checkstyle/checkstyle.xml ruleset. -> [Help 1]
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_3/hazelcast/src/main/java/com/hazelcast/jet/impl/jobupload/JobUploadStore.java:34:34: Name 'logger' must match pattern '^[A-Z][A-Z0-9]*(_[A-Z0-9]+)*$'. [ConstantName]
--------------------------
</pre>
</details>

2023-03-01 13:14 UTC, hz-devops-test commented
The job `Hazelcast-pr-EE-compiler` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-EE-compiler/5649/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-EE-compiler/5649/Hazelcast-pr-EE-compiler-5649.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal on project hazelcast-jet-kafka: Could not resolve dependencies for project com.hazelcast.jet:hazelcast-jet-kafka:jar:5.3.0-SNAPSHOT: Could not transfer artifact org.jetbrains:annotations:jar:17.0.0 from/to nexus-proxy (http://jenkins.hazelcast.com:8081/content/groups/public/): /home/jenkins/.m2/repository/org/jetbrains/annotations/17.0.0/annotations-17.0.0.jar.part (No such file or directory) -> [Help 1]
--------------------------
</pre>
</details>

2023-03-02 06:43 UTC, hz-devops-test commented
The job `Hazelcast-pr-EE-compiler` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-EE-compiler/5677/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-EE-compiler/5677/Hazelcast-pr-EE-compiler-5677.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal on project hazelcast-jet-kafka: Could not resolve dependencies for project com.hazelcast.jet:hazelcast-jet-kafka:jar:5.3.0-SNAPSHOT: Could not transfer artifact org.jetbrains:annotations:jar:17.0.0 from/to nexus-proxy (http://jenkins.hazelcast.com:8081/content/groups/public/): /home/jenkins/.m2/repository/org/jetbrains/annotations/17.0.0/annotations-17.0.0.jar.part (No such file or directory) -> [Help 1]
--------------------------
</pre>
</details>

2023-03-02 08:20 UTC, orcunc commented
run-sonar

2023-03-02 08:57 UTC, olukas requested changes
This PR doesn't fix https://github.com/hazelcast/hazelcast/issues/23664 at all. Main method is still executed in synchronized block. It still means that if something gets stuck in main method of submitted Jar then the whole jar upload is blocked forever (and cannot heal up until HZ node is restarted).

We have to be able to run more main methods from different jars at the same time.

(I haven't reviewed the rest of PR since this is something what needs to be reimplemented)

2023-03-02 16:39 UTC, TomaszGaweda commented on hazelcast/src/main/java/com/hazelcast/instance/impl/executejar/ClientExecuteJarStrategy.java
> +     * This method needs to be fully synchronized because it shuts down the remembered object
I don't understand why this mean that the method must be synchronized.

You can do `BootstrappedInstanceProxy instanceProxy = singleton.remembered();` before try block, then reference will be constant for this method - no need for any synchrionization

2023-03-03 11:35 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/16735/Hazelcast-pr-builder-16735.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/16735/Hazelcast-pr-builder-16735.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>

</pre>
</details>

2023-03-07 06:43 UTC, orcunc commented
> This PR doesn't fix #23664 at all. Main method is still executed in synchronized block. It still means that if something gets stuck in main method of submitted Jar then the whole jar upload is blocked forever (and cannot heal up until HZ node is restarted).
> 
> We have to be able to run more main methods from different jars at the same time.
> 
> (I haven't reviewed the rest of PR since this is something what needs to be reimplemented)

This is the link to the discussion in the slack channel
https://hazelcast.slack.com/archives/C04ERT4SLBC/p1677844095922569

So far no other suggestions. As I explained in the options, at least for now let's reduce the scope of the synchronized block. Yes @olukas you are right if something gets stuck, the thread will not be used anymore. But 
1. Only one thread will be lost. The member will still function with other threads. 
2. This is an internal API and the job submitting person should be careful not to submit dangerous jobs
3. I prefer to pass all parameters to the jar and not to store any state in the HazelcastBootsrap class. We can define a parameter convention for this. But all parties must agree on this. And so far no response.

2023-03-07 11:37 UTC, olukas commented
@orcunc 

> Only one thread will be lost. The member will still function with other threads.

if main method is run in synchronized block and it get stucks there that it's not true that it will be able to run in other threads. It will block forever due to synchronized block.

> This is an internal API and the job submitting person should be careful not to submit dangerous jobs

How do you define "dangerous jobs"? I guess that no user will think about it until it will get stuck on some day eventually (for example because it will read something from database which will be unreachable without configured timeout).

It's not related to public/private API - if we will have it in CLC and user can just send a jar by this feature then it's totally irrelevant it's private API.

> I prefer to pass all parameters to the jar and not to store any state in the HazelcastBootsrap class. We can define a parameter convention for this. But all parties must agree on this. And so far no response.

Implementation should be engineering decision and not QE decision. As a QE I can tell you what's wrong (i.e. if main method gets stuck it will make the feature not working forever) but I cannot tell you how to fix it.

2023-03-08 10:46 UTC, olukas approved these changes
**PLEASE DON'T TAKE THIS APPROVE AS REAL APPROVE.**

Setting as "approve" because I requested changes (but they will not be probably addressed by this PR) and it will not allow to merge until I set it as "approve" even if I would like remove myself from the reviewer list.

If https://github.com/hazelcast/hazelcast/issues/23664 would be addressed by this PR then please set me again as reviewer and I check whether it fixes the issue.

2023-03-08 12:28 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/16875/Hazelcast-pr-builder-16875.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/16875/Hazelcast-pr-builder-16875.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>

</pre>
</details>

2023-03-09 09:37 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/16953/Hazelcast-pr-builder-16953.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/16953/Hazelcast-pr-builder-16953.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>

</pre>
</details>

2023-03-16 14:33 UTC, closed without merging