Add support for changing JobConfig of a suspended job [HZ-1650]
hazelcast/hazelcast pull request #23862
Opened 2023-03-07 10:16 UTC by viliam-durina

Adds support for changing `JobConfig` of a suspended job.
Protocol changes: hazelcast/hazelcast-client-protocol#450

2023-03-07 10:20 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder-sql` of your PR failed. (Hazelcast internal details: [build log](
https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder-sql/115/Hazelcast-pr-builder-sql-115.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder-sql/115/Hazelcast-pr-builder-sql-115.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>

</pre>
</details>

2023-03-07 10:22 UTC, viliam-durina commented
run-lab-run

2023-03-07 10:36 UTC, frant-hartm approved these changes

2023-03-07 13:22 UTC, k-jamroz commented
we should add tests in EE that ensure that config can be changed in `SUSPENDED_EXPORTING_SNAPSHOT` state

2023-03-07 13:24 UTC, k-jamroz requested changes
need to restore check in `PlanExecutor.execute(CreateJobPlan plan, List<Object> arguments)` - for non streaming jobs (maybe with comment?) and it will be ok

2023-03-07 15:27 UTC, viliam-durina commented on hazelcast/src/main/java/com/hazelcast/jet/impl/client/protocol/task/JetUpdateJobConfigMessageTask.java
> +        return new String[] {ActionConstants.ACTION_RESTART};
That should be updated to:
>Suspend and resume a running job, change config options of a running job.

2023-03-07 17:03 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/16865/Hazelcast-pr-builder-16865.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/16865/Hazelcast-pr-builder-16865.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   SqlErrorTest.testMemberLeave:88->HazelcastTestSupport.assertInstanceOf:970 com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not active! is not an instanceof com.hazelcast.core.MemberLeftException
[INFO] 
[ERROR] Tests run: 5226, Failures: 1, Errors: 0, Skipped: 18
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2023-03-08 09:38 UTC, viliam-durina commented
run-lab-run

2023-03-08 16:14 UTC, mdumandag approved these changes

2023-03-09 08:03 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/16950/Hazelcast-pr-builder-16950.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/16950/Hazelcast-pr-builder-16950.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] COMPILATION ERROR : 
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_3/hazelcast/src/main/java/com/hazelcast/jet/impl/client/protocol/task/JetMessageTaskFactoryProvider.java:[75,34] cannot find symbol
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project hazelcast: Compilation failure: Compilation failure: 
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_3/hazelcast/src/main/java/com/hazelcast/jet/impl/client/protocol/task/JetMessageTaskFactoryProvider.java:[75,34] cannot find symbol
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_3/hazelcast/src/main/java/com/hazelcast/jet/impl/client/protocol/task/JetMessageTaskFactoryProvider.java:[75,44] cannot find symbol
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_3/hazelcast/src/main/java/com/hazelcast/jet/impl/client/protocol/task/JetMessageTaskFactoryProvider.java:[75,34] cannot find symbol
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_3/hazelcast/src/main/java/com/hazelcast/jet/impl/client/protocol/task/JetMessageTaskFactoryProvider.java:[75,44] cannot find symbol
--------------------------
</pre>
</details>

2023-03-09 08:03 UTC, hz-devops-test commented
The job `Hazelcast-pr-EE-compiler` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-EE-compiler/5956/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-EE-compiler/5956/Hazelcast-pr-EE-compiler-5956.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] COMPILATION ERROR : 
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/hazelcast/src/main/java/com/hazelcast/jet/impl/client/protocol/task/JetMessageTaskFactoryProvider.java:[75,34] cannot find symbol
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project hazelcast: Compilation failure: Compilation failure: 
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/hazelcast/src/main/java/com/hazelcast/jet/impl/client/protocol/task/JetMessageTaskFactoryProvider.java:[75,34] cannot find symbol
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/hazelcast/src/main/java/com/hazelcast/jet/impl/client/protocol/task/JetMessageTaskFactoryProvider.java:[75,44] cannot find symbol
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/hazelcast/src/main/java/com/hazelcast/jet/impl/client/protocol/task/JetMessageTaskFactoryProvider.java:[75,34] cannot find symbol
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/hazelcast/src/main/java/com/hazelcast/jet/impl/client/protocol/task/JetMessageTaskFactoryProvider.java:[75,44] cannot find symbol
--------------------------
</pre>
</details>

2023-03-09 08:04 UTC, hz-devops-test commented
The job `Hazelcast-pr-compiler` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-compiler/6567/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-compiler/6567/Hazelcast-pr-compiler-6567.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] COMPILATION ERROR : 
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/hazelcast/src/main/java/com/hazelcast/jet/impl/client/protocol/task/JetMessageTaskFactoryProvider.java:[75,34] cannot find symbol
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project hazelcast: Compilation failure: Compilation failure: 
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/hazelcast/src/main/java/com/hazelcast/jet/impl/client/protocol/task/JetMessageTaskFactoryProvider.java:[75,34] cannot find symbol
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/hazelcast/src/main/java/com/hazelcast/jet/impl/client/protocol/task/JetMessageTaskFactoryProvider.java:[75,44] cannot find symbol
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/hazelcast/src/main/java/com/hazelcast/jet/impl/client/protocol/task/JetMessageTaskFactoryProvider.java:[75,34] cannot find symbol
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/hazelcast/src/main/java/com/hazelcast/jet/impl/client/protocol/task/JetMessageTaskFactoryProvider.java:[75,44] cannot find symbol
--------------------------
</pre>
</details>

2023-03-09 08:28 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/16951/Hazelcast-pr-builder-16951.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/16951/Hazelcast-pr-builder-16951.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] COMPILATION ERROR : 
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/jet/impl/client/protocol/task/JetMessageTaskFactoryProvider.java:[75,34] cannot find symbol
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project hazelcast: Compilation failure: Compilation failure: 
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/jet/impl/client/protocol/task/JetMessageTaskFactoryProvider.java:[75,34] cannot find symbol
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/jet/impl/client/protocol/task/JetMessageTaskFactoryProvider.java:[75,44] cannot find symbol
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/jet/impl/client/protocol/task/JetMessageTaskFactoryProvider.java:[75,34] cannot find symbol
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/jet/impl/client/protocol/task/JetMessageTaskFactoryProvider.java:[75,44] cannot find symbol
--------------------------
</pre>
</details>

2023-03-09 08:28 UTC, hz-devops-test commented
The job `Hazelcast-pr-compiler` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-compiler/6568/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-compiler/6568/Hazelcast-pr-compiler-6568.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] COMPILATION ERROR : 
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/hazelcast/src/main/java/com/hazelcast/jet/impl/client/protocol/task/JetMessageTaskFactoryProvider.java:[75,34] cannot find symbol
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project hazelcast: Compilation failure: Compilation failure: 
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/hazelcast/src/main/java/com/hazelcast/jet/impl/client/protocol/task/JetMessageTaskFactoryProvider.java:[75,34] cannot find symbol
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/hazelcast/src/main/java/com/hazelcast/jet/impl/client/protocol/task/JetMessageTaskFactoryProvider.java:[75,44] cannot find symbol
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/hazelcast/src/main/java/com/hazelcast/jet/impl/client/protocol/task/JetMessageTaskFactoryProvider.java:[75,34] cannot find symbol
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/hazelcast/src/main/java/com/hazelcast/jet/impl/client/protocol/task/JetMessageTaskFactoryProvider.java:[75,44] cannot find symbol
--------------------------
</pre>
</details>

2023-03-09 11:32 UTC, merged