Proper compound external name handling in Mongo connector
hazelcast/hazelcast pull request #24228
Opened 2023-04-06 15:09 UTC by TomaszGaweda

External name can be:
`database.collection`
or just `collection`.

In the second case, the database must be provided in the data link definition.

Jira: [#HZ-2260](https://hazelcast.atlassian.net/browse/HZ-2260)

Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [x] Label `Add to Release Notes` or `Not Release Notes content` set
- [x] Request reviewers if possible

2023-04-06 17:11 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/17780/Hazelcast-pr-builder-17780.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/17780/Hazelcast-pr-builder-17780.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>

</pre>
</details>

2023-04-11 10:53 UTC, ldziedziul approved these changes

2023-04-12 20:06 UTC, frant-hartm requested changes

2023-04-12 20:06 UTC, frant-hartm commented on hazelcast-sql/src/test/java/com/hazelcast/jet/sql/impl/connector/mongodb/MongoBatchSqlConnectorTest.java
> +        execute("CREATE MAPPING " + mappingName + " external name " + externalName + " ("
```suggestion
        execute("CREATE MAPPING " + mappingName + " EXTERNAL NAME " + externalName + " ("
```

2023-04-12 20:06 UTC, frant-hartm commented on hazelcast-sql/src/test/java/com/hazelcast/jet/sql/impl/connector/mongodb/MongoBatchSqlConnectorTest.java
>                  + (includeIdInMapping ? " id VARCHAR external name _id, " : "")
```suggestion
                + (includeIdInMapping ? " id VARCHAR EXTERNAL NAME _id, " : "")
```

2023-04-12 20:06 UTC, frant-hartm commented on hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/mongodb/FieldResolver.java
> +        ClientWithDataConnection connect = connect(dataConnectionName, options);
You actually don't need both client and dataConnection. It's enough in `connect` to do the following:

- get dataConnection 
- get client
- release the dataConnection
- close the client

You don't need to keep the dataConnection until you close the client.

2023-04-12 20:18 UTC, TomaszGaweda commented
all done @frant-hartm :)

2023-04-12 20:29 UTC, frant-hartm approved these changes

2023-04-12 21:14 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/17833/Hazelcast-pr-builder-17833.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/17833/Hazelcast-pr-builder-17833.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   MongoStreamSqlConnectorTest.readsFromMongo_withId_oneStep:52->readsFromMongo:109->SqlTestSupport.assertRowsEventuallyInAnyOrder:293 
Expecting actual:
  [Row{[Anakin, Skywalker, insert]}]
to contain exactly in any order:
  [Row{[Luke, Skywalker, insert]}, Row{[Anakin, Skywalker, insert]}]
but could not find the following elements:
  [Row{[Luke, Skywalker, insert]}]

[ERROR]   MongoStreamSqlConnectorTest.readsFromMongo_withoutId_oneStep:62->readsFromMongo:109->SqlTestSupport.assertRowsEventuallyInAnyOrder:293 
Expecting actual:
  [Row{[Anakin, Skywalker, insert]}]
to contain exactly in any order:
  [Row{[Luke, Skywalker, insert]}, Row{[Anakin, Skywalker, insert]}]
but could not find the following elements:
  [Row{[Luke, Skywalker, insert]}]

[INFO] 
[ERROR] Tests run: 5495, Failures: 2, Errors: 0, Skipped: 11
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2023-04-13 10:12 UTC, hz-devops-test commented
The job `Hazelcast-pr-compiler` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-compiler/7404/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-compiler/7404/Hazelcast-pr-compiler-7404.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] COMPILATION ERROR : 
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mongodb/src/test/java/com/hazelcast/jet/mongodb/MongoSourceTest.java:[226,35] no suitable method found for stream(java.lang.String,()->mongoC[...]ring))
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:testCompile (default-testCompile) on project hazelcast-jet-mongodb: Compilation failure
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mongodb/src/test/java/com/hazelcast/jet/mongodb/MongoSourceTest.java:[226,35] no suitable method found for stream(java.lang.String,()->mongoC[...]ring))
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mongodb/src/test/java/com/hazelcast/jet/mongodb/MongoSourceTest.java:[226,35] no suitable method found for stream(java.lang.String,()->mongoC[...]ring))
--------------------------
</pre>
</details>

2023-04-14 12:37 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/17895/Hazelcast-pr-builder-17895.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/17895/Hazelcast-pr-builder-17895.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   MongoStreamSqlConnectorTest.readsFromMongo_withId_twoSteps:47->readsFromMongo:109->SqlTestSupport.assertRowsEventuallyInAnyOrder:293 
Expecting actual:
  [Row{[Anakin, Skywalker, insert]}]
to contain exactly in any order:
  [Row{[Luke, Skywalker, insert]}, Row{[Anakin, Skywalker, insert]}]
but could not find the following elements:
  [Row{[Luke, Skywalker, insert]}]

[INFO] 
[ERROR] Tests run: 5503, Failures: 1, Errors: 0, Skipped: 11
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2023-04-14 13:08 UTC, TomaszGaweda commented
run-lab-run

2023-04-14 14:00 UTC, merged