Validate table exists in JdbcSqlConnector [HZ-2286]
hazelcast/hazelcast pull request #24259
Opened 2023-04-13 06:28 UTC by frant-hartm

When CREATE MAPPING has no fields defined and a table does not exist the mapping was created with no fields.

Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [x] Label `Add to Release Notes` or `Not Release Notes content` set
- [x] Request reviewers if possible

2023-04-13 06:33 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/17845/Hazelcast-pr-builder-17845.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/17845/Hazelcast-pr-builder-17845.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.2.1:checkstyle (default) on project hazelcast-sql: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There are 2 errors reported by Checkstyle 8.38 with /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/checkstyle/checkstyle.xml ruleset. -> [Help 1]
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast-sql/src/main/java/com/hazelcast/sql/impl/QueryUtils.java:40:8: Unused import - java.util.stream.Collectors. [UnusedImports]
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast-sql/src/main/java/com/hazelcast/sql/impl/QueryUtils.java:42:15: Unused import - java.util.Arrays.asList. [UnusedImports]
--------------------------
</pre>
</details>

2023-04-13 06:38 UTC, hz-devops-test commented
The job `Hazelcast-pr-compiler` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-compiler/7395/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-compiler/7395/Hazelcast-pr-compiler-7395.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.2.1:checkstyle (default) on project hazelcast-sql: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There are 2 errors reported by Checkstyle 8.38 with /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/checkstyle/checkstyle.xml ruleset. -> [Help 1]
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/hazelcast-sql/src/main/java/com/hazelcast/sql/impl/QueryUtils.java:40:8: Unused import - java.util.stream.Collectors. [UnusedImports]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/hazelcast-sql/src/main/java/com/hazelcast/sql/impl/QueryUtils.java:42:15: Unused import - java.util.Arrays.asList. [UnusedImports]
--------------------------
</pre>
</details>

2023-04-13 11:53 UTC, orcunc requested changes

2023-04-13 11:53 UTC, orcunc commented on hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/jdbc/JdbcSqlConnector.java
> +        ResultSet tables = databaseMetaData.getTables(
The resulSet needs to be closed.
````
try(ResultSet rs =databaseMetaData.getTables(...})) {
  if (rs.next()) {
   ...
  } else {
  throw new HazelcastException(...);
  }
}
````

2023-04-13 14:32 UTC, TomaszGaweda approved these changes
super small nits only

2023-04-13 14:32 UTC, TomaszGaweda commented on hazelcast-sql/src/test/java/com/hazelcast/jet/sql/impl/connector/jdbc/MappingJdbcSqlConnectorTest.java
> +                        + "DATA CONNECTION " + TEST_DATABASE_REF
```suggestion
                "CREATE MAPPING " + tableName + " DATA CONNECTION " + TEST_DATABASE_REF
```

2023-04-13 14:32 UTC, TomaszGaweda commented on hazelcast-sql/src/main/java/com/hazelcast/sql/impl/QueryUtils.java
>       *                                  an exception is thrown. The check is ignored if passed version is {@code null}
```suggestion
     *                                  version, an exception is thrown. 
     *                                  The check is ignored if passed version is {@code null}
```

2023-04-14 15:16 UTC, frant-hartm commented on hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/jdbc/JdbcSqlConnector.java
> +        ResultSet tables = databaseMetaData.getTables(
Good catch.
2ff83c6b8c3

2023-04-14 15:16 UTC, frant-hartm commented on hazelcast-sql/src/test/java/com/hazelcast/jet/sql/impl/connector/jdbc/MappingJdbcSqlConnectorTest.java
> +                        + "DATA CONNECTION " + TEST_DATABASE_REF
2ff83c6b8c3

2023-04-17 07:27 UTC, orcunc approved these changes

2023-04-17 12:31 UTC, merged