Improve permission control of executor service proxies [API-2008]
hazelcast/hazelcast pull request #24271
Opened 2023-04-13 14:51 UTC by mdumandag

We had a feature to perform permission control for invocations sent over the client.

These permissions were missing from the message tasks of ExecutorService and DurableExecutor service.

In this PR, similar to the permissions used in the ScheduledExecutorService, I have introduced two new permissions for `READ` and `MODIFY` operations and updated the message tasks with those.

Also, I saw that we were not enforcing permissions for the invocations sent over the client-side ScheduledExecutorService proxy. I have fixed that and added tests for it.

EE: https://github.com/hazelcast/hazelcast-enterprise/pull/5917

2023-04-17 17:20 UTC, kwart requested changes
I just went quickly through the changes and I would like to avoid returning `null` from the `getRequiredPermission()` method.
We can also discuss other changes in the JIRA.

2023-04-20 08:59 UTC, mdumandag commented on hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/executorservice/ExecutorServiceCancelOnAddressMessageTask.java
> +            return null;
https://github.com/hazelcast/hazelcast/pull/24271/commits/31eca439fbbe97235f36286fa2b81c9b3556fa32

2023-04-20 08:59 UTC, mdumandag commented on hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/executorservice/ExecutorServiceCancelOnPartitionMessageTask.java
> +            return null;
https://github.com/hazelcast/hazelcast/pull/24271/commits/31eca439fbbe97235f36286fa2b81c9b3556fa32

2023-04-20 09:50 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/17991/Hazelcast-pr-builder-17991.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/17991/Hazelcast-pr-builder-17991.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   MapStoreForceOffloadAllOperationTest.metrics_show_offloaded_operation_count_when_forced_offload_enabled:81->HazelcastTestSupport.assertTrueEventually:1392->HazelcastTestSupport.assertTrueEventually:1288->lambda$metrics_show_offloaded_operation_count_when_forced_offload_enabled$0:86
[INFO] 
[ERROR] Tests run: 54747, Failures: 1, Errors: 0, Skipped: 244
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2023-04-20 10:01 UTC, mdumandag commented
run-lab-run

2023-04-20 10:59 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/17998/Hazelcast-pr-builder-17998.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/17998/Hazelcast-pr-builder-17998.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>

</pre>
</details>

2023-04-21 12:48 UTC, kwart approved these changes

2023-04-25 00:30 UTC, srknzl approved these changes

2023-04-25 07:41 UTC, mdumandag commented
run-lab-run

2023-04-28 08:23 UTC, merged