Check table exists in another db [HZ-2327]
hazelcast/hazelcast pull request #24386
Opened 2023-04-26 06:05 UTC by orcunc

For MySQL the schema name does not exists. In the external name configuration the schema name must be used as catalog name

Fixes https://github.com/hazelcast/hazelcast/issues/24340
Jira : https://hazelcast.atlassian.net/browse/HZ-2327

Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [x] Label `Add to Release Notes` or `Not Release Notes content` set
- [x] Request reviewers if possible

2023-04-26 13:46 UTC, frant-hartm requested changes

2023-04-27 05:21 UTC, orcunc commented on hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/jdbc/ConnectionUtils.java
> +    }
rev : 3cf539c82b78a9722a140ed39f0fe8417b5561d2

2023-04-27 05:21 UTC, orcunc commented on hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/jdbc/JdbcSqlConnector.java
> +        String schema = Objects.toString(externalTableName.schema, connection.getSchema());
rev : 3cf539c82b78a9722a140ed39f0fe8417b5561d2

2023-04-27 14:49 UTC, frant-hartm approved these changes

2023-04-27 15:59 UTC, merged