TxnMapProxyMadeGeneric
hazelcast/hazelcast pull request #24544
Opened 2023-05-12 10:35 UTC by aditya-32

Making TransactionalMapProxy generic
Fixes #7484 

Checklist:
- [ ] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [ ] Label `Add to Release Notes` or `Not Release Notes content` set
- [ ] Request reviewers if possible
- [ ] Send backports/forwardports if fix needs to be applied to past/future releases
- [ ] New public APIs have `@Nonnull/@Nullable` annotations
- [ ] New public APIs have `@since` tags in Javadoc

2023-05-12 10:35 UTC, devOpsHazelcast commented
Can one of the admins verify this patch?

2023-05-12 10:35 UTC, devOpsHazelcast commented
Can one of the admins verify this patch?

2023-05-12 10:36 UTC, aditya-32 commented
hi @ahmetmircik @srknzl can you please review the PR

2023-05-12 11:30 UTC, srknzl commented on hazelcast/src/main/java/com/hazelcast/map/impl/tx/TransactionalMapProxy.java
> +public class TransactionalMapProxy<K, V>
Changes I suggest for this file: 

```diff
diff --git a/hazelcast/src/main/java/com/hazelcast/map/impl/tx/TransactionalMapProxy.java b/hazelcast/src/main/java/com/hazelcast/map/impl/tx/TransactionalMapProxy.java
index 067409728b..9e4391dc32 100644
--- a/hazelcast/src/main/java/com/hazelcast/map/impl/tx/TransactionalMapProxy.java
+++ b/hazelcast/src/main/java/com/hazelcast/map/impl/tx/TransactionalMapProxy.java
@@ -140,12 +140,12 @@ public class TransactionalMapProxy<K, V>
     }
 
     @Override
-    public V put(Object key, Object value) {
+    public V put(K key, V value) {
         return put(key, value, -1, MILLISECONDS);
     }
 
     @Override
-    public V put(Object key, Object value, long ttl, TimeUnit timeUnit) {
+    public V put(K key, V value, long ttl, TimeUnit timeUnit) {
         checkTransactionState();
         checkNotNull(key, "key can't be null");
         checkNotNull(value, "value can't be null");
@@ -160,13 +160,13 @@ public class TransactionalMapProxy<K, V>
                 ttl, timeUnit, remoteCallHook));
         TxnValueWrapper<V> currentValue = txMap.get(keyData);
         Type type = valueBeforeTxn == null ? Type.NEW : Type.UPDATED;
-        TxnValueWrapper<V> wrapper = new TxnValueWrapper<>((V) value, type);
+        TxnValueWrapper<V> wrapper = new TxnValueWrapper<>(value, type);
         txMap.put(keyData, wrapper);
         return currentValue == null ? valueBeforeTxn : checkIfRemoved(currentValue);
     }
 
     @Override
-    public void set(Object key, Object value) {
+    public void set(K key, V value) {
         checkTransactionState();
         checkNotNull(key, "key can't be null");
         checkNotNull(value, "value can't be null");
@@ -179,12 +179,12 @@ public class TransactionalMapProxy<K, V>
 
         Data dataBeforeTxn = putInternal(keyData, valueData, UNSET, MILLISECONDS, remoteCallHook);
         Type type = dataBeforeTxn == null ? Type.NEW : Type.UPDATED;
-        TxnValueWrapper<V> wrapper = new TxnValueWrapper<>((V) value, type);
+        TxnValueWrapper<V> wrapper = new TxnValueWrapper<>(value, type);
         txMap.put(keyData, wrapper);
     }
 
     @Override
-    public V putIfAbsent(Object key, Object value) {
+    public V putIfAbsent(K key, V value) {
         checkTransactionState();
         checkNotNull(key, "key can't be null");
         checkNotNull(value, "value can't be null");
@@ -202,19 +202,19 @@ public class TransactionalMapProxy<K, V>
                 return wrapper.value;
             }
             putInternal(keyData, valueData, UNSET, MILLISECONDS, remoteCallHook);
-            txMap.put(keyData, new TxnValueWrapper<>((V) value, Type.NEW));
+            txMap.put(keyData, new TxnValueWrapper<>(value, Type.NEW));
             return null;
         } else {
             Data oldValue = putIfAbsentInternal(keyData, valueData, remoteCallHook);
             if (oldValue == null) {
-                txMap.put(keyData, new TxnValueWrapper<>((V) value, Type.NEW));
+                txMap.put(keyData, new TxnValueWrapper<>(value, Type.NEW));
             }
             return (V) toObjectIfNeeded(oldValue);
         }
     }
 
     @Override
-    public V replace(Object key, Object value) {
+    public V replace(K key, V value) {
         checkTransactionState();
         checkNotNull(key, "key can't be null");
         checkNotNull(value, "value can't be null");
@@ -232,19 +232,19 @@ public class TransactionalMapProxy<K, V>
                 return null;
             }
             putInternal(keyData, valueData, UNSET, MILLISECONDS, remoteCallHook);
-            txMap.put(keyData, new TxnValueWrapper<>((V) value, Type.UPDATED));
+            txMap.put(keyData, new TxnValueWrapper<>(value, Type.UPDATED));
             return wrapper.value;
         } else {
             Data oldValue = replaceInternal(keyData, valueData, remoteCallHook);
             if (oldValue != null) {
-                txMap.put(keyData, new TxnValueWrapper<>((V) value, Type.UPDATED));
+                txMap.put(keyData, new TxnValueWrapper<>(value, Type.UPDATED));
             }
             return (V) toObjectIfNeeded(oldValue);
         }
     }
 
     @Override
-    public boolean replace(Object key, Object oldValue, Object newValue) {
+    public boolean replace(K key, V oldValue, V newValue) {
         checkTransactionState();
         checkNotNull(key, "key can't be null");
         checkNotNull(oldValue, "oldValue can't be null");
@@ -269,7 +269,7 @@ public class TransactionalMapProxy<K, V>
             boolean success = replaceIfSameInternal(keyData, mapServiceContext.toData(oldValue),
                     newValueData, remoteCallHook);
             if (success) {
-                txMap.put(keyData, new TxnValueWrapper<>((V) newValue, Type.UPDATED));
+                txMap.put(keyData, new TxnValueWrapper<>(newValue, Type.UPDATED));
             }
             return success;
         }
@@ -403,7 +403,7 @@ public class TransactionalMapProxy<K, V>
 
     @Override
     @SuppressWarnings("unchecked")
-    public Collection<V> values(Predicate predicate) {
+    public Collection<V> values(Predicate<K, V> predicate) {
         checkTransactionState();
         checkNotNull(predicate, "Predicate can not be null!");
         checkNotInstanceOf(PagingPredicate.class, predicate,

```

2023-05-15 17:55 UTC, srknzl approved these changes

2023-05-15 17:55 UTC, srknzl commented
run-lab-run

2023-05-15 17:59 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/18498/Hazelcast-pr-builder-18498.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/18498/Hazelcast-pr-builder-18498.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.2.2:checkstyle (default) on project hazelcast: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There are 2 errors reported by Checkstyle 8.38 with /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/checkstyle/checkstyle.xml ruleset. -> [Help 1]
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/map/impl/tx/TransactionalMapProxy.java:359:37: ',' is not followed by whitespace. [WhitespaceAfter]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/map/impl/tx/TransactionalMapProxy.java:406:44: ',' is not followed by whitespace. [WhitespaceAfter]
--------------------------
</pre>
</details>

2023-05-15 18:13 UTC, aditya-32 commented
fixed check style error  , can you please run the pr builder once more?

2023-05-15 18:25 UTC, srknzl commented
run-lab-run

2023-05-18 10:56 UTC, ahmetmircik commented
@aditya-32 What was the rationale of this change? These are internal classes and type checking can stop working of it for some mechanisms i suppose.

2023-05-18 10:56 UTC, ahmetmircik requested changes
added question

2023-05-19 04:28 UTC, aditya-32 commented
Hi @ahmetmircik  can you please provide in some instance where we you see that can cause problem?

2023-05-19 04:29 UTC, aditya-32 commented
it was an open issue which i tried to fix by making the class generic

2023-05-22 05:53 UTC, aditya-32 commented
@srknzl @ahmetmircik  any update on this, Are we moving forward with this PR?

2023-05-26 14:49 UTC, ahmetmircik commented on hazelcast/src/main/java/com/hazelcast/map/impl/tx/TransactionalMapProxy.java
> +    public V get(Object key, boolean skipNearCacheLookup) {
let's keep this as Object return type, it serves for both client and member proxies and for client we sent serialized form.

2023-05-26 14:55 UTC, ahmetmircik commented
@aditya-32 server side map-proxy is used for multiple purposes, returning both serialized and de-serialized is legitimate types for it. We shouldn't do generic conversion on this part. Given this, i'm sorry that we need to close this PR.

2023-05-27 04:16 UTC, aditya-32 commented
@ahmetmircik if there is issue in making the class generic sure we can close it 
just wanted to know like how making it generic will cause issue in serialisation and de-serialisation.

2023-05-29 13:20 UTC, ahmetmircik commented
@aditya-32 thx for the work.

2023-05-29 13:20 UTC, closed without merging