Support nullable types when reading Avro files [HZ-2507]
hazelcast/hazelcast pull request #24840
Opened 2023-06-19 10:09 UTC by burakgok

Specifically, the following statements are affected:
```sql
CREATE MAPPING <name> TYPE File OPTIONS ('format'='avro', ...)
TABLE(AVRO_FILE(...))
```

Fixes HZ-2507

Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [x] Label `Add to Release Notes` or `Not Release Notes content` set
- [x] Request reviewers if possible
- [ ] Send backports/forwardports if fix needs to be applied to past/future releases

2023-07-03 11:58 UTC, k-jamroz commented
Is it a breaking change?

2023-07-03 12:08 UTC, k-jamroz approved these changes

2023-07-13 14:17 UTC, burakgok commented
This change just enables Avro file mappings and `AVRO_FILE` function to read unions of a primitive and null. It doesn't break the existing capability of reading primitives.

2023-07-18 14:05 UTC, frant-hartm requested changes

2023-07-18 14:05 UTC, frant-hartm commented on hazelcast-sql/src/test/java/com/hazelcast/jet/sql/impl/connector/file/SqlAvroTest.java
> +    }
We are missing test reading `null`s. This reads nullable fields, which contain values.

2023-07-27 12:53 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder-sql` of your PR failed. (Hazelcast internal details: [build log](
https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder-sql/229/Hazelcast-pr-builder-sql-229.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder-sql/229/Hazelcast-pr-builder-sql-229.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>

</pre>
</details>

2023-07-27 12:55 UTC, burakgok commented
run-lab-run

2023-07-27 13:36 UTC, burakgok commented
run-lab-run

2023-07-27 15:09 UTC, burakgok commented
run-lab-run

2023-07-28 09:21 UTC, frant-hartm approved these changes

2023-07-28 09:28 UTC, merged