Use member address as fallback if missing CLIENT endpoint qualifier in advanced networking configuration of the member
hazelcast/hazelcast pull request #25097
Opened 2023-07-28 15:35 UTC by ihsandemir

Added a fallback to member address usage if the user failed to set the CLIENT endpoint qualifier in the advanced networking configuration.

fixes #25032

2023-07-28 16:34 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/19536/Hazelcast-pr-builder-19536.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/19536/Hazelcast-pr-builder-19536.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
---------ERRORS-----------
--------------------------
[ERROR] Tests run: 17, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 195.4 s <<< FAILURE! -- in com.hazelcast.jet.kinesis.KinesisIntegrationTest
--------------------------
[ERROR] com.hazelcast.jet.kinesis.KinesisIntegrationTest.dynamicStream_1Shard_splitsDuringData -- Time elapsed: 127.0 s <<< FAILURE!
--------------------------
[ERROR] Failures: 
--------------------------
[ERROR]   KinesisIntegrationTest.dynamicStream_1Shard_splitsDuringData:324->dynamicStream_splitsDuringData:354->assertMessages:637->AbstractKinesisTest.assertMessages:163->HazelcastTestSupport.assertTrueEventually:1269->HazelcastTestSupport.assertTrueEventually:1165->AbstractKinesisTest.lambda$assertMessages$3:180 Messages for key 243 differ!
--------------------------
[ERROR] Tests run: 25, Failures: 1, Errors: 0, Skipped: 3
--------------------------
[ERROR] There are test failures.
--------------------------
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   KinesisIntegrationTest.dynamicStream_1Shard_splitsDuringData:324->dynamicStream_splitsDuringData:354->assertMessages:637->AbstractKinesisTest.assertMessages:163->HazelcastTestSupport.assertTrueEventually:1269->HazelcastTestSupport.assertTrueEventually:1165->AbstractKinesisTest.lambda$assertMessages$3:180 Messages for key 243 differ!
	expected: 10
	  actual: 690 expected:<[243: msg 000000243, 243: msg 000000493, 243: msg 000000743, 243: msg 000000993, 243: msg 000001243, 243: msg 000001493, 243: msg 000001743, 243: msg 000001993, 243: msg 000002243, 243: msg 000002493]> but was:<[243: msg 000000243, 243: msg 000000493, 243: msg 000000743, 243: msg 000000993, 243: msg 000001243, 243: msg 000001493, 243: msg 000001743, 243: msg 000001993, 243: msg 000002243, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 000002493, 243: msg 00000 [...]

2023-07-31 07:18 UTC, kwart commented
I've commented on the related issue

> Could the member address used there break things somewhere else?
> That brings me to a question: Is having some members without the client endpoint OK? I guess so, users could use one member as the access point for client protocol, and only basic (non-smart) clients would connect through it. If we don't want to allow such scenarios, then it would rather deserve a config-check during member start. And fail fast.

2023-07-31 15:30 UTC, srknzl reviewed
This change makes sense if a client can connect to member endpoint of a member and work fine. I dont know it.

2023-07-31 15:32 UTC, srknzl commented
Another comment: maybe if there is no CLIENT endpoint and we use the MEMBER endpoint, we can log a warning message if it is important for the user to have a CLIENT endpoint.

2023-07-31 19:14 UTC, srknzl approved these changes

2023-08-01 10:07 UTC, ihsandemir commented
run-lab-run

2023-08-09 09:45 UTC, kwart requested changes
Most of the discussion about this issue and PR went on Slack.

My view is we should prepare a proper fix.
Even when the NPE doesn't happen after applying this PR, we shouldn't send the wrong address for client protocol. We should allow sending empty/null addresses when the advanced network is configured and the member doesn't have the client endpoint enabled/configured.

2023-10-20 15:29 UTC, ihsandemir commented
Based on discussion with @kwart we decided to use a fallback default ip which will not match to any meaningful useful address but it won't also fail in address resolution when `new Address("new number")` is called. Candidate is to use `0.0.0.0` but I will experiemnt it and try to write a test for it.

2024-01-11 11:21 UTC, closed without merging