Assign to test failure GH Action
hazelcast/hazelcast pull request #25152
Opened 2023-08-04 16:56 UTC by Patras3

The main assumption is to assign a developer who lastly edited the code mentioned in the test failure issue.

This workflow will be invoked for issues with `.*Test-Failure.*` label. Creating a new issue with this label or adding label later has the same effect.

Implemented steps:
1. Find commit from issue description: `(commit\s([^)\s]+)` with fallback to `main`. 
_This regex meets currently used template by QEs team._
2. Checkout to specific commit or master branch
3. Parse issue title to find affected code
_Examples_:

| Title | Path | 
| --- | --- |
| `KinesisIntegrationTest` | `KinesisIntegrationTest.java` | 
| `KinesisIntegrationTest.dynamicStream_1Shard_splitsDuringData` | `KinesisIntegrationTest.java` | 
| `Several tests failed with NPE in 'com.hazelcast.cache.impl.hidensity.operation'` |`com/hazelcast/cache/impl/hidensity/operation` |
| `Nothing about package and no class name with Test suffix` | -|

4. Find last commit for path find in previous step.
_It uses bash `find . -wholename "*$FILENAME*" -type f` and iterates of each file to find recently edit file (committed)_
5. Find GH username for commit
6. Check if username belongs to organization
7. Print details
8. Evaluate suggested assignment
_Found username from previous steps will be used only if this username belongs currently to the organization. If any of previous step is failed or there is no reference to code in the title, or username is outside of organization, then author of issue will be assigned as fallback._
9. Assign issue and and proper comment
_Types of comments:_
_`Assigned @${commitAuthor} due to being the author of last commit (${commit})`
`Assigned @${issueAuthor}, because identified author (${commitAuthor}) of last commit (${commit}) is not a member of the organization`
`Assigned @${issueAuthor} due to not found reference to code in the issue `_

Checklist:
- [X] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [X] Label `Add to Release Notes` or `Not Release Notes content` set
- [X] Request reviewers if possible

2023-08-04 17:02 UTC, Patras3 commented
I would like to merge this, test with some TFs, and temporarily disable it until this way of handling test failures will be officially introduced. In this way, my upcoming 2 weeks' absence won't have an impact.

2023-08-04 17:55 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/19658/Hazelcast-pr-builder-19658.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/19658/Hazelcast-pr-builder-19658.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
---------ERRORS-----------
--------------------------
[ERROR] Tests run: 18, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 10.85 s <<< FAILURE! -- in com.hazelcast.spi.tenantcontrol.TenantControlTest
--------------------------
[ERROR] com.hazelcast.spi.tenantcontrol.TenantControlTest.basicMapTest[tenantControl: true] -- Time elapsed: 10.61 s <<< FAILURE!
--------------------------
[ERROR] Failures: 
--------------------------
[ERROR]   TenantControlTest.basicMapTest:185 expected:<1> but was:<11>
--------------------------
[ERROR] Tests run: 4659, Failures: 1, Errors: 0, Skipped: 11
--------------------------
[ERROR] There are test failures.
--------------------------
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   TenantControlTest.basicMapTest:185 expected:<1> but was:<11>
[INFO] 
[ERROR] Tests run: 4659, Failures: 1, Errors: 0, Skipped: 11
[INFO] 
[WARNING] Corrupted channel by directly writing to native stream in forked JVM 9. See FAQ web page and the dump file /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/target/surefire-reports/2023-08-04T17-01-30_524-jvmRun9.dumpstream

[ERROR] There are test failures.
</pre>
</details>

2023-08-14 09:12 UTC, frant-hartm commented
@ldziedziul could you please have a look at this?

2023-08-24 06:35 UTC, kwart approved these changes

2023-08-24 14:10 UTC, ldziedziul approved these changes
In general looks good but I'm concerned about maintainability of these JS scripts embedded in the workflow file. My personal preference would be to use bash scripts instead ;)

2023-08-25 07:56 UTC, olukas requested changes
IIUC there's one copy-paste error which actually means it will work incorrectly for common case - when we find author of commit we will not assign him but still assign `issueAuthor`.

2023-08-25 07:56 UTC, olukas commented on .github/workflows/assign-to-test-failure.yml
> +            //Return package path
nit: alignment

2023-08-25 07:56 UTC, olukas commented on .github/workflows/assign-to-test-failure.yml
> +              finalAssignement: issueAuthor
Shouldn't this be `commitAuthor`?

2023-08-25 08:25 UTC, hz-devops-test commented
The job `Hazelcast-pr-EE-compiler` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-EE-compiler/8834/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-EE-compiler/8834/Hazelcast-pr-EE-compiler-8834.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
---------ERRORS-----------
--------------------------
[ERROR] Failed to execute goal pl.project13.maven:git-commit-id-plugin:4.9.10:revision (default) on project hazelcast: Could not complete Mojo execution... Missing tree 2a16e70f898cd00b6ae18a9967010c239ffe6d55 -> [Help 1]
--------------------------
[ERROR] 
--------------------------
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
--------------------------
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
--------------------------
[ERROR] 
--------------------------
[ERROR] For more information about the errors and possible solutions, please read the following articles:
--------------------------
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
--------------------------
[ERROR] 
--------------------------
[ERROR] After correcting the problems, you can resume the build with the command
--------------------------
[ERROR]   mvn <args> -rf :hazelcast
--------------------------
</pre>
</details>

2023-08-25 08:55 UTC, Patras3 commented
run-ee-compile

2023-08-25 08:58 UTC, hz-devops-test commented
The job `Hazelcast-pr-EE-compiler` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-EE-compiler/8838/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-EE-compiler/8838/Hazelcast-pr-EE-compiler-8838.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
---------ERRORS-----------
--------------------------
[ERROR] Failed to execute goal pl.project13.maven:git-commit-id-plugin:4.9.10:revision (default) on project hazelcast: Could not complete Mojo execution... Missing tree 2a16e70f898cd00b6ae18a9967010c239ffe6d55 -> [Help 1]
--------------------------
[ERROR] 
--------------------------
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
--------------------------
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
--------------------------
[ERROR] 
--------------------------
[ERROR] For more information about the errors and possible solutions, please read the following articles:
--------------------------
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
--------------------------
[ERROR] 
--------------------------
[ERROR] After correcting the problems, you can resume the build with the command
--------------------------
[ERROR]   mvn <args> -rf :hazelcast
--------------------------
</pre>
</details>

2023-08-25 09:17 UTC, olukas approved these changes

2023-08-25 09:23 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/20060/Hazelcast-pr-builder-20060.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/20060/Hazelcast-pr-builder-20060.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
---------ERRORS-----------
--------------------------
[ERROR] Tests run: 28, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 201.4 s <<< FAILURE! -- in com.hazelcast.jet.kafka.impl.StreamKafkaPTest
--------------------------
[ERROR] com.hazelcast.jet.kafka.impl.StreamKafkaPTest.when_processingGuaranteeNone_then_continueFromBeginningAfterJobRestart -- Time elapsed: 124.6 s <<< FAILURE!
--------------------------
[ERROR] Failures: 
--------------------------
[ERROR]   StreamKafkaPTest.when_processingGuaranteeNone_then_continueFromBeginningAfterJobRestart:248->testWithJobRestart:314->testWithJobRestart:345->HazelcastTestSupport.assertTrueEventually:1269->HazelcastTestSupport.assertTrueEventually:1165->lambda$testWithJobRestart$4:345 expected:<300> but was:<331>
--------------------------
[ERROR] Tests run: 51, Failures: 1, Errors: 0, Skipped: 0
--------------------------
[ERROR] There are test failures.
--------------------------
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   StreamKafkaPTest.when_processingGuaranteeNone_then_continueFromBeginningAfterJobRestart:248->testWithJobRestart:314->testWithJobRestart:345->HazelcastTestSupport.assertTrueEventually:1269->HazelcastTestSupport.assertTrueEventually:1165->lambda$testWithJobRestart$4:345 expected:<300> but was:<331>
[INFO] 
[ERROR] Tests run: 51, Failures: 1, Errors: 0, Skipped: 0
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2023-08-28 08:47 UTC, AyberkSorgun approved these changes
LGTM, great work!

2023-08-28 08:59 UTC, merged