Fix incorrect PartitioningStrategy lookup on Clients
hazelcast/hazelcast pull request #25162
Opened 2023-08-08 11:33 UTC by JamesHazelcast

Currently, `DefaultClientExtension#getPartitioningStrategy` looks at the local System Properties to find a match for the Hazelcast property `PARTITIONING_STRATEGY_CLASS`, when it should be checking the provided Hazelcast cluster properties map, defined via `ClientConfig` overrides.

This requires a simple solution - altering this method to check the provided properties map instead of the local System Properties. However, since this method has obtained the `PartitioningStrategy` via System Property for over 8 years, to maintain a greater degree of backwards compatibility, we first check to see if a local System Property already exists and use that value if it does. Otherwise, if the System Property's not defined, the client will use the local cluster property map instead.

Fixes https://hazelcast.atlassian.net/browse/HZ-2738

Breaking changes (list specific methods/types/messages):
* Customers who rely on accurate Client `PartitioningStrategy` results may see changes in behaviour if they define a custom strategy in their config (which would have been ignored prior to this fix, but would now be used after this fix).

2023-08-08 13:20 UTC, burakgok approved these changes

2023-08-09 06:55 UTC, ivanthescientist approved these changes

2023-08-09 12:05 UTC, ihsandemir requested changes

2023-08-09 12:05 UTC, ihsandemir commented on hazelcast/src/main/java/com/hazelcast/client/impl/clientside/DefaultClientExtension.java
>          String partitioningStrategyClassName = ClusterProperty.PARTITIONING_STRATEGY_CLASS.getSystemProperty();
```suggestion
        String partitioningStrategyClassName = client.getClientConfig().getProperty(
                ClusterProperty.PARTITIONING_STRATEGY_CLASS.getName());
```

2023-08-09 18:20 UTC, ihsandemir approved these changes

2023-08-10 08:31 UTC, merged