Upgrade Calcite to version 1.33
hazelcast/hazelcast pull request #25326
Opened 2023-08-29 11:43 UTC by Fly-Style

2023-08-29 11:50 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/20169/Hazelcast-pr-builder-20169.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/20169/Hazelcast-pr-builder-20169.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
---------ERRORS-----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.4.0:enforce (enforce-tools) on project hazelcast-distribution: 
--------------------------
[ERROR] Rule 2: org.apache.maven.enforcer.rules.dependency.DependencyConvergence failed with message:
--------------------------
[ERROR] Failed while enforcing releasability.
--------------------------
[ERROR] 
--------------------------
[ERROR] Dependency convergence error for org.apache.commons:commons-math3:jar:3.6.1 paths to dependency are:
--------------------------
[ERROR] +-com.hazelcast:hazelcast-distribution:jar:5.4.0-SNAPSHOT
--------------------------
[ERROR]   +-com.hazelcast:hazelcast-sql:jar:5.4.0-SNAPSHOT:compile
--------------------------
[ERROR]     +-org.apache.calcite:calcite-core:jar:1.33.0:compile
--------------------------
[ERROR]       +-org.apache.commons:commons-math3:jar:3.6.1:compile
--------------------------
[ERROR] and
--------------------------
[ERROR] +-com.hazelcast:hazelcast-distribution:jar:5.4.0-SNAPSHOT
--------------------------
[ERROR]   +-com.hazelcast.jet:hazelcast-jet-files-azure:jar:jar-with-dependencies:5.4.0-SNAPSHOT:compile
--------------------------
[ERROR]     +-org.apache.hadoop:hadoop-client:jar:3.3.6:compile
--------------------------
[ERROR]       +-org.apache.hadoop:hadoop-common:jar:3.3.6:compile
--------------------------
[ERROR]         +-org.apache.commons:commons-math3:jar:3.1.1:compile
--------------------------
[ERROR] -> [Help 1]
--------------------------
[ERROR] 
--------------------------
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
--------------------------
[ERROR] 
--------------------------
[ERROR] For more information about the errors and possible solutions, please read the following articles:
--------------------------
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
--------------------------
[ERROR] 
--------------------------
[ERROR] After correcting the problems, you can resume the build with the command
--------------------------
[ERROR]   mvn <args> -rf :hazelcast-distribution
--------------------------
</pre>
</details>

2023-08-29 11:51 UTC, hz-devops-test commented
The job `Hazelcast-pr-EE-compiler` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-EE-compiler/8929/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-EE-compiler/8929/Hazelcast-pr-EE-compiler-8929.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
---------ERRORS-----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.4.0:enforce (enforce-tools) on project hazelcast-distribution: 
--------------------------
[ERROR] Rule 2: org.apache.maven.enforcer.rules.dependency.DependencyConvergence failed with message:
--------------------------
[ERROR] Failed while enforcing releasability.
--------------------------
[ERROR] 
--------------------------
[ERROR] Dependency convergence error for org.apache.commons:commons-math3:jar:3.6.1 paths to dependency are:
--------------------------
[ERROR] +-com.hazelcast:hazelcast-distribution:jar:5.4.0-SNAPSHOT
--------------------------
[ERROR]   +-com.hazelcast:hazelcast-sql:jar:5.4.0-SNAPSHOT:compile
--------------------------
[ERROR]     +-org.apache.calcite:calcite-core:jar:1.33.0:compile
--------------------------
[ERROR]       +-org.apache.commons:commons-math3:jar:3.6.1:compile
--------------------------
[ERROR] and
--------------------------
[ERROR] +-com.hazelcast:hazelcast-distribution:jar:5.4.0-SNAPSHOT
--------------------------
[ERROR]   +-com.hazelcast.jet:hazelcast-jet-files-azure:jar:jar-with-dependencies:5.4.0-SNAPSHOT:compile
--------------------------
[ERROR]     +-org.apache.hadoop:hadoop-client:jar:3.3.6:compile
--------------------------
[ERROR]       +-org.apache.hadoop:hadoop-common:jar:3.3.6:compile
--------------------------
[ERROR]         +-org.apache.commons:commons-math3:jar:3.1.1:compile
--------------------------
[ERROR] -> [Help 1]
--------------------------
[ERROR] 
--------------------------
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
--------------------------
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
--------------------------
[ERROR] 
--------------------------
[ERROR] For more information about the errors and possible solutions, please read the following articles:
--------------------------
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
--------------------------
[ERROR] 
--------------------------
[ERROR] After correcting the problems, you can resume the build with the command
--------------------------
[ERROR]   mvn <args> -rf :hazelcast-distribution
--------------------------
</pre>
</details>

2023-08-29 11:57 UTC, hz-devops-test commented
The job `Hazelcast-pr-compiler` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-compiler/9511/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-compiler/9511/Hazelcast-pr-compiler-9511.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
---------ERRORS-----------
--------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:license-maven-plugin:2.2.0:add-third-party (add-third-party) on project hazelcast-jet-s3: There are some forbidden licenses used, please check your dependencies. -> [Help 1]
--------------------------
[ERROR] 
--------------------------
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
--------------------------
[ERROR] 
--------------------------
[ERROR] For more information about the errors and possible solutions, please read the following articles:
--------------------------
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
--------------------------
[ERROR] 
--------------------------
[ERROR] After correcting the problems, you can resume the build with the command
--------------------------
[ERROR]   mvn <args> -rf :hazelcast-jet-s3
--------------------------
</pre>
</details>

2023-08-29 13:25 UTC, hz-devops-test commented
The job `Hazelcast-pr-compiler` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-compiler/9514/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-compiler/9514/Hazelcast-pr-compiler-9514.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
---------ERRORS-----------
--------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:license-maven-plugin:2.2.0:add-third-party (add-third-party) on project hazelcast-jet-s3: There are some forbidden licenses used, please check your dependencies. -> [Help 1]
--------------------------
[ERROR] 
--------------------------
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
--------------------------
[ERROR] 
--------------------------
[ERROR] For more information about the errors and possible solutions, please read the following articles:
--------------------------
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
--------------------------
[ERROR] 
--------------------------
[ERROR] After correcting the problems, you can resume the build with the command
--------------------------
[ERROR]   mvn <args> -rf :hazelcast-jet-s3
--------------------------
</pre>
</details>

2023-08-30 11:22 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/20197/Hazelcast-pr-builder-20197.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/20197/Hazelcast-pr-builder-20197.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
---------ERRORS-----------
--------------------------
[ERROR] Tests run: 26, Failures: 0, Errors: 26, Skipped: 0, Time elapsed: 2.716 s <<< FAILURE! -- in com.hazelcast.mapstore.AllTypesGenericMapStoreTest
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.loadRecord[type:VARCHAR(100), mappingType:'dummy', value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$715/0x0000000800327840@907f2b7, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$716/0x0000000800327c40@435ce306] -- Time elapsed: 1.216 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.storeRecord[type:VARCHAR(100), mappingType:'dummy', value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$715/0x0000000800327840@907f2b7, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$716/0x0000000800327c40@435ce306] -- Time elapsed: 0.047 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.storeRecord[type:BOOLEAN, mappingType:TRUE, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$717/0x0000000800327040@75699e35, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$718/0x0000000800327440@107e5441] -- Time elapsed: 0.027 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.loadRecord[type:BOOLEAN, mappingType:TRUE, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$717/0x0000000800327040@75699e35, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$718/0x0000000800327440@107e5441] -- Time elapsed: 0.043 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.loadRecord[type:TINYINT, mappingType:1, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$719/0x0000000800326840@4aeaadc1, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$720/0x0000000800326c40@263558c9] -- Time elapsed: 0.020 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.storeRecord[type:TINYINT, mappingType:1, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$719/0x0000000800326840@4aeaadc1, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$720/0x0000000800326c40@263558c9] -- Time elapsed: 0.019 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.storeRecord[type:SMALLINT, mappingType:2, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$721/0x0000000800326040@1f14f20c, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$722/0x0000000800326440@7daa61f3] -- Time elapsed: 0.050 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.loadRecord[type:SMALLINT, mappingType:2, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$721/0x0000000800326040@1f14f20c, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$722/0x0000000800326440@7daa61f3] -- Time elapsed: 0.047 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.loadRecord[type:INTEGER, mappingType:3, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$723/0x0000000800325840@62315f22, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$724/0x0000000800325c40@6e4ea0bd] -- Time elapsed: 0.024 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.storeRecord[type:INTEGER, mappingType:3, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$723/0x0000000800325840@62315f22, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$724/0x0000000800325c40@6e4ea0bd] -- Time elapsed: 0.027 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.storeRecord[type:BIGINT, mappingType:4, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$725/0x0000000800325040@56f2bbea, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$726/0x0000000800325440@78f9ed3e] -- Time elapsed: 0.006 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.loadRecord[type:BIGINT, mappingType:4, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$725/0x0000000800325040@56f2bbea, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$726/0x0000000800325440@78f9ed3e] -- Time elapsed: 0.046 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.storeRecord[type:DECIMAL (10,5), mappingType:1.12345, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$727/0x0000000800324840@1059754c, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$728/0x0000000800324c40@b0964b2] -- Time elapsed: 0.049 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.loadRecord[type:DECIMAL (10,5), mappingType:1.12345, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$727/0x0000000800324840@1059754c, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$728/0x0000000800324c40@b0964b2] -- Time elapsed: 0.036 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.loadRecord[type:REAL, mappingType:1.5, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$729/0x0000000800324040@48e7b3d2, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$730/0x0000000800324440@7f4037ed] -- Time elapsed: 0.038 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.storeRecord[type:REAL, mappingType:1.5, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$729/0x0000000800324040@48e7b3d2, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$730/0x0000000800324440@7f4037ed] -- Time elapsed: 0.025 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.loadRecord[type:DOUBLE, mappingType:1.8, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$731/0x0000000800323840@24e8de5c, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$732/0x0000000800323c40@64040287] -- Time elapsed: 0.039 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.storeRecord[type:DOUBLE, mappingType:1.8, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$731/0x0000000800323840@24e8de5c, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$732/0x0000000800323c40@64040287] -- Time elapsed: 0.028 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.storeRecord[type:DATE, mappingType:'2022-12-30', value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$733/0x0000000800323040@110844f6, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$734/0x0000000800323440@6f89f665] -- Time elapsed: 0.027 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.loadRecord[type:DATE, mappingType:'2022-12-30', value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$733/0x0000000800323040@110844f6, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$734/0x0000000800323440@6f89f665] - [...]

2023-08-30 13:51 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/20200/Hazelcast-pr-builder-20200.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/20200/Hazelcast-pr-builder-20200.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
---------ERRORS-----------
--------------------------
[ERROR] Tests run: 26, Failures: 0, Errors: 26, Skipped: 0, Time elapsed: 2.638 s <<< FAILURE! -- in com.hazelcast.mapstore.AllTypesGenericMapStoreTest
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.storeRecord[type:VARCHAR(100), mappingType:'dummy', value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$716/0x0000000800327c40@4fcc529, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$717/0x0000000800327040@25cc7470] -- Time elapsed: 1.149 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.loadRecord[type:VARCHAR(100), mappingType:'dummy', value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$716/0x0000000800327c40@4fcc529, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$717/0x0000000800327040@25cc7470] -- Time elapsed: 0.043 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.loadRecord[type:BOOLEAN, mappingType:TRUE, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$718/0x0000000800327440@20d11153, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$719/0x0000000800326840@3887cf88] -- Time elapsed: 0.035 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.storeRecord[type:BOOLEAN, mappingType:TRUE, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$718/0x0000000800327440@20d11153, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$719/0x0000000800326840@3887cf88] -- Time elapsed: 0.026 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.storeRecord[type:TINYINT, mappingType:1, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$720/0x0000000800326c40@5649ec46, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$721/0x0000000800326040@78dc4696] -- Time elapsed: 0.037 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.loadRecord[type:TINYINT, mappingType:1, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$720/0x0000000800326c40@5649ec46, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$721/0x0000000800326040@78dc4696] -- Time elapsed: 0.033 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.storeRecord[type:SMALLINT, mappingType:2, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$722/0x0000000800326440@502f8b57, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$723/0x0000000800325840@5652f555] -- Time elapsed: 0.026 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.loadRecord[type:SMALLINT, mappingType:2, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$722/0x0000000800326440@502f8b57, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$723/0x0000000800325840@5652f555] -- Time elapsed: 0.034 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.loadRecord[type:INTEGER, mappingType:3, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$724/0x0000000800325c40@4fe01805, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$725/0x0000000800325040@55120f99] -- Time elapsed: 0.039 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.storeRecord[type:INTEGER, mappingType:3, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$724/0x0000000800325c40@4fe01805, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$725/0x0000000800325040@55120f99] -- Time elapsed: 0.033 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.storeRecord[type:BIGINT, mappingType:4, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$726/0x0000000800325440@794b435f, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$727/0x0000000800324840@38f2e97e] -- Time elapsed: 0.050 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.loadRecord[type:BIGINT, mappingType:4, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$726/0x0000000800325440@794b435f, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$727/0x0000000800324840@38f2e97e] -- Time elapsed: 0.067 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.loadRecord[type:DECIMAL (10,5), mappingType:1.12345, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$728/0x0000000800324c40@779dfe55, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$729/0x0000000800324040@323659f8] -- Time elapsed: 0.064 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.storeRecord[type:DECIMAL (10,5), mappingType:1.12345, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$728/0x0000000800324c40@779dfe55, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$729/0x0000000800324040@323659f8] -- Time elapsed: 0.046 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.loadRecord[type:REAL, mappingType:1.5, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$730/0x0000000800324440@1144a55a, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$731/0x0000000800323840@3e521715] -- Time elapsed: 0.037 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.storeRecord[type:REAL, mappingType:1.5, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$730/0x0000000800324440@1144a55a, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$731/0x0000000800323840@3e521715] -- Time elapsed: 0.041 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.loadRecord[type:DOUBLE, mappingType:1.8, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$732/0x0000000800323c40@26a529dc, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$733/0x0000000800330040@265c5d69] -- Time elapsed: 0.039 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.storeRecord[type:DOUBLE, mappingType:1.8, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$732/0x0000000800323c40@26a529dc, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$733/0x0000000800330040@265c5d69] -- Time elapsed: 0.044 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.loadRecord[type:DATE, mappingType:'2022-12-30', value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$734/0x0000000800330440@1286528d, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$735/0x0000000800330840@3cc20577] -- Time elapsed: 0.051 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.storeRecord[type:DATE, mappingType:'2022-12-30', value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$734/0x0000000800330440@1286528d, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$735/0x0000000800330840@3cc20577] [...]

2023-08-30 14:37 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/20202/Hazelcast-pr-builder-20202.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/20202/Hazelcast-pr-builder-20202.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
---------ERRORS-----------
--------------------------
[ERROR] Tests run: 26, Failures: 0, Errors: 26, Skipped: 0, Time elapsed: 2.605 s <<< FAILURE! -- in com.hazelcast.mapstore.AllTypesGenericMapStoreTest
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.loadRecord[type:VARCHAR(100), mappingType:'dummy', value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$715/0x0000000800327840@907f2b7, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$716/0x0000000800327c40@435ce306] -- Time elapsed: 1.185 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.storeRecord[type:VARCHAR(100), mappingType:'dummy', value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$715/0x0000000800327840@907f2b7, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$716/0x0000000800327c40@435ce306] -- Time elapsed: 0.072 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.storeRecord[type:BOOLEAN, mappingType:TRUE, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$717/0x0000000800327040@75699e35, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$718/0x0000000800327440@107e5441] -- Time elapsed: 0.037 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.loadRecord[type:BOOLEAN, mappingType:TRUE, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$717/0x0000000800327040@75699e35, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$718/0x0000000800327440@107e5441] -- Time elapsed: 0.049 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.loadRecord[type:TINYINT, mappingType:1, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$719/0x0000000800326840@4aeaadc1, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$720/0x0000000800326c40@263558c9] -- Time elapsed: 0.047 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.storeRecord[type:TINYINT, mappingType:1, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$719/0x0000000800326840@4aeaadc1, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$720/0x0000000800326c40@263558c9] -- Time elapsed: 0.038 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.storeRecord[type:SMALLINT, mappingType:2, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$721/0x0000000800326040@1f14f20c, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$722/0x0000000800326440@7daa61f3] -- Time elapsed: 0.034 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.loadRecord[type:SMALLINT, mappingType:2, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$721/0x0000000800326040@1f14f20c, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$722/0x0000000800326440@7daa61f3] -- Time elapsed: 0.046 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.storeRecord[type:INTEGER, mappingType:3, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$723/0x0000000800325840@62315f22, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$724/0x0000000800325c40@6e4ea0bd] -- Time elapsed: 0.036 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.loadRecord[type:INTEGER, mappingType:3, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$723/0x0000000800325840@62315f22, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$724/0x0000000800325c40@6e4ea0bd] -- Time elapsed: 0.030 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.storeRecord[type:BIGINT, mappingType:4, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$725/0x0000000800325040@56f2bbea, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$726/0x0000000800325440@78f9ed3e] -- Time elapsed: 0.037 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.loadRecord[type:BIGINT, mappingType:4, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$725/0x0000000800325040@56f2bbea, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$726/0x0000000800325440@78f9ed3e] -- Time elapsed: 0.019 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.storeRecord[type:DECIMAL (10,5), mappingType:1.12345, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$727/0x0000000800324840@1059754c, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$728/0x0000000800324c40@b0964b2] -- Time elapsed: 0.029 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.loadRecord[type:DECIMAL (10,5), mappingType:1.12345, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$727/0x0000000800324840@1059754c, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$728/0x0000000800324c40@b0964b2] -- Time elapsed: 0.038 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.storeRecord[type:REAL, mappingType:1.5, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$729/0x0000000800324040@48e7b3d2, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$730/0x0000000800324440@7f4037ed] -- Time elapsed: 0.035 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.loadRecord[type:REAL, mappingType:1.5, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$729/0x0000000800324040@48e7b3d2, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$730/0x0000000800324440@7f4037ed] -- Time elapsed: 0.024 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.storeRecord[type:DOUBLE, mappingType:1.8, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$731/0x0000000800323840@24e8de5c, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$732/0x0000000800323c40@64040287] -- Time elapsed: 0.046 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.loadRecord[type:DOUBLE, mappingType:1.8, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$731/0x0000000800323840@24e8de5c, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$732/0x0000000800323c40@64040287] -- Time elapsed: 0.025 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.storeRecord[type:DATE, mappingType:'2022-12-30', value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$733/0x0000000800323040@110844f6, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$734/0x0000000800323440@6f89f665] -- Time elapsed: 0.029 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.loadRecord[type:DATE, mappingType:'2022-12-30', value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$733/0x0000000800323040@110844f6, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$734/0x0000000800323440@6f89f665] - [...]

2023-08-31 10:12 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/20223/Hazelcast-pr-builder-20223.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/20223/Hazelcast-pr-builder-20223.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
---------ERRORS-----------
--------------------------
[ERROR] Tests run: 26, Failures: 0, Errors: 26, Skipped: 0, Time elapsed: 2.748 s <<< FAILURE! -- in com.hazelcast.mapstore.AllTypesGenericMapStoreTest
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.loadRecord[type:VARCHAR(100), mappingType:'dummy', value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$716/0x000000080032f840@1b812421, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$717/0x000000080032fc40@5d28bcd5] -- Time elapsed: 1.207 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.storeRecord[type:VARCHAR(100), mappingType:'dummy', value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$716/0x000000080032f840@1b812421, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$717/0x000000080032fc40@5d28bcd5] -- Time elapsed: 0.055 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.loadRecord[type:BOOLEAN, mappingType:TRUE, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$718/0x000000080032f040@3887cf88, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$719/0x000000080032f440@5649ec46] -- Time elapsed: 0.036 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.storeRecord[type:BOOLEAN, mappingType:TRUE, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$718/0x000000080032f040@3887cf88, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$719/0x000000080032f440@5649ec46] -- Time elapsed: 0.035 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.storeRecord[type:TINYINT, mappingType:1, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$720/0x000000080032e840@78dc4696, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$721/0x000000080032ec40@502f8b57] -- Time elapsed: 0.036 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.loadRecord[type:TINYINT, mappingType:1, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$720/0x000000080032e840@78dc4696, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$721/0x000000080032ec40@502f8b57] -- Time elapsed: 0.047 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.storeRecord[type:SMALLINT, mappingType:2, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$722/0x000000080032e040@5652f555, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$723/0x000000080032e440@4fe01805] -- Time elapsed: 0.034 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.loadRecord[type:SMALLINT, mappingType:2, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$722/0x000000080032e040@5652f555, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$723/0x000000080032e440@4fe01805] -- Time elapsed: 0.028 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.loadRecord[type:INTEGER, mappingType:3, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$724/0x000000080032d840@55120f99, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$725/0x000000080032dc40@794b435f] -- Time elapsed: 0.063 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.storeRecord[type:INTEGER, mappingType:3, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$724/0x000000080032d840@55120f99, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$725/0x000000080032dc40@794b435f] -- Time elapsed: 0.045 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.storeRecord[type:BIGINT, mappingType:4, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$726/0x000000080032d040@38f2e97e, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$727/0x000000080032d440@779dfe55] -- Time elapsed: 0.049 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.loadRecord[type:BIGINT, mappingType:4, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$726/0x000000080032d040@38f2e97e, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$727/0x000000080032d440@779dfe55] -- Time elapsed: 0.048 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.storeRecord[type:DECIMAL (10,5), mappingType:1.12345, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$728/0x000000080032c840@323659f8, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$729/0x000000080032cc40@1144a55a] -- Time elapsed: 0.014 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.loadRecord[type:DECIMAL (10,5), mappingType:1.12345, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$728/0x000000080032c840@323659f8, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$729/0x000000080032cc40@1144a55a] -- Time elapsed: 0.021 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.loadRecord[type:REAL, mappingType:1.5, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$730/0x000000080032c040@3e521715, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$731/0x000000080032c440@26a529dc] -- Time elapsed: 0.053 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.storeRecord[type:REAL, mappingType:1.5, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$730/0x000000080032c040@3e521715, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$731/0x000000080032c440@26a529dc] -- Time elapsed: 0.054 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.storeRecord[type:DOUBLE, mappingType:1.8, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$732/0x000000080032b840@265c5d69, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$733/0x000000080032bc40@1286528d] -- Time elapsed: 0.025 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.loadRecord[type:DOUBLE, mappingType:1.8, value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$732/0x000000080032b840@265c5d69, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$733/0x000000080032bc40@1286528d] -- Time elapsed: 0.036 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.storeRecord[type:DATE, mappingType:'2022-12-30', value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$734/0x0000000800338040@3cc20577, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$735/0x0000000800338440@33a630fa] -- Time elapsed: 0.041 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.mapstore.AllTypesGenericMapStoreTest.loadRecord[type:DATE, mappingType:'2022-12-30', value:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$734/0x0000000800338040@3cc20577, expected:com.hazelcast.mapstore.AllTypesGenericMapStoreTest$$Lambda$735/0x0000000800338440@33a630f [...]

2023-09-05 09:08 UTC, k-jamroz approved these changes

2023-09-05 09:14 UTC, frant-hartm requested changes

2023-09-05 09:14 UTC, frant-hartm commented on distribution/pom.xml
> +            </exclusions>
This shouldn't be here. 

If the dependencyConvergence reports a version mismatch, you should define the correct version in the root pom in `depencencyManagement` section (which you already have).

2023-09-05 12:12 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder-ee-tests` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder-ee-tests/109/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder-ee-tests/109/Hazelcast-pr-builder-ee-tests-109.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
---------ERRORS-----------
--------------------------
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 6.601 s <<< FAILURE! -- in com.hazelcast.wan.WanSplitBrainReplicationTest
--------------------------
[ERROR] com.hazelcast.wan.WanSplitBrainReplicationTest.testSplitBrain -- Time elapsed: 6.599 s <<< FAILURE!
--------------------------
[ERROR] Failures: 
--------------------------
[ERROR]   WanSplitBrainReplicationTest>SplitBrainTestSupport.testSplitBrain:195->SplitBrainTestSupport.doIteration:207->onAfterSplitBrainHealed:95 Expected 11 published WAN events expected:<11> but was:<12>
--------------------------
[ERROR] Tests run: 9786, Failures: 1, Errors: 0, Skipped: 69
--------------------------
[ERROR] There are test failures.
--------------------------
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   WanSplitBrainReplicationTest>SplitBrainTestSupport.testSplitBrain:195->SplitBrainTestSupport.doIteration:207->onAfterSplitBrainHealed:95 Expected 11 published WAN events expected:<11> but was:<12>
[INFO] 
[ERROR] Tests run: 9786, Failures: 1, Errors: 0, Skipped: 69
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2023-09-07 10:56 UTC, frant-hartm approved these changes

2023-09-07 11:12 UTC, merged