Fix KafkaConnectIntegrationTest.test_reading_and_writing_to_map test
hazelcast/hazelcast pull request #25424
Opened 2023-09-13 06:12 UTC by orcunc

The test is downloading the DataGen connector zip file from JFrog. In one of the test runs it failed with error message :
 java.net.SocketException: Connection reset

 It would be better to have the connector zip as local resource to avoid download failures in the future  [HZ-3116]

Fixes : https://github.com/hazelcast/hazelcast/issues/24905

Breaking changes (list specific methods/types/messages):
* API
* client protocol format
* serialized form
* snapshot format

Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [x] Label `Add to Release Notes` or `Not Release Notes content` set
- [x] Request reviewers if possible

2023-09-13 11:53 UTC, TomaszGaweda requested changes
I don't really like copying dependencies into the project.

In hazelcast3 connector we had a trick, that we used Maven to download the jars and then use it locally. We can do the same for KafkaConnect ITs, just:
- make it so that it's automated
- implement for all tests

2023-09-16 05:52 UTC, hz-devops-test commented
The job `Hazelcast-pr-EE-compiler` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-EE-compiler/9282/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-EE-compiler/9282/Hazelcast-pr-EE-compiler-9282.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>

</pre>
</details>

2023-09-16 06:52 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/20542/Hazelcast-pr-builder-20542.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/20542/Hazelcast-pr-builder-20542.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Tests run: 6, Failures: 1, Errors: 4, Skipped: 1, Time elapsed: 13.39 s <<< FAILURE! -- in com.hazelcast.jet.kafka.connect.KafkaConnectIntegrationTest
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] Tests run: 6, Failures: 1, Errors: 4, Skipped: 1, Time elapsed: 13.39 s <<< FAILURE! -- in com.hazelcast.jet.kafka.connect.KafkaConnectIntegrationTest
--------------------------
[ERROR] com.hazelcast.jet.kafka.connect.KafkaConnectIntegrationTest.windowing_withIngestionTimestamps_should_work -- Time elapsed: 5.212 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.jet.kafka.connect.KafkaConnectIntegrationTest.test_reading_without_timestamps -- Time elapsed: 0.533 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.jet.kafka.connect.KafkaConnectIntegrationTest.test_snapshotting -- Time elapsed: 0.661 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.jet.kafka.connect.KafkaConnectIntegrationTest.test_reading_and_writing_to_map -- Time elapsed: 0.340 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.jet.kafka.connect.KafkaConnectIntegrationTest.windowing_withNativeTimestamps_should_fail_when_records_without_native_timestamps -- Time elapsed: 0.362 s <<< FAILURE!
--------------------------
[ERROR] Failures: 
--------------------------
[ERROR]   KafkaConnectIntegrationTest.windowing_withNativeTimestamps_should_fail_when_records_without_native_timestamps:168 
--------------------------
[ERROR] Errors: 
--------------------------
[ERROR]   KafkaConnectIntegrationTest.test_reading_and_writing_to_map:238 ? Jet Job resource upload failed
--------------------------
[ERROR]   KafkaConnectIntegrationTest.test_reading_without_timestamps:122 ? Jet Job resource upload failed
--------------------------
[ERROR]   KafkaConnectIntegrationTest.test_snapshotting:378 ? Jet Job resource upload failed
--------------------------
[ERROR]   KafkaConnectIntegrationTest.windowing_withIngestionTimestamps_should_work:199 ? Jet Job resource upload failed
--------------------------
[ERROR] Tests run: 36, Failures: 1, Errors: 4, Skipped: 1
--------------------------
[ERROR] There are test failures.
--------------------------
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   KafkaConnectIntegrationTest.windowing_withNativeTimestamps_should_fail_when_records_without_native_timestamps:168 
Expecting actual throwable to be an instance of:
  java.util.concurrent.CompletionException
but was:
  com.hazelcast.jet.JetException: Job resource upload failed
	at com.hazelcast.jet.impl.JobRepository.uploadJobResources(JobRepository.java:261)
	at com.hazelcast.jet.impl.AbstractJetInstance.uploadResources(AbstractJetInstance.java:344)
	at com.hazelcast.jet.impl.AbstractJetInstance.newJobInt(AbstractJetInstance.java:142)
	...(19 remaining lines not displayed - this can be changed with Assertions.setMaxStackTraceElementsDisplayed)
[ERROR] Errors: 
[ERROR]   KafkaConnectIntegrationTest.test_reading_and_writing_to_map:238 ? Jet Job resource upload failed
[ERROR]   KafkaConnectIntegrationTest.test_reading_without_timestamps:122 ? Jet Job resource upload failed
[ERROR]   KafkaConnectIntegrationTest.test_snapshotting:378 ? Jet Job resource upload failed
[ERROR]   KafkaConnectIntegrationTest.windowing_withIngestionTimestamps_should_work:199 ? Jet Job resource upload failed
[INFO] 
[ERROR] Tests run: 36, Failures: 1, Errors: 4, Skipped: 1
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2023-09-18 06:46 UTC, orcunc commented
The confluentinc-kafka-connect-datagen is not available on maven central. But we have in on JFrog. download-maven-plugin is going to download and cache it at ${local-repo}/.cache/maven-download-plugin

Documentation is : https://maven-download-plugin.github.io/maven-download-plugin/docsite/1.7.1/wget-mojo.html

2023-09-19 08:14 UTC, ldziedziul commented on extensions/kafka-connect/pom.xml
> +    <repositories>
Do we need that?

2023-09-19 08:14 UTC, ldziedziul commented on extensions/kafka-connect/pom.xml
> +        <dependency>
Do we need it?

2023-09-19 12:58 UTC, TomaszGaweda approved these changes

2023-09-21 07:16 UTC, ldziedziul approved these changes

2023-09-21 08:10 UTC, merged