Disable host name verification when creating http client.  [HZ-3087]
hazelcast/hazelcast pull request #25435
Opened 2023-09-13 15:35 UTC by orcunc

When converting from Apache to Java Http client the disabling host name verification was overlooked. It was causing test failures when using self signed certificates.

Breaking changes (list specific methods/types/messages):
* API
* client protocol format
* serialized form
* snapshot format

Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [x] Label `Add to Release Notes` or `Not Release Notes content` set
- [x] Request reviewers if possible

2023-09-13 20:05 UTC, kwart commented
run-ee-tests

2023-09-13 20:05 UTC, kwart commented
run-ee-nightly-tests

2023-09-13 20:17 UTC, kwart requested changes
I think the proper way is to have the hostname verification enabled here and fix it by disabling the verification on the test-class level. Only when it's needed.

2023-09-13 23:23 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder-ee-tests` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder-ee-tests/111/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder-ee-tests/111/Hazelcast-pr-builder-ee-tests-111.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
---------ERRORS-----------
--------------------------
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 6.121 s <<< FAILURE! -- in com.hazelcast.wan.WanSplitBrainReplicationTest
--------------------------
[ERROR] com.hazelcast.wan.WanSplitBrainReplicationTest.testSplitBrain -- Time elapsed: 6.117 s <<< FAILURE!
--------------------------
[ERROR] Tests run: 5, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 858.8 s <<< FAILURE! -- in com.hazelcast.internal.tstore.compaction.PartitionCompactorTest
--------------------------
[ERROR] com.hazelcast.internal.tstore.compaction.PartitionCompactorTest.test_partition_compactor_with_index_on_owner_and_backup -- Time elapsed: 302.2 s <<< ERROR!
--------------------------
[ERROR] com.hazelcast.internal.tstore.compaction.PartitionCompactorTest.test_partition_compactor_with_null_index_on_owner_and_backup -- Time elapsed: 312.0 s <<< ERROR!
--------------------------
[ERROR] Failures: 
--------------------------
[ERROR]   WanSplitBrainReplicationTest>SplitBrainTestSupport.testSplitBrain:195->SplitBrainTestSupport.doIteration:207->onAfterSplitBrainHealed:95 Expected 11 published WAN events expected:<11> but was:<12>
--------------------------
[ERROR] Errors: 
--------------------------
[ERROR]   PartitionCompactorTest.test_partition_compactor_with_index_on_owner_and_backup:149 ? TestTimedOut test timed out after 300000 milliseconds
--------------------------
[ERROR]   PartitionCompactorTest.test_partition_compactor_with_null_index_on_owner_and_backup:205 ? TestTimedOut test timed out after 300000 milliseconds
--------------------------
[ERROR] Tests run: 9870, Failures: 1, Errors: 2, Skipped: 70
--------------------------
[ERROR] There are test failures.
--------------------------
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   WanSplitBrainReplicationTest>SplitBrainTestSupport.testSplitBrain:195->SplitBrainTestSupport.doIteration:207->onAfterSplitBrainHealed:95 Expected 11 published WAN events expected:<11> but was:<12>
[ERROR] Errors: 
[ERROR]   PartitionCompactorTest.test_partition_compactor_with_index_on_owner_and_backup:149 ? TestTimedOut test timed out after 300000 milliseconds
[ERROR]   PartitionCompactorTest.test_partition_compactor_with_null_index_on_owner_and_backup:205 ? TestTimedOut test timed out after 300000 milliseconds
[INFO] 
[ERROR] Tests run: 9870, Failures: 1, Errors: 2, Skipped: 70
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2023-09-14 09:18 UTC, orcunc commented
Closing in favor of https://github.com/hazelcast/hazelcast/pull/25434

2023-09-14 09:18 UTC, closed without merging