Remove wiremock-jre8-standalone dependency and upgrade to wiremock [HZ-3113]
hazelcast/hazelcast pull request #25586
Opened 2023-10-02 09:35 UTC by orcunc

Upgrade wiremock dependency to wiremock-standalone:3.0.1

With the new dependency the apache commons library is not available anymore. Fix the tests that use apache commons IOUtils [HZ-3113]

Jira : https://hazelcast.atlassian.net/browse/HZ-3113

Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [x] Label `Add to Release Notes` or `Not Release Notes content` set
- [x] Request reviewers if possible

2023-10-02 10:38 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/20860/Hazelcast-pr-builder-20860.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/20860/Hazelcast-pr-builder-20860.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
---------ERRORS-----------
--------------------------
[ERROR] Tests run: 28, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 235.2 s <<< FAILURE! -- in com.hazelcast.jet.kafka.impl.StreamKafkaPTest
--------------------------
[ERROR] com.hazelcast.jet.kafka.impl.StreamKafkaPTest.when_processingGuaranteeNoneWithConsumerGroup_then_continueFromLastReadMessageAfterJobRestart -- Time elapsed: 121.3 s <<< FAILURE!
--------------------------
[ERROR] Failures: 
--------------------------
[ERROR]   StreamKafkaPTest.when_processingGuaranteeNoneWithConsumerGroup_then_continueFromLastReadMessageAfterJobRestart:266->testWithJobRestart:345->HazelcastTestSupport.assertTrueEventually:1269->HazelcastTestSupport.assertTrueEventually:1165->lambda$testWithJobRestart$4:345 expected:<200> but was:<199>
--------------------------
[ERROR] Tests run: 51, Failures: 1, Errors: 0, Skipped: 0
--------------------------
[ERROR] There are test failures.
--------------------------
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   StreamKafkaPTest.when_processingGuaranteeNoneWithConsumerGroup_then_continueFromLastReadMessageAfterJobRestart:266->testWithJobRestart:345->HazelcastTestSupport.assertTrueEventually:1269->HazelcastTestSupport.assertTrueEventually:1165->lambda$testWithJobRestart$4:345 expected:<200> but was:<199>
[INFO] 
[ERROR] Tests run: 51, Failures: 1, Errors: 0, Skipped: 0
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2023-10-02 11:11 UTC, orcunc commented
run-lab-run

2023-10-02 12:14 UTC, JackPGreen requested changes

2023-10-02 12:14 UTC, JackPGreen commented on hazelcast/src/test/java/com/hazelcast/jet/impl/deployment/ChildFirstClassLoaderTest.java
> -import org.apache.commons.io.IOUtils;
I don't think this is any better (personally).

2023-10-02 12:45 UTC, JackPGreen commented on hazelcast/src/test/java/com/hazelcast/jet/impl/deployment/ChildFirstClassLoaderTest.java
> -import org.apache.commons.io.IOUtils;
> So we don't have Apache Commons IO anymore. I had to change the tests.

Ok - that makes sense, but is also a shame as it avoids a lot of boilerplate.

2023-10-03 11:38 UTC, orcunc commented
@JamesHazelcast can you look at this PR please when you have time. Thanks

2023-10-03 12:42 UTC, JamesHazelcast approved these changes
LGTM, thanks @orcunc, apologies for the delay

2023-10-03 12:43 UTC, merged