Update 5.3.z SNAPSHOT version to 5.3.6 [5.3.z]
hazelcast/hazelcast pull request #25831
Opened 2023-10-24 16:58 UTC by nishaatr

We have skipped 5.3.3 and 5.3.4 and released 5.3.5 instead. This change will ensure next release (5.3.6) is properly created from 5.3.z

Fixes: [HZ-3546]

Checklist:
- [ ] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [ ] Add `Add to Release Notes` label if changes should be mentioned in release notes or `Not Release Notes content` if changes are not relevant for release notes
- [ ] Request reviewers if possible
- [ ] New public APIs have `@Nonnull/@Nullable` annotations
- [ ] New public APIs have `@since` tags in Javadoc
- [ ] Send backports/forwardports if fix needs to be applied to past/future releases

2023-10-24 16:59 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/21385/Hazelcast-pr-builder-21385.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/21385/Hazelcast-pr-builder-21385.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
---------ERRORS-----------
--------------------------
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
--------------------------
[ERROR] The build could not read 10 projects -> [Help 1]
--------------------------
[ERROR]   
--------------------------
[ERROR]   The project com.hazelcast:hazelcast-tpc-engine:5.3.4-SNAPSHOT (/home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_2/hazelcast-tpc-engine/pom.xml) has 1 error
--------------------------
[ERROR]     Non-resolvable parent POM for com.hazelcast:hazelcast-tpc-engine:5.3.4-SNAPSHOT: The following artifacts could not be resolved: com.hazelcast:hazelcast-root:pom:5.3.4-SNAPSHOT (absent): Could not find artifact com.hazelcast:hazelcast-root:pom:5.3.4-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 28, column 13 -> [Help 2]
--------------------------
[ERROR]   
--------------------------
[ERROR]   The project com.hazelcast:hazelcast:5.3.4-SNAPSHOT (/home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_2/hazelcast/pom.xml) has 1 error
--------------------------
[ERROR]     Non-resolvable parent POM for com.hazelcast:hazelcast:5.3.4-SNAPSHOT: The following artifacts could not be resolved: com.hazelcast:hazelcast-root:pom:5.3.4-SNAPSHOT (absent): Could not find artifact com.hazelcast:hazelcast-root:pom:5.3.4-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 26, column 13 -> [Help 2]
--------------------------
[ERROR]   
--------------------------
[ERROR]   The project com.hazelcast:hazelcast-archunit-rules:5.3.4-SNAPSHOT (/home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_2/hazelcast-archunit-rules/pom.xml) has 1 error
--------------------------
[ERROR]     Non-resolvable parent POM for com.hazelcast:hazelcast-archunit-rules:5.3.4-SNAPSHOT: The following artifacts could not be resolved: com.hazelcast:hazelcast-root:pom:5.3.4-SNAPSHOT (absent): Could not find artifact com.hazelcast:hazelcast-root:pom:5.3.4-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 25, column 13 -> [Help 2]
--------------------------
[ERROR]   
--------------------------
[ERROR]   The project com.hazelcast:hazelcast-spring:5.3.4-SNAPSHOT (/home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_2/hazelcast-spring/pom.xml) has 1 error
--------------------------
[ERROR]     Non-resolvable parent POM for com.hazelcast:hazelcast-spring:5.3.4-SNAPSHOT: The following artifacts could not be resolved: com.hazelcast:hazelcast-root:pom:5.3.4-SNAPSHOT (absent): Could not find artifact com.hazelcast:hazelcast-root:pom:5.3.4-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 25, column 13 -> [Help 2]
--------------------------
[ERROR]   
--------------------------
[ERROR]   The project com.hazelcast:hazelcast-spring-tests:5.3.4-SNAPSHOT (/home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_2/hazelcast-spring-tests/pom.xml) has 1 error
--------------------------
[ERROR]     Non-resolvable parent POM for com.hazelcast:hazelcast-spring-tests:5.3.4-SNAPSHOT: The following artifacts could not be resolved: com.hazelcast:hazelcast-root:pom:5.3.4-SNAPSHOT (absent): Could not find artifact com.hazelcast:hazelcast-root:pom:5.3.4-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 25, column 13 -> [Help 2]
--------------------------
[ERROR]   
--------------------------
[ERROR]   The project com.hazelcast:hazelcast-build-utils:5.3.4-SNAPSHOT (/home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_2/hazelcast-build-utils/pom.xml) has 1 error
--------------------------
[ERROR]     Non-resolvable parent POM for com.hazelcast:hazelcast-build-utils:5.3.4-SNAPSHOT: The following artifacts could not be resolved: com.hazelcast:hazelcast-root:pom:5.3.4-SNAPSHOT (absent): Could not find artifact com.hazelcast:hazelcast-root:pom:5.3.4-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 25, column 13 -> [Help 2]
--------------------------
[ERROR]   
--------------------------
[ERROR]   The project com.hazelcast:hazelcast-sql:5.3.4-SNAPSHOT (/home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_2/hazelcast-sql/pom.xml) has 1 error
--------------------------
[ERROR]     Non-resolvable parent POM for com.hazelcast:hazelcast-sql:5.3.4-SNAPSHOT: The following artifacts could not be resolved: com.hazelcast:hazelcast-root:pom:5.3.4-SNAPSHOT (absent): Could not find artifact com.hazelcast:hazelcast-root:pom:5.3.4-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 28, column 13 -> [Help 2]
--------------------------
[ERROR]   
--------------------------
[ERROR]   The project com.hazelcast.jet:hazelcast-jet-extensions:5.3.4-SNAPSHOT (/home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_2/extensions/pom.xml) has 1 error
--------------------------
[ERROR]     Non-resolvable parent POM for com.hazelcast.jet:hazelcast-jet-extensions:5.3.4-SNAPSHOT: The following artifacts could not be resolved: com.hazelcast:hazelcast-root:pom:5.3.4-SNAPSHOT (absent): Could not find artifact com.hazelcast:hazelcast-root:pom:5.3.4-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 30, column 13 -> [Help 2]
--------------------------
[ERROR]   
--------------------------
[ERROR]   The project com.hazelcast:hazelcast-distribution:5.3.4-SNAPSHOT (/home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_2/distribution/pom.xml) has 1 error
--------------------------
[ERROR]     Non-resolvable parent POM for com.hazelcast:hazelcast-distribution:5.3.4-SNAPSHOT: The following artifacts could not be resolved: com.hazelcast:hazelcast-root:pom:5.3.4-SNAPSHOT (absent): Could not find artifact com.hazelcast:hazelcast-root:pom:5.3.4-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 21, column 13 -> [Help 2]
--------------------------
[ERROR]   
--------------------------
[ERROR]   The project com.hazelcast:hazelcast-it:5.3.4-SNAPSHOT (/home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_2/hazelcast-it/pom.xml) has 1 error
--------------------------
[ERROR]     Non-resolvable parent POM for com.hazelcast:hazelcast-it:5.3.4-SNAPSHOT: The following artifacts could not be resolved: com.hazelcast:hazelcast-root:pom:5.3.4-SNAPSHOT (absent): Could not find artifact com.hazelcast:hazelcast-root:pom:5.3.4-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 22, column 13 -> [Help 2]
--------------------------
[ERROR] 
--------------------------
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
--------------------------
[ERROR] 
--------------------------
[ERROR] For more information about the errors and possible solutions, please read the following articles:
--------------------------
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
--------------------------
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
--------------------------
</pre>
</details>

2023-10-24 17:16 UTC, JackPGreen approved these changes

2023-10-25 07:57 UTC, olukas requested changes
There are much more places in the repo where the version needs to be updated.

2023-10-25 08:54 UTC, nishaatr commented
> There are much more places in the repo where the version needs to be updated.

Fixed. Ran below command

mvn -q -B versions:set -DgenerateBackupPoms=false -DnewVersion=5.3.6-SNAPSHOT -N

2023-10-25 08:57 UTC, olukas approved these changes

2023-10-25 10:00 UTC, merged