GenericMapStore: Single column as value [HZ-1568]
hazelcast/hazelcast pull request #25878
Opened 2023-10-31 17:17 UTC by Edizc

INSERT_PR_DESCRIPTION_HERE

Fixes INSERT_LINK_TO_THE_ISSUE_HERE

Backport of: INSERT_LINK_TO_THE_ORIGINAL_PR_HERE

EE PR: INSERT_LINK_TO_THE_EE_PR_HERE

Breaking changes (list specific methods/types/messages):
* API
* client protocol format
* serialized form
* snapshot format

Checklist:
- [ ] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [ ] Add `Add to Release Notes` label if changes should be mentioned in release notes or `Not Release Notes content` if changes are not relevant for release notes
- [ ] Request reviewers if possible
- [ ] New public APIs have `@Nonnull/@Nullable` annotations
- [ ] New public APIs have `@since` tags in Javadoc
- [ ] Send backports/forwardports if fix needs to be applied to past/future releases

2023-10-31 17:20 UTC, Edizc commented
I made superficial changes to JdbcSqlTestSupport and GenericMapStoreIntegrationTest to make sure my implementation was working correctly. I am more than happy to change these according to your feedback. Additional changes are needed for the GenericMapStoreTest and GenericMapLoaderTest etc. but I intend to do them after #25730 is merged.

2023-10-31 17:23 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/21501/Hazelcast-pr-builder-21501.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/21501/Hazelcast-pr-builder-21501.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/extensions/mapstore/src/main/java/com/hazelcast/mapstore/GenericMapLoader.java:31:8: Unused import - com.hazelcast.nio.serialization.genericrecord.GenericRecord. [UnusedImports]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/extensions/mapstore/src/main/java/com/hazelcast/mapstore/GenericMapLoader.java:90:1: Type Javadoc comment is missing @param <V> tag. [JavadocType]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/extensions/mapstore/src/main/java/com/hazelcast/mapstore/GenericMapStore.java:22:8: Unused import - com.hazelcast.nio.serialization.genericrecord.GenericRecord. [UnusedImports]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/extensions/mapstore/src/main/java/com/hazelcast/mapstore/GenericMapStore.java:63:1: Type Javadoc comment is missing @param <V> tag. [JavadocType]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/extensions/mapstore/src/test/java/org/example/Person.java:68:32: '+' is not followed by whitespace. [WhitespaceAround]
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.3.1:checkstyle (default) on project hazelcast-mapstore: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There are 5 errors reported by Checkstyle 9.3 with /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/extensions/mapstore/../../checkstyle/checkstyle_jet.xml ruleset. -> [Help 1]
--------------------------
[ERROR] 
--------------------------
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
--------------------------
[ERROR] 
--------------------------
[ERROR] For more information about the errors and possible solutions, please read the following articles:
--------------------------
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
--------------------------
[ERROR] 
--------------------------
[ERROR] After correcting the problems, you can resume the build with the command
--------------------------
[ERROR]   mvn <args> -rf :hazelcast-mapstore
--------------------------
</pre>
</details>

2023-10-31 17:27 UTC, hz-devops-test commented
The job `Hazelcast-pr-EE-compiler` of your PR failed. (Hazelcast internal details: [build log](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-EE-compiler/10195/Hazelcast-pr-EE-compiler-10195.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-EE-compiler/10195/Hazelcast-pr-EE-compiler-10195.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] COMPILATION ERROR : 
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[59,28] wrong number of type arguments; required 2
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] COMPILATION ERROR : 
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[59,28] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[379,32] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[383,32] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[389,32] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[394,34] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[67,29] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[567,33] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[571,33] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[577,33] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[581,35] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/AllTypesGenericMapStoreTest.java:[70,28] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[136,25] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[146,25] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[184,25] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[586,25] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[134,24] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[144,24] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[398,24] wrong number of type arguments; required 2
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:testCompile (default-testCompile) on project hazelcast-mapstore: Compilation failure: Compilation failure: 
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[59,28] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[379,32] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[383,32] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[389,32] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[394,34] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[67,29] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[567,33] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[571,33] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[577,33] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[581,35] wrong number of  [...]

2023-10-31 17:30 UTC, hz-devops-test commented
The job `Hazelcast-pr-compiler` of your PR failed. (Hazelcast internal details: [build log](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-compiler/10772/Hazelcast-pr-compiler-10772.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-compiler/10772/Hazelcast-pr-compiler-10772.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
---------ERRORS-----------
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mapstore/src/main/java/com/hazelcast/mapstore/GenericMapStore.java:22:8: Unused import - com.hazelcast.nio.serialization.genericrecord.GenericRecord. [UnusedImports]
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mapstore/src/main/java/com/hazelcast/mapstore/GenericMapStore.java:63:1: Type Javadoc comment is missing @param <V> tag. [JavadocType]
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mapstore/src/main/java/com/hazelcast/mapstore/GenericMapLoader.java:31:8: Unused import - com.hazelcast.nio.serialization.genericrecord.GenericRecord. [UnusedImports]
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mapstore/src/main/java/com/hazelcast/mapstore/GenericMapLoader.java:90:1: Type Javadoc comment is missing @param <V> tag. [JavadocType]
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mapstore/src/test/java/org/example/Person.java:68:32: '+' is not followed by whitespace. [WhitespaceAround]
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.3.1:checkstyle (default) on project hazelcast-mapstore: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There are 5 errors reported by Checkstyle 9.3 with /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mapstore/../../checkstyle/checkstyle_jet.xml ruleset. -> [Help 1]
--------------------------
[ERROR] 
--------------------------
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
--------------------------
[ERROR] 
--------------------------
[ERROR] For more information about the errors and possible solutions, please read the following articles:
--------------------------
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
--------------------------
[ERROR] 
--------------------------
[ERROR] After correcting the problems, you can resume the build with the command
--------------------------
[ERROR]   mvn <args> -rf :hazelcast-mapstore
--------------------------
</pre>
</details>

2023-11-07 08:01 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/21585/Hazelcast-pr-builder-21585.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/21585/Hazelcast-pr-builder-21585.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] COMPILATION ERROR : 
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[59,28] wrong number of type arguments; required 2
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] COMPILATION ERROR : 
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[59,28] wrong number of type arguments; required 2
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[379,32] wrong number of type arguments; required 2
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[383,32] wrong number of type arguments; required 2
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[389,32] wrong number of type arguments; required 2
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[394,34] wrong number of type arguments; required 2
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[67,29] wrong number of type arguments; required 2
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[567,33] wrong number of type arguments; required 2
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[571,33] wrong number of type arguments; required 2
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[577,33] wrong number of type arguments; required 2
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[581,35] wrong number of type arguments; required 2
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/extensions/mapstore/src/test/java/com/hazelcast/mapstore/AllTypesGenericMapStoreTest.java:[70,28] wrong number of type arguments; required 2
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[136,25] wrong number of type arguments; required 2
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[146,25] wrong number of type arguments; required 2
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[184,25] wrong number of type arguments; required 2
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[586,25] wrong number of type arguments; required 2
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[134,24] wrong number of type arguments; required 2
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[144,24] wrong number of type arguments; required 2
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[398,24] wrong number of type arguments; required 2
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:testCompile (default-testCompile) on project hazelcast-mapstore: Compilation failure: Compilation failure: 
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[59,28] wrong number of type arguments; required 2
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[379,32] wrong number of type arguments; required 2
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[383,32] wrong number of type arguments; required 2
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[389,32] wrong number of type arguments; required 2
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[394,34] wrong number of type arguments; required 2
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[67,29] wrong number of type arguments; required 2
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[567,33] wrong number of type arguments; required 2
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[571,33] wrong number of type arguments; required 2
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[577,33] wrong number of type arguments; required 2
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[581,35] wrong number of type arguments; required 2
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/extensions/mapstore/src/test/java/com/hazelcast/mapstore/AllTypesGenericMapStoreTest.java:[70,28] wrong number of type arguments; required 2
--------------------------
[ERROR] /appdisk/jenkins/jenkins_slave/workspac [...]

2023-11-07 08:05 UTC, hz-devops-test commented
The job `Hazelcast-pr-EE-compiler` of your PR failed. (Hazelcast internal details: [build log](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-EE-compiler/10284/Hazelcast-pr-EE-compiler-10284.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-EE-compiler/10284/Hazelcast-pr-EE-compiler-10284.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] COMPILATION ERROR : 
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[59,28] wrong number of type arguments; required 2
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] COMPILATION ERROR : 
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[59,28] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[379,32] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[383,32] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[389,32] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[394,34] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[67,29] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[567,33] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[571,33] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[577,33] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[581,35] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/AllTypesGenericMapStoreTest.java:[70,28] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[136,25] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[146,25] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[184,25] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[586,25] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[134,24] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[144,24] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[398,24] wrong number of type arguments; required 2
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:testCompile (default-testCompile) on project hazelcast-mapstore: Compilation failure: Compilation failure: 
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[59,28] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[379,32] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[383,32] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[389,32] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[394,34] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[67,29] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[567,33] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[571,33] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[577,33] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[581,35] wrong number of  [...]

2023-11-07 08:10 UTC, hz-devops-test commented
The job `Hazelcast-pr-compiler` of your PR failed. (Hazelcast internal details: [build log](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-compiler/10860/Hazelcast-pr-compiler-10860.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-compiler/10860/Hazelcast-pr-compiler-10860.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] COMPILATION ERROR : 
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[59,28] wrong number of type arguments; required 2
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] COMPILATION ERROR : 
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[59,28] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[379,32] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[383,32] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[389,32] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[394,34] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[67,29] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[567,33] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[571,33] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[577,33] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[581,35] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mapstore/src/test/java/com/hazelcast/mapstore/AllTypesGenericMapStoreTest.java:[70,28] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[136,25] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[146,25] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[184,25] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[586,25] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[134,24] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[144,24] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[398,24] wrong number of type arguments; required 2
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:testCompile (default-testCompile) on project hazelcast-mapstore: Compilation failure: Compilation failure: 
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[59,28] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[379,32] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[383,32] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[389,32] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[394,34] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[67,29] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[567,33] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[571,33] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[577,33] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[581,35] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mapstore/src/test/java/com/hazelcast/mapstore/AllTypesGenericMapStoreTest.java:[70,28] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mapstore/src/test/java/ [...]

2023-11-07 08:19 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/21586/Hazelcast-pr-builder-21586.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/21586/Hazelcast-pr-builder-21586.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/extensions/mapstore/src/main/java/com/hazelcast/mapstore/GenericMapStore.java:70: Line is longer than 123 characters (found 164). [LineLength]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/extensions/mapstore/src/main/java/com/hazelcast/mapstore/GenericMapStoreProperties.java:26:54: Using the '.*' form of import should be avoided - com.hazelcast.mapstore.GenericMapLoader.*. [AvoidStarImport]
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.3.1:checkstyle (default) on project hazelcast-mapstore: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There are 2 errors reported by Checkstyle 9.3 with /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/extensions/mapstore/../../checkstyle/checkstyle_jet.xml ruleset. -> [Help 1]
--------------------------
[ERROR] 
--------------------------
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
--------------------------
[ERROR] 
--------------------------
[ERROR] For more information about the errors and possible solutions, please read the following articles:
--------------------------
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
--------------------------
[ERROR] 
--------------------------
[ERROR] After correcting the problems, you can resume the build with the command
--------------------------
[ERROR]   mvn <args> -rf :hazelcast-mapstore
--------------------------
</pre>
</details>

2023-11-07 08:23 UTC, hz-devops-test commented
The job `Hazelcast-pr-EE-compiler` of your PR failed. (Hazelcast internal details: [build log](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-EE-compiler/10285/Hazelcast-pr-EE-compiler-10285.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-EE-compiler/10285/Hazelcast-pr-EE-compiler-10285.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] COMPILATION ERROR : 
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[59,28] wrong number of type arguments; required 2
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] COMPILATION ERROR : 
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[59,28] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[379,32] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[383,32] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[389,32] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[394,34] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[67,29] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[567,33] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[571,33] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[577,33] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[581,35] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/AllTypesGenericMapStoreTest.java:[70,28] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[136,25] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[146,25] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[184,25] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[586,25] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[134,24] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[144,24] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[398,24] wrong number of type arguments; required 2
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:testCompile (default-testCompile) on project hazelcast-mapstore: Compilation failure: Compilation failure: 
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[59,28] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[379,32] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[383,32] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[389,32] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:[394,34] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[67,29] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[567,33] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[571,33] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[577,33] wrong number of type arguments; required 2
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-EE-compiler/hazelcast/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:[581,35] wrong number of  [...]

2023-11-07 08:29 UTC, hz-devops-test commented
The job `Hazelcast-pr-compiler` of your PR failed. (Hazelcast internal details: [build log](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-compiler/10861/Hazelcast-pr-compiler-10861.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-compiler/10861/Hazelcast-pr-compiler-10861.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mapstore/src/main/java/com/hazelcast/mapstore/GenericMapStoreProperties.java:26:54: Using the '.*' form of import should be avoided - com.hazelcast.mapstore.GenericMapLoader.*. [AvoidStarImport]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mapstore/src/main/java/com/hazelcast/mapstore/GenericMapStore.java:70: Line is longer than 123 characters (found 164). [LineLength]
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.3.1:checkstyle (default) on project hazelcast-mapstore: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There are 2 errors reported by Checkstyle 9.3 with /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mapstore/../../checkstyle/checkstyle_jet.xml ruleset. -> [Help 1]
--------------------------
[ERROR] 
--------------------------
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
--------------------------
[ERROR] 
--------------------------
[ERROR] For more information about the errors and possible solutions, please read the following articles:
--------------------------
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
--------------------------
[ERROR] 
--------------------------
[ERROR] After correcting the problems, you can resume the build with the command
--------------------------
[ERROR]   mvn <args> -rf :hazelcast-mapstore
--------------------------
</pre>
</details>

2023-11-07 17:12 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/21620/Hazelcast-pr-builder-21620.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/21620/Hazelcast-pr-builder-21620.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/extensions/mapstore/src/main/java/com/hazelcast/mapstore/GenericMapStore.java:70: Line is longer than 123 characters (found 164). [LineLength]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/extensions/mapstore/src/main/java/com/hazelcast/mapstore/GenericMapStoreProperties.java:26:54: Using the '.*' form of import should be avoided - com.hazelcast.mapstore.GenericMapLoader.*. [AvoidStarImport]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:394: Line is longer than 123 characters (found 129). [LineLength]
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.3.1:checkstyle (default) on project hazelcast-mapstore: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There are 3 errors reported by Checkstyle 9.3 with /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/extensions/mapstore/../../checkstyle/checkstyle_jet.xml ruleset. -> [Help 1]
--------------------------
[ERROR] 
--------------------------
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
--------------------------
[ERROR] 
--------------------------
[ERROR] For more information about the errors and possible solutions, please read the following articles:
--------------------------
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
--------------------------
[ERROR] 
--------------------------
[ERROR] After correcting the problems, you can resume the build with the command
--------------------------
[ERROR]   mvn <args> -rf :hazelcast-mapstore
--------------------------
</pre>
</details>

2023-11-07 17:20 UTC, hz-devops-test commented
The job `Hazelcast-pr-compiler` of your PR failed. (Hazelcast internal details: [build log](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-compiler/10893/Hazelcast-pr-compiler-10893.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-compiler/10893/Hazelcast-pr-compiler-10893.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mapstore/src/main/java/com/hazelcast/mapstore/GenericMapStore.java:70: Line is longer than 123 characters (found 164). [LineLength]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mapstore/src/main/java/com/hazelcast/mapstore/GenericMapStoreProperties.java:26:54: Using the '.*' form of import should be avoided - com.hazelcast.mapstore.GenericMapLoader.*. [AvoidStarImport]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:394: Line is longer than 123 characters (found 129). [LineLength]
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.3.1:checkstyle (default) on project hazelcast-mapstore: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There are 3 errors reported by Checkstyle 9.3 with /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mapstore/../../checkstyle/checkstyle_jet.xml ruleset. -> [Help 1]
--------------------------
[ERROR] 
--------------------------
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
--------------------------
[ERROR] 
--------------------------
[ERROR] For more information about the errors and possible solutions, please read the following articles:
--------------------------
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
--------------------------
[ERROR] 
--------------------------
[ERROR] After correcting the problems, you can resume the build with the command
--------------------------
[ERROR]   mvn <args> -rf :hazelcast-mapstore
--------------------------
</pre>
</details>

2023-11-22 12:39 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/21880/Hazelcast-pr-builder-21880.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/21880/Hazelcast-pr-builder-21880.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_2/extensions/mapstore/src/main/java/com/hazelcast/mapstore/GenericMapStore.java:70: Line is longer than 123 characters (found 164). [LineLength]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_2/extensions/mapstore/src/main/java/com/hazelcast/mapstore/GenericMapStoreProperties.java:26:54: Using the '.*' form of import should be avoided - com.hazelcast.mapstore.GenericMapLoader.*. [AvoidStarImport]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_2/extensions/mapstore/src/test/java/com/hazelcast/mapstore/AllTypesGenericMapStoreTest.java:40:17: Using the '.*' form of import should be avoided - java.time.*. [AvoidStarImport]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_2/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:44:54: Using the '.*' form of import should be avoided - com.hazelcast.mapstore.GenericMapLoader.*. [AvoidStarImport]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_2/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:620: Line is longer than 123 characters (found 129). [LineLength]
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.3.1:checkstyle (default) on project hazelcast-mapstore: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There are 5 errors reported by Checkstyle 9.3 with /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_2/extensions/mapstore/../../checkstyle/checkstyle_jet.xml ruleset. -> [Help 1]
--------------------------
[ERROR] 
--------------------------
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
--------------------------
[ERROR] 
--------------------------
[ERROR] For more information about the errors and possible solutions, please read the following articles:
--------------------------
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
--------------------------
[ERROR] 
--------------------------
[ERROR] After correcting the problems, you can resume the build with the command
--------------------------
[ERROR]   mvn <args> -rf :hazelcast-mapstore
--------------------------
</pre>
</details>

2023-11-22 12:47 UTC, hz-devops-test commented
The job `Hazelcast-pr-compiler` of your PR failed. (Hazelcast internal details: [build log](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-compiler/11152/Hazelcast-pr-compiler-11152.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-compiler/11152/Hazelcast-pr-compiler-11152.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler_3/extensions/mapstore/src/main/java/com/hazelcast/mapstore/GenericMapStoreProperties.java:26:54: Using the '.*' form of import should be avoided - com.hazelcast.mapstore.GenericMapLoader.*. [AvoidStarImport]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler_3/extensions/mapstore/src/main/java/com/hazelcast/mapstore/GenericMapStore.java:70: Line is longer than 123 characters (found 164). [LineLength]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler_3/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:620: Line is longer than 123 characters (found 129). [LineLength]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler_3/extensions/mapstore/src/test/java/com/hazelcast/mapstore/AllTypesGenericMapStoreTest.java:40:17: Using the '.*' form of import should be avoided - java.time.*. [AvoidStarImport]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler_3/extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapLoaderTest.java:44:54: Using the '.*' form of import should be avoided - com.hazelcast.mapstore.GenericMapLoader.*. [AvoidStarImport]
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.3.1:checkstyle (default) on project hazelcast-mapstore: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There are 5 errors reported by Checkstyle 9.3 with /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler_3/extensions/mapstore/../../checkstyle/checkstyle_jet.xml ruleset. -> [Help 1]
--------------------------
[ERROR] 
--------------------------
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
--------------------------
[ERROR] 
--------------------------
[ERROR] For more information about the errors and possible solutions, please read the following articles:
--------------------------
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
--------------------------
[ERROR] 
--------------------------
[ERROR] After correcting the problems, you can resume the build with the command
--------------------------
[ERROR]   mvn <args> -rf :hazelcast-mapstore
--------------------------
</pre>
</details>

2023-11-22 15:45 UTC, frant-hartm requested changes

2023-11-22 15:58 UTC, TomaszGaweda reviewed
Minor comments only

2023-11-22 15:58 UTC, TomaszGaweda commented on extensions/mapstore/src/test/java/com/hazelcast/mapstore/AllTypesGenericMapStoreTest.java
> +    public Consumer<Tuple3<GenericRecordBuilder, String, Object>> setField;
For this I'd create a own functional interface + tuple record (java 17 would be awesome here :P )

2023-11-22 15:58 UTC, TomaszGaweda commented on extensions/mapstore/src/test/java/com/hazelcast/mapstore/AllTypesGenericMapStoreTest.java
> +    private String tableNameSingleColumn;
at this point I'd extract single-column tests to separate class, then assertions also will be in test method instead of consumers

2023-11-22 19:17 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/21898/Hazelcast-pr-builder-21898.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/21898/Hazelcast-pr-builder-21898.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/extensions/mapstore/src/test/java/com/hazelcast/mapstore/SingleColumnGenericMapStoreIntegrationTest.java:25:8: Unused import - com.hazelcast.internal.util.FilteringClassLoader. [UnusedImports]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/extensions/mapstore/src/test/java/com/hazelcast/mapstore/SingleColumnGenericMapStoreIntegrationTest.java:52:15: Unused import - org.assertj.core.util.Lists.newArrayList. [UnusedImports]
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.3.1:checkstyle (default) on project hazelcast-mapstore: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There are 2 errors reported by Checkstyle 9.3 with /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/extensions/mapstore/../../checkstyle/checkstyle_jet.xml ruleset. -> [Help 1]
--------------------------
[ERROR] 
--------------------------
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
--------------------------
[ERROR] 
--------------------------
[ERROR] For more information about the errors and possible solutions, please read the following articles:
--------------------------
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
--------------------------
[ERROR] 
--------------------------
[ERROR] After correcting the problems, you can resume the build with the command
--------------------------
[ERROR]   mvn <args> -rf :hazelcast-mapstore
--------------------------
</pre>
</details>

2023-11-22 19:22 UTC, hz-devops-test commented
The job `Hazelcast-pr-compiler` of your PR failed. (Hazelcast internal details: [build log](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-compiler/11178/Hazelcast-pr-compiler-11178.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-compiler/11178/Hazelcast-pr-compiler-11178.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mapstore/src/test/java/com/hazelcast/mapstore/SingleColumnGenericMapStoreIntegrationTest.java:25:8: Unused import - com.hazelcast.internal.util.FilteringClassLoader. [UnusedImports]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mapstore/src/test/java/com/hazelcast/mapstore/SingleColumnGenericMapStoreIntegrationTest.java:52:15: Unused import - org.assertj.core.util.Lists.newArrayList. [UnusedImports]
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.3.1:checkstyle (default) on project hazelcast-mapstore: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There are 2 errors reported by Checkstyle 9.3 with /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler/extensions/mapstore/../../checkstyle/checkstyle_jet.xml ruleset. -> [Help 1]
--------------------------
[ERROR] 
--------------------------
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
--------------------------
[ERROR] 
--------------------------
[ERROR] For more information about the errors and possible solutions, please read the following articles:
--------------------------
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
--------------------------
[ERROR] 
--------------------------
[ERROR] After correcting the problems, you can resume the build with the command
--------------------------
[ERROR]   mvn <args> -rf :hazelcast-mapstore
--------------------------
</pre>
</details>

2023-11-22 20:31 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/21900/Hazelcast-pr-builder-21900.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/21900/Hazelcast-pr-builder-21900.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
---------ERRORS-----------
--------------------------
[ERROR] Tests run: 13, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.988 s <<< FAILURE! -- in com.hazelcast.internal.tpcengine.nio.NioAsyncServerSocketTest
--------------------------
[ERROR] com.hazelcast.internal.tpcengine.nio.NioAsyncServerSocketTest.test_createCloseLoop_withSameReactor -- Time elapsed: 0.121 s <<< ERROR!
--------------------------
[ERROR] Errors: 
--------------------------
[ERROR]   NioAsyncServerSocketTest>AsyncServerSocketTest.test_createCloseLoop_withSameReactor:255 ? UncheckedIO Failed to bind to /127.0.0.1:5001
--------------------------
[ERROR] Tests run: 300, Failures: 0, Errors: 1, Skipped: 0
--------------------------
[ERROR] 
--------------------------
</pre>
</details>

2023-11-23 07:27 UTC, Edizc commented
run-lab-run

2023-11-23 14:43 UTC, frant-hartm approved these changes

2023-11-23 15:57 UTC, merged