Add Namespace awareness for all available UDFs [HZ-2576]
hazelcast/hazelcast pull request #26148
Opened 2023-12-05 19:16 UTC by JamesHazelcast

This PR focuses on the changes required for the introduction of Namespace awareness to User-Defined Functions, primarily in relation to data structures, although "default" Namespace awareness is provided to UDFs not associated with a data structure.
[Namespaces feature TTD for reference](https://gist.github.com/JamesHazelcast/f25007a4e0594c491ce867c816b616a7).

_This PR is 1 of 5 pertaining to the Namespace feature addition. The other 4 PRs can be found below:_
- <PR1>
- <PR2>
- <PR3>
- <PR4>

_Due to the Namespaces feature being split into 5 pieces for easier reviewing, it is highly recommended that you clone the [UCD feature development branch](https://github.com/vbekiaris/hazelcast/tree/enhancements/5.4.0/ucd) for testing purposes, as these individual PRs are likely non-functional standalone._

2023-12-05 19:16 UTC, hz-devops-test commented
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/22172/Hazelcast-pr-builder-22172.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/22172/Hazelcast-pr-builder-22172.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
---------ERRORS-----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.4.1:enforce (enforce-tools) on project hazelcast-root: 
--------------------------
[ERROR] Rule 0: org.apache.maven.enforcer.rules.version.RequireJavaVersion failed with message:
--------------------------
[ERROR] Detected JDK version 1.8.0-351 (JAVA_HOME=/usr/share/jdks/oracle-8/jre) is not in the allowed range [11,).
--------------------------
[ERROR] -> [Help 1]
--------------------------
[ERROR] 
--------------------------
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
--------------------------
[ERROR] 
--------------------------
[ERROR] For more information about the errors and possible solutions, please read the following articles:
--------------------------
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
--------------------------
</pre>
</details>

2023-12-05 19:24 UTC, hz-devops-test commented
The job `Hazelcast-pr-compiler` of your PR failed. (Hazelcast internal details: [build log](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-compiler/11438/Hazelcast-pr-compiler-11438.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-compiler/11438/Hazelcast-pr-compiler-11438.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] COMPILATION ERROR : 
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler_2/hazelcast/src/main/java/com/hazelcast/internal/cluster/impl/ClusterServiceImpl.java:[44,40] package com.hazelcast.internal.namespace does not exist
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] COMPILATION ERROR : 
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler_2/hazelcast/src/main/java/com/hazelcast/internal/cluster/impl/ClusterServiceImpl.java:[44,40] package com.hazelcast.internal.namespace does not exist
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler_2/hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractCacheService.java:[40,40] package com.hazelcast.internal.namespace does not exist
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler_2/hazelcast/src/main/java/com/hazelcast/cache/impl/operation/OnJoinCacheOperation.java:[23,40] package com.hazelcast.internal.namespace does not exist
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler_2/hazelcast/src/main/java/com/hazelcast/cache/impl/operation/OnJoinCacheOperation.java:[24,45] package com.hazelcast.internal.namespace.impl does not exist
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler_2/hazelcast/src/main/java/com/hazelcast/cache/impl/operation/CacheReplicationOperation.java:[26,40] package com.hazelcast.internal.namespace does not exist
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler_2/hazelcast/src/main/java/com/hazelcast/cache/impl/operation/CacheReplicationOperation.java:[27,45] package com.hazelcast.internal.namespace.impl does not exist
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler_2/hazelcast/src/main/java/com/hazelcast/ringbuffer/impl/RingbufferContainer.java:[22,40] package com.hazelcast.internal.namespace does not exist
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler_2/hazelcast/src/main/java/com/hazelcast/ringbuffer/impl/RingbufferStoreWrapper.java:[21,40] package com.hazelcast.internal.namespace does not exist
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler_2/hazelcast/src/main/java/com/hazelcast/scheduledexecutor/impl/TaskDefinition.java:[20,40] package com.hazelcast.internal.namespace does not exist
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler_2/hazelcast/src/main/java/com/hazelcast/scheduledexecutor/impl/TaskDefinition.java:[21,45] package com.hazelcast.internal.namespace.impl does not exist
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler_2/hazelcast/src/main/java/com/hazelcast/multimap/impl/MultiMapEventsDispatcher.java:[21,40] package com.hazelcast.internal.namespace does not exist
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler_2/hazelcast/src/main/java/com/hazelcast/collection/impl/queue/QueueContainer.java:[24,40] package com.hazelcast.internal.namespace does not exist
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler_2/hazelcast/src/main/java/com/hazelcast/collection/impl/queue/QueueStoreWrapper.java:[24,40] package com.hazelcast.internal.namespace does not exist
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler_2/hazelcast/src/main/java/com/hazelcast/collection/impl/queue/QueueService.java:[35,40] package com.hazelcast.internal.namespace does not exist
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler_2/hazelcast/src/main/java/com/hazelcast/collection/impl/queue/QueueProxySupport.java:[37,40] package com.hazelcast.internal.namespace does not exist
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler_2/hazelcast/src/main/java/com/hazelcast/map/impl/querycache/accumulator/AccumulatorInfo.java:[20,40] package com.hazelcast.internal.namespace does not exist
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler_2/hazelcast/src/main/java/com/hazelcast/map/impl/querycache/accumulator/AccumulatorInfo.java:[21,45] package com.hazelcast.internal.namespace.impl does not exist
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler_2/hazelcast/src/main/java/com/hazelcast/query/impl/getters/Extractors.java:[21,40] package com.hazelcast.internal.namespace does not exist
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler_2/hazelcast/src/main/java/com/hazelcast/query/impl/getters/ExtractorHelper.java:[20,40] package com.hazelcast.internal.namespace does not exist
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler_2/hazelcast/src/main/java/com/hazelcast/map/impl/MapContainer.java:[25,40] package com.hazelcast.internal.namespace does not exist
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler_2/hazelcast/src/main/java/com/hazelcast/map/impl/query/Query.java:[20,40] package com.hazelcast.internal.namespace does not exist
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler_2/hazelcast/src/main/java/com/hazelcast/map/impl/query/Query.java:[21,45] package com.hazelcast.internal.namespace.impl does not exist
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler_2/hazelcast/src/main/java/com/hazelcast/map/impl/operation/MapOperation.java:[21,40] package com.hazelcast.internal.namespace does not exist
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler_2/hazelcast/src/main/java/com/hazelcast/map/impl/operation/MapOperation.java:[22,45] package com.hazelcast.internal.namespace.impl does not exist
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler_2/hazelcast/src/main/java/com/hazelcast/map/impl/operation/steps/engine/StepRunner.java:[20,40] package com.hazelcast.internal.namespace does not exist
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler_2/hazelcast/src/main/java/com/hazelcast/map/impl/MapStoreWrapper.java:[22,40] package com.hazelcast.internal.namespace does not exist
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler_2/hazelcast/src/main/java/com/hazelcast/splitbrainprotection/impl/SplitBrainProtectionServiceImpl.java:[27,40] package com.hazelcast.internal.namespace does not exist
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler_2/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/AbstractPartitionMessageTask.java:[21,40] package com.hazelcast.internal.namespace does not exist
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-compiler_2/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/AbstractAllPartitionsMessageTas [...]

2023-12-12 16:05 UTC, frant-hartm requested changes
Concurrent replacement of config - should the currently executing user code successfully finish?
It seems that the following can happen:
Run entry processor:
- processor is deserialized using namespace version 1
- replace namespace with version 2
- processor is executed using runWithNamespace version 2

IMap#replaceAll is not implemented with namespaces.

2023-12-13 13:45 UTC, JamesHazelcast commented
> Concurrent replacement of config - should the currently executing user code successfully finish? It seems that the following can happen: Run entry processor:
> 
> * processor is deserialized using namespace version 1
> * replace namespace with version 2
> * processor is executed using runWithNamespace version 2

Yes this is the intended flow - we do not make any attempts to stop/interrupt/restart use of a Namespace when it is replaced, we rely on the next call using the updated Namespace instead.

2023-12-13 13:48 UTC, JamesHazelcast commented on hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractCacheService.java
> +    public Object toObject(Object data, String namespace) {
There was already an existing `toObject` method that most/all cache operations were already using - so I just created a Namespace specific variant next to it to reduce duplicate code in all uses.

2023-12-13 15:30 UTC, JamesHazelcast commented on hazelcast/src/main/java/com/hazelcast/spi/annotation/NamespacesSupported.java
> +@Retention(RetentionPolicy.RUNTIME)
Good suggestion, thanks. Addressed in https://github.com/vbekiaris/hazelcast/commit/9001630d3b19a18d65bff86bfd811931b87a5dcb

2023-12-13 15:44 UTC, vbekiaris reviewed
I see no `getNamespacePermission` to `USE` namespace in Executor/ScheduledExecutor/DurableExecutor message tasks that submit a runnable/callable.
On EE side, we would need permissions tests - if we can take advantage of existing `UCDTest` children and test them with/without required client permissions, we would have caught those missing `getNamespacePermission()` overrides.

2023-12-13 16:00 UTC, JamesHazelcast commented on hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/AbstractMessageTask.java
> +    protected static Collection<Permission> extendPermissions(@Nullable Collection<Permission> parentPermissions,
Yep! Thanks, addressed in https://github.com/vbekiaris/hazelcast/commit/b5185b6b8213d3cd2560670d07ada944804720c5

2023-12-13 16:32 UTC, vbekiaris approved these changes
✅ 

kudos @JamesHazelcast , @JackPGreen , @gareth-johnston

2023-12-15 14:05 UTC, JamesHazelcast commented
Closing this PR due to the creation of the final mono-repo PR: https://github.com/hazelcast/hazelcast-mono/pull/217 🎉

2023-12-15 14:05 UTC, closed without merging